// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ConsumptionsColumns holds the columns for the "consumptions" table.
	ConsumptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "warehouse_id", Type: field.TypeUUID, Nullable: true},
		{Name: "items", Type: field.TypeJSON},
		{Name: "reason", Type: field.TypeString, Default: "sale"},
		{Name: "status", Type: field.TypeString, Default: "processed"},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "processed_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ConsumptionsTable holds the schema information for the "consumptions" table.
	ConsumptionsTable = &schema.Table{
		Name:       "consumptions",
		Columns:    ConsumptionsColumns,
		PrimaryKey: []*schema.Column{ConsumptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "consumption_tenant_id_order_id",
				Unique:  false,
				Columns: []*schema.Column{ConsumptionsColumns[1], ConsumptionsColumns[2]},
			},
			{
				Name:    "consumption_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{ConsumptionsColumns[7]},
			},
		},
	}
	// InventoryBalancesColumns holds the columns for the "inventory_balances" table.
	InventoryBalancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "on_hand", Type: field.TypeInt, Default: 0},
		{Name: "available", Type: field.TypeInt, Default: 0},
		{Name: "reserved", Type: field.TypeInt, Default: 0},
		{Name: "unit_of_measure", Type: field.TypeString, Default: "PIECE"},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "item_id", Type: field.TypeUUID},
		{Name: "warehouse_id", Type: field.TypeUUID},
	}
	// InventoryBalancesTable holds the schema information for the "inventory_balances" table.
	InventoryBalancesTable = &schema.Table{
		Name:       "inventory_balances",
		Columns:    InventoryBalancesColumns,
		PrimaryKey: []*schema.Column{InventoryBalancesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "inventory_balances_items_balances",
				Columns:    []*schema.Column{InventoryBalancesColumns[7]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "inventory_balances_warehouses_balances",
				Columns:    []*schema.Column{InventoryBalancesColumns[8]},
				RefColumns: []*schema.Column{WarehousesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "inventorybalance_tenant_id_item_id_warehouse_id",
				Unique:  true,
				Columns: []*schema.Column{InventoryBalancesColumns[1], InventoryBalancesColumns[7], InventoryBalancesColumns[8]},
			},
			{
				Name:    "inventorybalance_tenant_id_item_id",
				Unique:  false,
				Columns: []*schema.Column{InventoryBalancesColumns[1], InventoryBalancesColumns[7]},
			},
		},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "sku", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "unit_of_measure", Type: field.TypeString, Default: "PIECE"},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "item_tenant_id_sku",
				Unique:  true,
				Columns: []*schema.Column{ItemsColumns[1], ItemsColumns[2]},
			},
			{
				Name:    "item_tenant_id_category",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[1], ItemsColumns[5]},
			},
			{
				Name:    "item_tenant_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{ItemsColumns[1], ItemsColumns[8]},
			},
		},
	}
	// ReservationsColumns holds the columns for the "reservations" table.
	ReservationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "items", Type: field.TypeJSON},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "confirmed_at", Type: field.TypeTime, Nullable: true},
		{Name: "idempotency_key", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "warehouse_id", Type: field.TypeUUID, Nullable: true},
	}
	// ReservationsTable holds the schema information for the "reservations" table.
	ReservationsTable = &schema.Table{
		Name:       "reservations",
		Columns:    ReservationsColumns,
		PrimaryKey: []*schema.Column{ReservationsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reservations_warehouses_reservations",
				Columns:    []*schema.Column{ReservationsColumns[10]},
				RefColumns: []*schema.Column{WarehousesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "reservation_tenant_id_order_id",
				Unique:  false,
				Columns: []*schema.Column{ReservationsColumns[1], ReservationsColumns[2]},
			},
			{
				Name:    "reservation_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{ReservationsColumns[1], ReservationsColumns[3]},
			},
			{
				Name:    "reservation_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{ReservationsColumns[7]},
			},
		},
	}
	// WarehousesColumns holds the columns for the "warehouses" table.
	WarehousesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "tenant_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "code", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// WarehousesTable holds the schema information for the "warehouses" table.
	WarehousesTable = &schema.Table{
		Name:       "warehouses",
		Columns:    WarehousesColumns,
		PrimaryKey: []*schema.Column{WarehousesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "warehouse_tenant_id_code",
				Unique:  true,
				Columns: []*schema.Column{WarehousesColumns[1], WarehousesColumns[3]},
			},
			{
				Name:    "warehouse_tenant_id_is_default",
				Unique:  false,
				Columns: []*schema.Column{WarehousesColumns[1], WarehousesColumns[5]},
			},
			{
				Name:    "warehouse_tenant_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{WarehousesColumns[1], WarehousesColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ConsumptionsTable,
		InventoryBalancesTable,
		ItemsTable,
		ReservationsTable,
		WarehousesTable,
	}
)

func init() {
	InventoryBalancesTable.ForeignKeys[0].RefTable = ItemsTable
	InventoryBalancesTable.ForeignKeys[1].RefTable = WarehousesTable
	ReservationsTable.ForeignKeys[0].RefTable = WarehousesTable
}
