// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/inventory-service/internal/ent/approvalrule"
	"github.com/google/uuid"
)

// ApprovalRule is the model entity for the ApprovalRule schema.
type ApprovalRule struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Owning tenant
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Document type this rule governs
	Module approvalrule.Module `json:"module,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Inclusive lower bound of the amount band
	MinAmount float64 `json:"min_amount,omitempty"`
	// Inclusive upper bound; nil = unbounded (and above)
	MaxAmount *float64 `json:"max_amount,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApprovalRuleQuery when eager-loading is set.
	Edges        ApprovalRuleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApprovalRuleEdges holds the relations/edges for other nodes in the graph.
type ApprovalRuleEdges struct {
	// Steps holds the value of the steps edge.
	Steps []*ApprovalStep `json:"steps,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StepsOrErr returns the Steps value or an error if the edge
// was not loaded in eager-loading.
func (e ApprovalRuleEdges) StepsOrErr() ([]*ApprovalStep, error) {
	if e.loadedTypes[0] {
		return e.Steps, nil
	}
	return nil, &NotLoadedError{edge: "steps"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApprovalRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case approvalrule.FieldIsActive:
			values[i] = new(sql.NullBool)
		case approvalrule.FieldMinAmount, approvalrule.FieldMaxAmount:
			values[i] = new(sql.NullFloat64)
		case approvalrule.FieldModule, approvalrule.FieldName:
			values[i] = new(sql.NullString)
		case approvalrule.FieldCreatedAt, approvalrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case approvalrule.FieldID, approvalrule.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApprovalRule fields.
func (_m *ApprovalRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case approvalrule.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case approvalrule.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case approvalrule.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = approvalrule.Module(value.String)
			}
		case approvalrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case approvalrule.FieldMinAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field min_amount", values[i])
			} else if value.Valid {
				_m.MinAmount = value.Float64
			}
		case approvalrule.FieldMaxAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_amount", values[i])
			} else if value.Valid {
				_m.MaxAmount = new(float64)
				*_m.MaxAmount = value.Float64
			}
		case approvalrule.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case approvalrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case approvalrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApprovalRule.
// This includes values selected through modifiers, order, etc.
func (_m *ApprovalRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySteps queries the "steps" edge of the ApprovalRule entity.
func (_m *ApprovalRule) QuerySteps() *ApprovalStepQuery {
	return NewApprovalRuleClient(_m.config).QuerySteps(_m)
}

// Update returns a builder for updating this ApprovalRule.
// Note that you need to call ApprovalRule.Unwrap() before calling this method if this ApprovalRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApprovalRule) Update() *ApprovalRuleUpdateOne {
	return NewApprovalRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApprovalRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApprovalRule) Unwrap() *ApprovalRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApprovalRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApprovalRule) String() string {
	var builder strings.Builder
	builder.WriteString("ApprovalRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("module=")
	builder.WriteString(fmt.Sprintf("%v", _m.Module))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("min_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinAmount))
	builder.WriteString(", ")
	if v := _m.MaxAmount; v != nil {
		builder.WriteString("max_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ApprovalRules is a parsable slice of ApprovalRule.
type ApprovalRules []*ApprovalRule
