// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/batchrawmaterial"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
)

// BatchRawMaterialDelete is the builder for deleting a BatchRawMaterial entity.
type BatchRawMaterialDelete struct {
	config
	hooks    []Hook
	mutation *BatchRawMaterialMutation
}

// Where appends a list predicates to the BatchRawMaterialDelete builder.
func (_d *BatchRawMaterialDelete) Where(ps ...predicate.BatchRawMaterial) *BatchRawMaterialDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BatchRawMaterialDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BatchRawMaterialDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BatchRawMaterialDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(batchrawmaterial.Table, sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BatchRawMaterialDeleteOne is the builder for deleting a single BatchRawMaterial entity.
type BatchRawMaterialDeleteOne struct {
	_d *BatchRawMaterialDelete
}

// Where appends a list predicates to the BatchRawMaterialDelete builder.
func (_d *BatchRawMaterialDeleteOne) Where(ps ...predicate.BatchRawMaterial) *BatchRawMaterialDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BatchRawMaterialDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{batchrawmaterial.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BatchRawMaterialDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
