// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/bundle"
	"github.com/bengobox/inventory-service/internal/ent/bundlecomponent"
	"github.com/bengobox/inventory-service/internal/ent/item"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// BundleComponentUpdate is the builder for updating BundleComponent entities.
type BundleComponentUpdate struct {
	config
	hooks    []Hook
	mutation *BundleComponentMutation
}

// Where appends a list predicates to the BundleComponentUpdate builder.
func (_u *BundleComponentUpdate) Where(ps ...predicate.BundleComponent) *BundleComponentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBundleID sets the "bundle_id" field.
func (_u *BundleComponentUpdate) SetBundleID(v uuid.UUID) *BundleComponentUpdate {
	_u.mutation.SetBundleID(v)
	return _u
}

// SetNillableBundleID sets the "bundle_id" field if the given value is not nil.
func (_u *BundleComponentUpdate) SetNillableBundleID(v *uuid.UUID) *BundleComponentUpdate {
	if v != nil {
		_u.SetBundleID(*v)
	}
	return _u
}

// SetComponentItemID sets the "component_item_id" field.
func (_u *BundleComponentUpdate) SetComponentItemID(v uuid.UUID) *BundleComponentUpdate {
	_u.mutation.SetComponentItemID(v)
	return _u
}

// SetNillableComponentItemID sets the "component_item_id" field if the given value is not nil.
func (_u *BundleComponentUpdate) SetNillableComponentItemID(v *uuid.UUID) *BundleComponentUpdate {
	if v != nil {
		_u.SetComponentItemID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *BundleComponentUpdate) SetQuantity(v int) *BundleComponentUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *BundleComponentUpdate) SetNillableQuantity(v *int) *BundleComponentUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *BundleComponentUpdate) AddQuantity(v int) *BundleComponentUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BundleComponentUpdate) SetSortOrder(v int) *BundleComponentUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BundleComponentUpdate) SetNillableSortOrder(v *int) *BundleComponentUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BundleComponentUpdate) AddSortOrder(v int) *BundleComponentUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundle entity.
func (_u *BundleComponentUpdate) SetBundle(v *Bundle) *BundleComponentUpdate {
	return _u.SetBundleID(v.ID)
}

// SetComponentItem sets the "component_item" edge to the Item entity.
func (_u *BundleComponentUpdate) SetComponentItem(v *Item) *BundleComponentUpdate {
	return _u.SetComponentItemID(v.ID)
}

// Mutation returns the BundleComponentMutation object of the builder.
func (_u *BundleComponentUpdate) Mutation() *BundleComponentMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundle entity.
func (_u *BundleComponentUpdate) ClearBundle() *BundleComponentUpdate {
	_u.mutation.ClearBundle()
	return _u
}

// ClearComponentItem clears the "component_item" edge to the Item entity.
func (_u *BundleComponentUpdate) ClearComponentItem() *BundleComponentUpdate {
	_u.mutation.ClearComponentItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BundleComponentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleComponentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BundleComponentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleComponentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleComponentUpdate) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleComponent.bundle"`)
	}
	if _u.mutation.ComponentItemCleared() && len(_u.mutation.ComponentItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleComponent.component_item"`)
	}
	return nil
}

func (_u *BundleComponentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlecomponent.Table, bundlecomponent.Columns, sqlgraph.NewFieldSpec(bundlecomponent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(bundlecomponent.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(bundlecomponent.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(bundlecomponent.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundlecomponent.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.BundleTable,
			Columns: []string{bundlecomponent.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.BundleTable,
			Columns: []string{bundlecomponent.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ComponentItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.ComponentItemTable,
			Columns: []string{bundlecomponent.ComponentItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.ComponentItemTable,
			Columns: []string{bundlecomponent.ComponentItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlecomponent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BundleComponentUpdateOne is the builder for updating a single BundleComponent entity.
type BundleComponentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BundleComponentMutation
}

// SetBundleID sets the "bundle_id" field.
func (_u *BundleComponentUpdateOne) SetBundleID(v uuid.UUID) *BundleComponentUpdateOne {
	_u.mutation.SetBundleID(v)
	return _u
}

// SetNillableBundleID sets the "bundle_id" field if the given value is not nil.
func (_u *BundleComponentUpdateOne) SetNillableBundleID(v *uuid.UUID) *BundleComponentUpdateOne {
	if v != nil {
		_u.SetBundleID(*v)
	}
	return _u
}

// SetComponentItemID sets the "component_item_id" field.
func (_u *BundleComponentUpdateOne) SetComponentItemID(v uuid.UUID) *BundleComponentUpdateOne {
	_u.mutation.SetComponentItemID(v)
	return _u
}

// SetNillableComponentItemID sets the "component_item_id" field if the given value is not nil.
func (_u *BundleComponentUpdateOne) SetNillableComponentItemID(v *uuid.UUID) *BundleComponentUpdateOne {
	if v != nil {
		_u.SetComponentItemID(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *BundleComponentUpdateOne) SetQuantity(v int) *BundleComponentUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *BundleComponentUpdateOne) SetNillableQuantity(v *int) *BundleComponentUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *BundleComponentUpdateOne) AddQuantity(v int) *BundleComponentUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *BundleComponentUpdateOne) SetSortOrder(v int) *BundleComponentUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *BundleComponentUpdateOne) SetNillableSortOrder(v *int) *BundleComponentUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *BundleComponentUpdateOne) AddSortOrder(v int) *BundleComponentUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetBundle sets the "bundle" edge to the Bundle entity.
func (_u *BundleComponentUpdateOne) SetBundle(v *Bundle) *BundleComponentUpdateOne {
	return _u.SetBundleID(v.ID)
}

// SetComponentItem sets the "component_item" edge to the Item entity.
func (_u *BundleComponentUpdateOne) SetComponentItem(v *Item) *BundleComponentUpdateOne {
	return _u.SetComponentItemID(v.ID)
}

// Mutation returns the BundleComponentMutation object of the builder.
func (_u *BundleComponentUpdateOne) Mutation() *BundleComponentMutation {
	return _u.mutation
}

// ClearBundle clears the "bundle" edge to the Bundle entity.
func (_u *BundleComponentUpdateOne) ClearBundle() *BundleComponentUpdateOne {
	_u.mutation.ClearBundle()
	return _u
}

// ClearComponentItem clears the "component_item" edge to the Item entity.
func (_u *BundleComponentUpdateOne) ClearComponentItem() *BundleComponentUpdateOne {
	_u.mutation.ClearComponentItem()
	return _u
}

// Where appends a list predicates to the BundleComponentUpdate builder.
func (_u *BundleComponentUpdateOne) Where(ps ...predicate.BundleComponent) *BundleComponentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BundleComponentUpdateOne) Select(field string, fields ...string) *BundleComponentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BundleComponent entity.
func (_u *BundleComponentUpdateOne) Save(ctx context.Context) (*BundleComponent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BundleComponentUpdateOne) SaveX(ctx context.Context) *BundleComponent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BundleComponentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BundleComponentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BundleComponentUpdateOne) check() error {
	if _u.mutation.BundleCleared() && len(_u.mutation.BundleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleComponent.bundle"`)
	}
	if _u.mutation.ComponentItemCleared() && len(_u.mutation.ComponentItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "BundleComponent.component_item"`)
	}
	return nil
}

func (_u *BundleComponentUpdateOne) sqlSave(ctx context.Context) (_node *BundleComponent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bundlecomponent.Table, bundlecomponent.Columns, sqlgraph.NewFieldSpec(bundlecomponent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BundleComponent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bundlecomponent.FieldID)
		for _, f := range fields {
			if !bundlecomponent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bundlecomponent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(bundlecomponent.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(bundlecomponent.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(bundlecomponent.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(bundlecomponent.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.BundleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.BundleTable,
			Columns: []string{bundlecomponent.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.BundleTable,
			Columns: []string{bundlecomponent.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ComponentItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.ComponentItemTable,
			Columns: []string{bundlecomponent.ComponentItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ComponentItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bundlecomponent.ComponentItemTable,
			Columns: []string{bundlecomponent.ComponentItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &BundleComponent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bundlecomponent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
