// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/foodcostvariance"
	"github.com/google/uuid"
)

// FoodCostVarianceCreate is the builder for creating a FoodCostVariance entity.
type FoodCostVarianceCreate struct {
	config
	mutation *FoodCostVarianceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *FoodCostVarianceCreate) SetTenantID(v uuid.UUID) *FoodCostVarianceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *FoodCostVarianceCreate) SetPeriodStart(v time.Time) *FoodCostVarianceCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *FoodCostVarianceCreate) SetPeriodEnd(v time.Time) *FoodCostVarianceCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetRecipeSku sets the "recipe_sku" field.
func (_c *FoodCostVarianceCreate) SetRecipeSku(v string) *FoodCostVarianceCreate {
	_c.mutation.SetRecipeSku(v)
	return _c
}

// SetRecipeName sets the "recipe_name" field.
func (_c *FoodCostVarianceCreate) SetRecipeName(v string) *FoodCostVarianceCreate {
	_c.mutation.SetRecipeName(v)
	return _c
}

// SetTheoreticalCost sets the "theoretical_cost" field.
func (_c *FoodCostVarianceCreate) SetTheoreticalCost(v float64) *FoodCostVarianceCreate {
	_c.mutation.SetTheoreticalCost(v)
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *FoodCostVarianceCreate) SetActualCost(v float64) *FoodCostVarianceCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetVariancePct sets the "variance_pct" field.
func (_c *FoodCostVarianceCreate) SetVariancePct(v float64) *FoodCostVarianceCreate {
	_c.mutation.SetVariancePct(v)
	return _c
}

// SetBreakdown sets the "breakdown" field.
func (_c *FoodCostVarianceCreate) SetBreakdown(v map[string]interface{}) *FoodCostVarianceCreate {
	_c.mutation.SetBreakdown(v)
	return _c
}

// SetCalculatedAt sets the "calculated_at" field.
func (_c *FoodCostVarianceCreate) SetCalculatedAt(v time.Time) *FoodCostVarianceCreate {
	_c.mutation.SetCalculatedAt(v)
	return _c
}

// SetNillableCalculatedAt sets the "calculated_at" field if the given value is not nil.
func (_c *FoodCostVarianceCreate) SetNillableCalculatedAt(v *time.Time) *FoodCostVarianceCreate {
	if v != nil {
		_c.SetCalculatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FoodCostVarianceCreate) SetID(v uuid.UUID) *FoodCostVarianceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FoodCostVarianceCreate) SetNillableID(v *uuid.UUID) *FoodCostVarianceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the FoodCostVarianceMutation object of the builder.
func (_c *FoodCostVarianceCreate) Mutation() *FoodCostVarianceMutation {
	return _c.mutation
}

// Save creates the FoodCostVariance in the database.
func (_c *FoodCostVarianceCreate) Save(ctx context.Context) (*FoodCostVariance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FoodCostVarianceCreate) SaveX(ctx context.Context) *FoodCostVariance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FoodCostVarianceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FoodCostVarianceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FoodCostVarianceCreate) defaults() {
	if _, ok := _c.mutation.CalculatedAt(); !ok {
		v := foodcostvariance.DefaultCalculatedAt()
		_c.mutation.SetCalculatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := foodcostvariance.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FoodCostVarianceCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "FoodCostVariance.tenant_id"`)}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "FoodCostVariance.period_start"`)}
	}
	if _, ok := _c.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "FoodCostVariance.period_end"`)}
	}
	if _, ok := _c.mutation.RecipeSku(); !ok {
		return &ValidationError{Name: "recipe_sku", err: errors.New(`ent: missing required field "FoodCostVariance.recipe_sku"`)}
	}
	if v, ok := _c.mutation.RecipeSku(); ok {
		if err := foodcostvariance.RecipeSkuValidator(v); err != nil {
			return &ValidationError{Name: "recipe_sku", err: fmt.Errorf(`ent: validator failed for field "FoodCostVariance.recipe_sku": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RecipeName(); !ok {
		return &ValidationError{Name: "recipe_name", err: errors.New(`ent: missing required field "FoodCostVariance.recipe_name"`)}
	}
	if v, ok := _c.mutation.RecipeName(); ok {
		if err := foodcostvariance.RecipeNameValidator(v); err != nil {
			return &ValidationError{Name: "recipe_name", err: fmt.Errorf(`ent: validator failed for field "FoodCostVariance.recipe_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TheoreticalCost(); !ok {
		return &ValidationError{Name: "theoretical_cost", err: errors.New(`ent: missing required field "FoodCostVariance.theoretical_cost"`)}
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		return &ValidationError{Name: "actual_cost", err: errors.New(`ent: missing required field "FoodCostVariance.actual_cost"`)}
	}
	if _, ok := _c.mutation.VariancePct(); !ok {
		return &ValidationError{Name: "variance_pct", err: errors.New(`ent: missing required field "FoodCostVariance.variance_pct"`)}
	}
	if _, ok := _c.mutation.CalculatedAt(); !ok {
		return &ValidationError{Name: "calculated_at", err: errors.New(`ent: missing required field "FoodCostVariance.calculated_at"`)}
	}
	return nil
}

func (_c *FoodCostVarianceCreate) sqlSave(ctx context.Context) (*FoodCostVariance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FoodCostVarianceCreate) createSpec() (*FoodCostVariance, *sqlgraph.CreateSpec) {
	var (
		_node = &FoodCostVariance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(foodcostvariance.Table, sqlgraph.NewFieldSpec(foodcostvariance.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(foodcostvariance.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(foodcostvariance.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(foodcostvariance.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := _c.mutation.RecipeSku(); ok {
		_spec.SetField(foodcostvariance.FieldRecipeSku, field.TypeString, value)
		_node.RecipeSku = value
	}
	if value, ok := _c.mutation.RecipeName(); ok {
		_spec.SetField(foodcostvariance.FieldRecipeName, field.TypeString, value)
		_node.RecipeName = value
	}
	if value, ok := _c.mutation.TheoreticalCost(); ok {
		_spec.SetField(foodcostvariance.FieldTheoreticalCost, field.TypeFloat64, value)
		_node.TheoreticalCost = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(foodcostvariance.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = value
	}
	if value, ok := _c.mutation.VariancePct(); ok {
		_spec.SetField(foodcostvariance.FieldVariancePct, field.TypeFloat64, value)
		_node.VariancePct = value
	}
	if value, ok := _c.mutation.Breakdown(); ok {
		_spec.SetField(foodcostvariance.FieldBreakdown, field.TypeJSON, value)
		_node.Breakdown = value
	}
	if value, ok := _c.mutation.CalculatedAt(); ok {
		_spec.SetField(foodcostvariance.FieldCalculatedAt, field.TypeTime, value)
		_node.CalculatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FoodCostVariance.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FoodCostVarianceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *FoodCostVarianceCreate) OnConflict(opts ...sql.ConflictOption) *FoodCostVarianceUpsertOne {
	_c.conflict = opts
	return &FoodCostVarianceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FoodCostVarianceCreate) OnConflictColumns(columns ...string) *FoodCostVarianceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FoodCostVarianceUpsertOne{
		create: _c,
	}
}

type (
	// FoodCostVarianceUpsertOne is the builder for "upsert"-ing
	//  one FoodCostVariance node.
	FoodCostVarianceUpsertOne struct {
		create *FoodCostVarianceCreate
	}

	// FoodCostVarianceUpsert is the "OnConflict" setter.
	FoodCostVarianceUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *FoodCostVarianceUpsert) SetTenantID(v uuid.UUID) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateTenantID() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldTenantID)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *FoodCostVarianceUpsert) SetPeriodStart(v time.Time) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdatePeriodStart() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *FoodCostVarianceUpsert) SetPeriodEnd(v time.Time) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdatePeriodEnd() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldPeriodEnd)
	return u
}

// SetRecipeSku sets the "recipe_sku" field.
func (u *FoodCostVarianceUpsert) SetRecipeSku(v string) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldRecipeSku, v)
	return u
}

// UpdateRecipeSku sets the "recipe_sku" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateRecipeSku() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldRecipeSku)
	return u
}

// SetRecipeName sets the "recipe_name" field.
func (u *FoodCostVarianceUpsert) SetRecipeName(v string) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldRecipeName, v)
	return u
}

// UpdateRecipeName sets the "recipe_name" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateRecipeName() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldRecipeName)
	return u
}

// SetTheoreticalCost sets the "theoretical_cost" field.
func (u *FoodCostVarianceUpsert) SetTheoreticalCost(v float64) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldTheoreticalCost, v)
	return u
}

// UpdateTheoreticalCost sets the "theoretical_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateTheoreticalCost() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldTheoreticalCost)
	return u
}

// AddTheoreticalCost adds v to the "theoretical_cost" field.
func (u *FoodCostVarianceUpsert) AddTheoreticalCost(v float64) *FoodCostVarianceUpsert {
	u.Add(foodcostvariance.FieldTheoreticalCost, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *FoodCostVarianceUpsert) SetActualCost(v float64) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateActualCost() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *FoodCostVarianceUpsert) AddActualCost(v float64) *FoodCostVarianceUpsert {
	u.Add(foodcostvariance.FieldActualCost, v)
	return u
}

// SetVariancePct sets the "variance_pct" field.
func (u *FoodCostVarianceUpsert) SetVariancePct(v float64) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldVariancePct, v)
	return u
}

// UpdateVariancePct sets the "variance_pct" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateVariancePct() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldVariancePct)
	return u
}

// AddVariancePct adds v to the "variance_pct" field.
func (u *FoodCostVarianceUpsert) AddVariancePct(v float64) *FoodCostVarianceUpsert {
	u.Add(foodcostvariance.FieldVariancePct, v)
	return u
}

// SetBreakdown sets the "breakdown" field.
func (u *FoodCostVarianceUpsert) SetBreakdown(v map[string]interface{}) *FoodCostVarianceUpsert {
	u.Set(foodcostvariance.FieldBreakdown, v)
	return u
}

// UpdateBreakdown sets the "breakdown" field to the value that was provided on create.
func (u *FoodCostVarianceUpsert) UpdateBreakdown() *FoodCostVarianceUpsert {
	u.SetExcluded(foodcostvariance.FieldBreakdown)
	return u
}

// ClearBreakdown clears the value of the "breakdown" field.
func (u *FoodCostVarianceUpsert) ClearBreakdown() *FoodCostVarianceUpsert {
	u.SetNull(foodcostvariance.FieldBreakdown)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(foodcostvariance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FoodCostVarianceUpsertOne) UpdateNewValues() *FoodCostVarianceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(foodcostvariance.FieldID)
		}
		if _, exists := u.create.mutation.CalculatedAt(); exists {
			s.SetIgnore(foodcostvariance.FieldCalculatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FoodCostVarianceUpsertOne) Ignore() *FoodCostVarianceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FoodCostVarianceUpsertOne) DoNothing() *FoodCostVarianceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FoodCostVarianceCreate.OnConflict
// documentation for more info.
func (u *FoodCostVarianceUpsertOne) Update(set func(*FoodCostVarianceUpsert)) *FoodCostVarianceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FoodCostVarianceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *FoodCostVarianceUpsertOne) SetTenantID(v uuid.UUID) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateTenantID() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateTenantID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *FoodCostVarianceUpsertOne) SetPeriodStart(v time.Time) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdatePeriodStart() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *FoodCostVarianceUpsertOne) SetPeriodEnd(v time.Time) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdatePeriodEnd() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetRecipeSku sets the "recipe_sku" field.
func (u *FoodCostVarianceUpsertOne) SetRecipeSku(v string) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetRecipeSku(v)
	})
}

// UpdateRecipeSku sets the "recipe_sku" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateRecipeSku() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateRecipeSku()
	})
}

// SetRecipeName sets the "recipe_name" field.
func (u *FoodCostVarianceUpsertOne) SetRecipeName(v string) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetRecipeName(v)
	})
}

// UpdateRecipeName sets the "recipe_name" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateRecipeName() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateRecipeName()
	})
}

// SetTheoreticalCost sets the "theoretical_cost" field.
func (u *FoodCostVarianceUpsertOne) SetTheoreticalCost(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetTheoreticalCost(v)
	})
}

// AddTheoreticalCost adds v to the "theoretical_cost" field.
func (u *FoodCostVarianceUpsertOne) AddTheoreticalCost(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddTheoreticalCost(v)
	})
}

// UpdateTheoreticalCost sets the "theoretical_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateTheoreticalCost() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateTheoreticalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *FoodCostVarianceUpsertOne) SetActualCost(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *FoodCostVarianceUpsertOne) AddActualCost(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateActualCost() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateActualCost()
	})
}

// SetVariancePct sets the "variance_pct" field.
func (u *FoodCostVarianceUpsertOne) SetVariancePct(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetVariancePct(v)
	})
}

// AddVariancePct adds v to the "variance_pct" field.
func (u *FoodCostVarianceUpsertOne) AddVariancePct(v float64) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddVariancePct(v)
	})
}

// UpdateVariancePct sets the "variance_pct" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateVariancePct() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateVariancePct()
	})
}

// SetBreakdown sets the "breakdown" field.
func (u *FoodCostVarianceUpsertOne) SetBreakdown(v map[string]interface{}) *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetBreakdown(v)
	})
}

// UpdateBreakdown sets the "breakdown" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertOne) UpdateBreakdown() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateBreakdown()
	})
}

// ClearBreakdown clears the value of the "breakdown" field.
func (u *FoodCostVarianceUpsertOne) ClearBreakdown() *FoodCostVarianceUpsertOne {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.ClearBreakdown()
	})
}

// Exec executes the query.
func (u *FoodCostVarianceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FoodCostVarianceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FoodCostVarianceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FoodCostVarianceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: FoodCostVarianceUpsertOne.ID is not supported by MySQL driver. Use FoodCostVarianceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FoodCostVarianceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FoodCostVarianceCreateBulk is the builder for creating many FoodCostVariance entities in bulk.
type FoodCostVarianceCreateBulk struct {
	config
	err      error
	builders []*FoodCostVarianceCreate
	conflict []sql.ConflictOption
}

// Save creates the FoodCostVariance entities in the database.
func (_c *FoodCostVarianceCreateBulk) Save(ctx context.Context) ([]*FoodCostVariance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FoodCostVariance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FoodCostVarianceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FoodCostVarianceCreateBulk) SaveX(ctx context.Context) []*FoodCostVariance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FoodCostVarianceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FoodCostVarianceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FoodCostVariance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FoodCostVarianceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *FoodCostVarianceCreateBulk) OnConflict(opts ...sql.ConflictOption) *FoodCostVarianceUpsertBulk {
	_c.conflict = opts
	return &FoodCostVarianceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FoodCostVarianceCreateBulk) OnConflictColumns(columns ...string) *FoodCostVarianceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FoodCostVarianceUpsertBulk{
		create: _c,
	}
}

// FoodCostVarianceUpsertBulk is the builder for "upsert"-ing
// a bulk of FoodCostVariance nodes.
type FoodCostVarianceUpsertBulk struct {
	create *FoodCostVarianceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(foodcostvariance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *FoodCostVarianceUpsertBulk) UpdateNewValues() *FoodCostVarianceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(foodcostvariance.FieldID)
			}
			if _, exists := b.mutation.CalculatedAt(); exists {
				s.SetIgnore(foodcostvariance.FieldCalculatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FoodCostVariance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FoodCostVarianceUpsertBulk) Ignore() *FoodCostVarianceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FoodCostVarianceUpsertBulk) DoNothing() *FoodCostVarianceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FoodCostVarianceCreateBulk.OnConflict
// documentation for more info.
func (u *FoodCostVarianceUpsertBulk) Update(set func(*FoodCostVarianceUpsert)) *FoodCostVarianceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FoodCostVarianceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *FoodCostVarianceUpsertBulk) SetTenantID(v uuid.UUID) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateTenantID() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateTenantID()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *FoodCostVarianceUpsertBulk) SetPeriodStart(v time.Time) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdatePeriodStart() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *FoodCostVarianceUpsertBulk) SetPeriodEnd(v time.Time) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdatePeriodEnd() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetRecipeSku sets the "recipe_sku" field.
func (u *FoodCostVarianceUpsertBulk) SetRecipeSku(v string) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetRecipeSku(v)
	})
}

// UpdateRecipeSku sets the "recipe_sku" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateRecipeSku() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateRecipeSku()
	})
}

// SetRecipeName sets the "recipe_name" field.
func (u *FoodCostVarianceUpsertBulk) SetRecipeName(v string) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetRecipeName(v)
	})
}

// UpdateRecipeName sets the "recipe_name" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateRecipeName() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateRecipeName()
	})
}

// SetTheoreticalCost sets the "theoretical_cost" field.
func (u *FoodCostVarianceUpsertBulk) SetTheoreticalCost(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetTheoreticalCost(v)
	})
}

// AddTheoreticalCost adds v to the "theoretical_cost" field.
func (u *FoodCostVarianceUpsertBulk) AddTheoreticalCost(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddTheoreticalCost(v)
	})
}

// UpdateTheoreticalCost sets the "theoretical_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateTheoreticalCost() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateTheoreticalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *FoodCostVarianceUpsertBulk) SetActualCost(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *FoodCostVarianceUpsertBulk) AddActualCost(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateActualCost() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateActualCost()
	})
}

// SetVariancePct sets the "variance_pct" field.
func (u *FoodCostVarianceUpsertBulk) SetVariancePct(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetVariancePct(v)
	})
}

// AddVariancePct adds v to the "variance_pct" field.
func (u *FoodCostVarianceUpsertBulk) AddVariancePct(v float64) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.AddVariancePct(v)
	})
}

// UpdateVariancePct sets the "variance_pct" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateVariancePct() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateVariancePct()
	})
}

// SetBreakdown sets the "breakdown" field.
func (u *FoodCostVarianceUpsertBulk) SetBreakdown(v map[string]interface{}) *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.SetBreakdown(v)
	})
}

// UpdateBreakdown sets the "breakdown" field to the value that was provided on create.
func (u *FoodCostVarianceUpsertBulk) UpdateBreakdown() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.UpdateBreakdown()
	})
}

// ClearBreakdown clears the value of the "breakdown" field.
func (u *FoodCostVarianceUpsertBulk) ClearBreakdown() *FoodCostVarianceUpsertBulk {
	return u.Update(func(s *FoodCostVarianceUpsert) {
		s.ClearBreakdown()
	})
}

// Exec executes the query.
func (u *FoodCostVarianceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FoodCostVarianceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FoodCostVarianceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FoodCostVarianceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
