// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/inventory-service/internal/ent/inventorypermission"
	"github.com/google/uuid"
)

// InventoryPermission is the model entity for the InventoryPermission schema.
type InventoryPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Permission code: inventory.items.add, inventory.stock.view, etc.
	PermissionCode string `json:"permission_code,omitempty"`
	// Display name
	Name string `json:"name,omitempty"`
	// Module: items, variants, categories, warehouses, stock, recipes, consumptions, reservations, units, config, users
	Module string `json:"module,omitempty"`
	// Action: add, view, view_own, change, change_own, delete, delete_own, manage, manage_own
	Action string `json:"action,omitempty"`
	// Resource: items, warehouses, etc.
	Resource string `json:"resource,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InventoryPermissionQuery when eager-loading is set.
	Edges        InventoryPermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InventoryPermissionEdges holds the relations/edges for other nodes in the graph.
type InventoryPermissionEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*InventoryRole `json:"roles,omitempty"`
	// RolePermissions holds the value of the role_permissions edge.
	RolePermissions []*RolePermission `json:"role_permissions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e InventoryPermissionEdges) RolesOrErr() ([]*InventoryRole, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// RolePermissionsOrErr returns the RolePermissions value or an error if the edge
// was not loaded in eager-loading.
func (e InventoryPermissionEdges) RolePermissionsOrErr() ([]*RolePermission, error) {
	if e.loadedTypes[1] {
		return e.RolePermissions, nil
	}
	return nil, &NotLoadedError{edge: "role_permissions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InventoryPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case inventorypermission.FieldPermissionCode, inventorypermission.FieldName, inventorypermission.FieldModule, inventorypermission.FieldAction, inventorypermission.FieldResource, inventorypermission.FieldDescription:
			values[i] = new(sql.NullString)
		case inventorypermission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case inventorypermission.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InventoryPermission fields.
func (_m *InventoryPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case inventorypermission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case inventorypermission.FieldPermissionCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission_code", values[i])
			} else if value.Valid {
				_m.PermissionCode = value.String
			}
		case inventorypermission.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case inventorypermission.FieldModule:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module", values[i])
			} else if value.Valid {
				_m.Module = value.String
			}
		case inventorypermission.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case inventorypermission.FieldResource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resource", values[i])
			} else if value.Valid {
				_m.Resource = value.String
			}
		case inventorypermission.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case inventorypermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InventoryPermission.
// This includes values selected through modifiers, order, etc.
func (_m *InventoryPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the InventoryPermission entity.
func (_m *InventoryPermission) QueryRoles() *InventoryRoleQuery {
	return NewInventoryPermissionClient(_m.config).QueryRoles(_m)
}

// QueryRolePermissions queries the "role_permissions" edge of the InventoryPermission entity.
func (_m *InventoryPermission) QueryRolePermissions() *RolePermissionQuery {
	return NewInventoryPermissionClient(_m.config).QueryRolePermissions(_m)
}

// Update returns a builder for updating this InventoryPermission.
// Note that you need to call InventoryPermission.Unwrap() before calling this method if this InventoryPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InventoryPermission) Update() *InventoryPermissionUpdateOne {
	return NewInventoryPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InventoryPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InventoryPermission) Unwrap() *InventoryPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InventoryPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InventoryPermission) String() string {
	var builder strings.Builder
	builder.WriteString("InventoryPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("permission_code=")
	builder.WriteString(_m.PermissionCode)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("module=")
	builder.WriteString(_m.Module)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("resource=")
	builder.WriteString(_m.Resource)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// InventoryPermissions is a parsable slice of InventoryPermission.
type InventoryPermissions []*InventoryPermission
