// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/inventorybalance"
	"github.com/bengobox/inventory-service/internal/ent/item"
	"github.com/bengobox/inventory-service/internal/ent/warehouse"
	"github.com/google/uuid"
)

// InventoryBalanceCreate is the builder for creating a InventoryBalance entity.
type InventoryBalanceCreate struct {
	config
	mutation *InventoryBalanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *InventoryBalanceCreate) SetTenantID(v uuid.UUID) *InventoryBalanceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *InventoryBalanceCreate) SetItemID(v uuid.UUID) *InventoryBalanceCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetWarehouseID sets the "warehouse_id" field.
func (_c *InventoryBalanceCreate) SetWarehouseID(v uuid.UUID) *InventoryBalanceCreate {
	_c.mutation.SetWarehouseID(v)
	return _c
}

// SetOnHand sets the "on_hand" field.
func (_c *InventoryBalanceCreate) SetOnHand(v int) *InventoryBalanceCreate {
	_c.mutation.SetOnHand(v)
	return _c
}

// SetNillableOnHand sets the "on_hand" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableOnHand(v *int) *InventoryBalanceCreate {
	if v != nil {
		_c.SetOnHand(*v)
	}
	return _c
}

// SetAvailable sets the "available" field.
func (_c *InventoryBalanceCreate) SetAvailable(v int) *InventoryBalanceCreate {
	_c.mutation.SetAvailable(v)
	return _c
}

// SetNillableAvailable sets the "available" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableAvailable(v *int) *InventoryBalanceCreate {
	if v != nil {
		_c.SetAvailable(*v)
	}
	return _c
}

// SetReserved sets the "reserved" field.
func (_c *InventoryBalanceCreate) SetReserved(v int) *InventoryBalanceCreate {
	_c.mutation.SetReserved(v)
	return _c
}

// SetNillableReserved sets the "reserved" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableReserved(v *int) *InventoryBalanceCreate {
	if v != nil {
		_c.SetReserved(*v)
	}
	return _c
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (_c *InventoryBalanceCreate) SetUnitOfMeasure(v string) *InventoryBalanceCreate {
	_c.mutation.SetUnitOfMeasure(v)
	return _c
}

// SetNillableUnitOfMeasure sets the "unit_of_measure" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableUnitOfMeasure(v *string) *InventoryBalanceCreate {
	if v != nil {
		_c.SetUnitOfMeasure(*v)
	}
	return _c
}

// SetReorderLevel sets the "reorder_level" field.
func (_c *InventoryBalanceCreate) SetReorderLevel(v int) *InventoryBalanceCreate {
	_c.mutation.SetReorderLevel(v)
	return _c
}

// SetNillableReorderLevel sets the "reorder_level" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableReorderLevel(v *int) *InventoryBalanceCreate {
	if v != nil {
		_c.SetReorderLevel(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InventoryBalanceCreate) SetUpdatedAt(v time.Time) *InventoryBalanceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableUpdatedAt(v *time.Time) *InventoryBalanceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InventoryBalanceCreate) SetID(v uuid.UUID) *InventoryBalanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InventoryBalanceCreate) SetNillableID(v *uuid.UUID) *InventoryBalanceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *InventoryBalanceCreate) SetItem(v *Item) *InventoryBalanceCreate {
	return _c.SetItemID(v.ID)
}

// SetWarehouse sets the "warehouse" edge to the Warehouse entity.
func (_c *InventoryBalanceCreate) SetWarehouse(v *Warehouse) *InventoryBalanceCreate {
	return _c.SetWarehouseID(v.ID)
}

// Mutation returns the InventoryBalanceMutation object of the builder.
func (_c *InventoryBalanceCreate) Mutation() *InventoryBalanceMutation {
	return _c.mutation
}

// Save creates the InventoryBalance in the database.
func (_c *InventoryBalanceCreate) Save(ctx context.Context) (*InventoryBalance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryBalanceCreate) SaveX(ctx context.Context) *InventoryBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryBalanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryBalanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryBalanceCreate) defaults() {
	if _, ok := _c.mutation.OnHand(); !ok {
		v := inventorybalance.DefaultOnHand
		_c.mutation.SetOnHand(v)
	}
	if _, ok := _c.mutation.Available(); !ok {
		v := inventorybalance.DefaultAvailable
		_c.mutation.SetAvailable(v)
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		v := inventorybalance.DefaultReserved
		_c.mutation.SetReserved(v)
	}
	if _, ok := _c.mutation.UnitOfMeasure(); !ok {
		v := inventorybalance.DefaultUnitOfMeasure
		_c.mutation.SetUnitOfMeasure(v)
	}
	if _, ok := _c.mutation.ReorderLevel(); !ok {
		v := inventorybalance.DefaultReorderLevel
		_c.mutation.SetReorderLevel(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := inventorybalance.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := inventorybalance.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryBalanceCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "InventoryBalance.tenant_id"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "InventoryBalance.item_id"`)}
	}
	if _, ok := _c.mutation.WarehouseID(); !ok {
		return &ValidationError{Name: "warehouse_id", err: errors.New(`ent: missing required field "InventoryBalance.warehouse_id"`)}
	}
	if _, ok := _c.mutation.OnHand(); !ok {
		return &ValidationError{Name: "on_hand", err: errors.New(`ent: missing required field "InventoryBalance.on_hand"`)}
	}
	if _, ok := _c.mutation.Available(); !ok {
		return &ValidationError{Name: "available", err: errors.New(`ent: missing required field "InventoryBalance.available"`)}
	}
	if _, ok := _c.mutation.Reserved(); !ok {
		return &ValidationError{Name: "reserved", err: errors.New(`ent: missing required field "InventoryBalance.reserved"`)}
	}
	if _, ok := _c.mutation.UnitOfMeasure(); !ok {
		return &ValidationError{Name: "unit_of_measure", err: errors.New(`ent: missing required field "InventoryBalance.unit_of_measure"`)}
	}
	if _, ok := _c.mutation.ReorderLevel(); !ok {
		return &ValidationError{Name: "reorder_level", err: errors.New(`ent: missing required field "InventoryBalance.reorder_level"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "InventoryBalance.updated_at"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "InventoryBalance.item"`)}
	}
	if len(_c.mutation.WarehouseIDs()) == 0 {
		return &ValidationError{Name: "warehouse", err: errors.New(`ent: missing required edge "InventoryBalance.warehouse"`)}
	}
	return nil
}

func (_c *InventoryBalanceCreate) sqlSave(ctx context.Context) (*InventoryBalance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryBalanceCreate) createSpec() (*InventoryBalance, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryBalance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventorybalance.Table, sqlgraph.NewFieldSpec(inventorybalance.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(inventorybalance.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OnHand(); ok {
		_spec.SetField(inventorybalance.FieldOnHand, field.TypeInt, value)
		_node.OnHand = value
	}
	if value, ok := _c.mutation.Available(); ok {
		_spec.SetField(inventorybalance.FieldAvailable, field.TypeInt, value)
		_node.Available = value
	}
	if value, ok := _c.mutation.Reserved(); ok {
		_spec.SetField(inventorybalance.FieldReserved, field.TypeInt, value)
		_node.Reserved = value
	}
	if value, ok := _c.mutation.UnitOfMeasure(); ok {
		_spec.SetField(inventorybalance.FieldUnitOfMeasure, field.TypeString, value)
		_node.UnitOfMeasure = value
	}
	if value, ok := _c.mutation.ReorderLevel(); ok {
		_spec.SetField(inventorybalance.FieldReorderLevel, field.TypeInt, value)
		_node.ReorderLevel = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(inventorybalance.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventorybalance.ItemTable,
			Columns: []string{inventorybalance.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ItemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WarehouseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventorybalance.WarehouseTable,
			Columns: []string{inventorybalance.WarehouseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warehouse.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WarehouseID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryBalance.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryBalanceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryBalanceCreate) OnConflict(opts ...sql.ConflictOption) *InventoryBalanceUpsertOne {
	_c.conflict = opts
	return &InventoryBalanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryBalanceCreate) OnConflictColumns(columns ...string) *InventoryBalanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryBalanceUpsertOne{
		create: _c,
	}
}

type (
	// InventoryBalanceUpsertOne is the builder for "upsert"-ing
	//  one InventoryBalance node.
	InventoryBalanceUpsertOne struct {
		create *InventoryBalanceCreate
	}

	// InventoryBalanceUpsert is the "OnConflict" setter.
	InventoryBalanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *InventoryBalanceUpsert) SetTenantID(v uuid.UUID) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateTenantID() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldTenantID)
	return u
}

// SetItemID sets the "item_id" field.
func (u *InventoryBalanceUpsert) SetItemID(v uuid.UUID) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateItemID() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldItemID)
	return u
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *InventoryBalanceUpsert) SetWarehouseID(v uuid.UUID) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldWarehouseID, v)
	return u
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateWarehouseID() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldWarehouseID)
	return u
}

// SetOnHand sets the "on_hand" field.
func (u *InventoryBalanceUpsert) SetOnHand(v int) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldOnHand, v)
	return u
}

// UpdateOnHand sets the "on_hand" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateOnHand() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldOnHand)
	return u
}

// AddOnHand adds v to the "on_hand" field.
func (u *InventoryBalanceUpsert) AddOnHand(v int) *InventoryBalanceUpsert {
	u.Add(inventorybalance.FieldOnHand, v)
	return u
}

// SetAvailable sets the "available" field.
func (u *InventoryBalanceUpsert) SetAvailable(v int) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldAvailable, v)
	return u
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateAvailable() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldAvailable)
	return u
}

// AddAvailable adds v to the "available" field.
func (u *InventoryBalanceUpsert) AddAvailable(v int) *InventoryBalanceUpsert {
	u.Add(inventorybalance.FieldAvailable, v)
	return u
}

// SetReserved sets the "reserved" field.
func (u *InventoryBalanceUpsert) SetReserved(v int) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldReserved, v)
	return u
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateReserved() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldReserved)
	return u
}

// AddReserved adds v to the "reserved" field.
func (u *InventoryBalanceUpsert) AddReserved(v int) *InventoryBalanceUpsert {
	u.Add(inventorybalance.FieldReserved, v)
	return u
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (u *InventoryBalanceUpsert) SetUnitOfMeasure(v string) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldUnitOfMeasure, v)
	return u
}

// UpdateUnitOfMeasure sets the "unit_of_measure" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateUnitOfMeasure() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldUnitOfMeasure)
	return u
}

// SetReorderLevel sets the "reorder_level" field.
func (u *InventoryBalanceUpsert) SetReorderLevel(v int) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldReorderLevel, v)
	return u
}

// UpdateReorderLevel sets the "reorder_level" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateReorderLevel() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldReorderLevel)
	return u
}

// AddReorderLevel adds v to the "reorder_level" field.
func (u *InventoryBalanceUpsert) AddReorderLevel(v int) *InventoryBalanceUpsert {
	u.Add(inventorybalance.FieldReorderLevel, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryBalanceUpsert) SetUpdatedAt(v time.Time) *InventoryBalanceUpsert {
	u.Set(inventorybalance.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryBalanceUpsert) UpdateUpdatedAt() *InventoryBalanceUpsert {
	u.SetExcluded(inventorybalance.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventorybalance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryBalanceUpsertOne) UpdateNewValues() *InventoryBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inventorybalance.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventoryBalanceUpsertOne) Ignore() *InventoryBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryBalanceUpsertOne) DoNothing() *InventoryBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryBalanceCreate.OnConflict
// documentation for more info.
func (u *InventoryBalanceUpsertOne) Update(set func(*InventoryBalanceUpsert)) *InventoryBalanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InventoryBalanceUpsertOne) SetTenantID(v uuid.UUID) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateTenantID() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateTenantID()
	})
}

// SetItemID sets the "item_id" field.
func (u *InventoryBalanceUpsertOne) SetItemID(v uuid.UUID) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateItemID() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateItemID()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *InventoryBalanceUpsertOne) SetWarehouseID(v uuid.UUID) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateWarehouseID() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateWarehouseID()
	})
}

// SetOnHand sets the "on_hand" field.
func (u *InventoryBalanceUpsertOne) SetOnHand(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetOnHand(v)
	})
}

// AddOnHand adds v to the "on_hand" field.
func (u *InventoryBalanceUpsertOne) AddOnHand(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddOnHand(v)
	})
}

// UpdateOnHand sets the "on_hand" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateOnHand() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateOnHand()
	})
}

// SetAvailable sets the "available" field.
func (u *InventoryBalanceUpsertOne) SetAvailable(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *InventoryBalanceUpsertOne) AddAvailable(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateAvailable() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateAvailable()
	})
}

// SetReserved sets the "reserved" field.
func (u *InventoryBalanceUpsertOne) SetReserved(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetReserved(v)
	})
}

// AddReserved adds v to the "reserved" field.
func (u *InventoryBalanceUpsertOne) AddReserved(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddReserved(v)
	})
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateReserved() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateReserved()
	})
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (u *InventoryBalanceUpsertOne) SetUnitOfMeasure(v string) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetUnitOfMeasure(v)
	})
}

// UpdateUnitOfMeasure sets the "unit_of_measure" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateUnitOfMeasure() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateUnitOfMeasure()
	})
}

// SetReorderLevel sets the "reorder_level" field.
func (u *InventoryBalanceUpsertOne) SetReorderLevel(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetReorderLevel(v)
	})
}

// AddReorderLevel adds v to the "reorder_level" field.
func (u *InventoryBalanceUpsertOne) AddReorderLevel(v int) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddReorderLevel(v)
	})
}

// UpdateReorderLevel sets the "reorder_level" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateReorderLevel() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateReorderLevel()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryBalanceUpsertOne) SetUpdatedAt(v time.Time) *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryBalanceUpsertOne) UpdateUpdatedAt() *InventoryBalanceUpsertOne {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InventoryBalanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryBalanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryBalanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventoryBalanceUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InventoryBalanceUpsertOne.ID is not supported by MySQL driver. Use InventoryBalanceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventoryBalanceUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventoryBalanceCreateBulk is the builder for creating many InventoryBalance entities in bulk.
type InventoryBalanceCreateBulk struct {
	config
	err      error
	builders []*InventoryBalanceCreate
	conflict []sql.ConflictOption
}

// Save creates the InventoryBalance entities in the database.
func (_c *InventoryBalanceCreateBulk) Save(ctx context.Context) ([]*InventoryBalance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InventoryBalance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryBalanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryBalanceCreateBulk) SaveX(ctx context.Context) []*InventoryBalance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryBalanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryBalanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryBalance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryBalanceUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryBalanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventoryBalanceUpsertBulk {
	_c.conflict = opts
	return &InventoryBalanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryBalanceCreateBulk) OnConflictColumns(columns ...string) *InventoryBalanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryBalanceUpsertBulk{
		create: _c,
	}
}

// InventoryBalanceUpsertBulk is the builder for "upsert"-ing
// a bulk of InventoryBalance nodes.
type InventoryBalanceUpsertBulk struct {
	create *InventoryBalanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventorybalance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventoryBalanceUpsertBulk) UpdateNewValues() *InventoryBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inventorybalance.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryBalance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventoryBalanceUpsertBulk) Ignore() *InventoryBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryBalanceUpsertBulk) DoNothing() *InventoryBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryBalanceCreateBulk.OnConflict
// documentation for more info.
func (u *InventoryBalanceUpsertBulk) Update(set func(*InventoryBalanceUpsert)) *InventoryBalanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryBalanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InventoryBalanceUpsertBulk) SetTenantID(v uuid.UUID) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateTenantID() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateTenantID()
	})
}

// SetItemID sets the "item_id" field.
func (u *InventoryBalanceUpsertBulk) SetItemID(v uuid.UUID) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateItemID() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateItemID()
	})
}

// SetWarehouseID sets the "warehouse_id" field.
func (u *InventoryBalanceUpsertBulk) SetWarehouseID(v uuid.UUID) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetWarehouseID(v)
	})
}

// UpdateWarehouseID sets the "warehouse_id" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateWarehouseID() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateWarehouseID()
	})
}

// SetOnHand sets the "on_hand" field.
func (u *InventoryBalanceUpsertBulk) SetOnHand(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetOnHand(v)
	})
}

// AddOnHand adds v to the "on_hand" field.
func (u *InventoryBalanceUpsertBulk) AddOnHand(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddOnHand(v)
	})
}

// UpdateOnHand sets the "on_hand" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateOnHand() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateOnHand()
	})
}

// SetAvailable sets the "available" field.
func (u *InventoryBalanceUpsertBulk) SetAvailable(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetAvailable(v)
	})
}

// AddAvailable adds v to the "available" field.
func (u *InventoryBalanceUpsertBulk) AddAvailable(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddAvailable(v)
	})
}

// UpdateAvailable sets the "available" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateAvailable() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateAvailable()
	})
}

// SetReserved sets the "reserved" field.
func (u *InventoryBalanceUpsertBulk) SetReserved(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetReserved(v)
	})
}

// AddReserved adds v to the "reserved" field.
func (u *InventoryBalanceUpsertBulk) AddReserved(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddReserved(v)
	})
}

// UpdateReserved sets the "reserved" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateReserved() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateReserved()
	})
}

// SetUnitOfMeasure sets the "unit_of_measure" field.
func (u *InventoryBalanceUpsertBulk) SetUnitOfMeasure(v string) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetUnitOfMeasure(v)
	})
}

// UpdateUnitOfMeasure sets the "unit_of_measure" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateUnitOfMeasure() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateUnitOfMeasure()
	})
}

// SetReorderLevel sets the "reorder_level" field.
func (u *InventoryBalanceUpsertBulk) SetReorderLevel(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetReorderLevel(v)
	})
}

// AddReorderLevel adds v to the "reorder_level" field.
func (u *InventoryBalanceUpsertBulk) AddReorderLevel(v int) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.AddReorderLevel(v)
	})
}

// UpdateReorderLevel sets the "reorder_level" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateReorderLevel() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateReorderLevel()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InventoryBalanceUpsertBulk) SetUpdatedAt(v time.Time) *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InventoryBalanceUpsertBulk) UpdateUpdatedAt() *InventoryBalanceUpsertBulk {
	return u.Update(func(s *InventoryBalanceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *InventoryBalanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventoryBalanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryBalanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryBalanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
