// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/item"
	"github.com/bengobox/inventory-service/internal/ent/itembrand"
	"github.com/google/uuid"
)

// ItemBrandCreate is the builder for creating a ItemBrand entity.
type ItemBrandCreate struct {
	config
	mutation *ItemBrandMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *ItemBrandCreate) SetTenantID(v uuid.UUID) *ItemBrandCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ItemBrandCreate) SetName(v string) *ItemBrandCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ItemBrandCreate) SetCode(v string) *ItemBrandCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ItemBrandCreate) SetDescription(v string) *ItemBrandCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableDescription(v *string) *ItemBrandCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *ItemBrandCreate) SetLogoURL(v string) *ItemBrandCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableLogoURL(v *string) *ItemBrandCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *ItemBrandCreate) SetSortOrder(v int) *ItemBrandCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableSortOrder(v *int) *ItemBrandCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ItemBrandCreate) SetIsActive(v bool) *ItemBrandCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableIsActive(v *bool) *ItemBrandCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemBrandCreate) SetCreatedAt(v time.Time) *ItemBrandCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableCreatedAt(v *time.Time) *ItemBrandCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemBrandCreate) SetUpdatedAt(v time.Time) *ItemBrandCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableUpdatedAt(v *time.Time) *ItemBrandCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemBrandCreate) SetID(v uuid.UUID) *ItemBrandCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItemBrandCreate) SetNillableID(v *uuid.UUID) *ItemBrandCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddItemIDs adds the "items" edge to the Item entity by IDs.
func (_c *ItemBrandCreate) AddItemIDs(ids ...uuid.UUID) *ItemBrandCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the Item entity.
func (_c *ItemBrandCreate) AddItems(v ...*Item) *ItemBrandCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// Mutation returns the ItemBrandMutation object of the builder.
func (_c *ItemBrandCreate) Mutation() *ItemBrandMutation {
	return _c.mutation
}

// Save creates the ItemBrand in the database.
func (_c *ItemBrandCreate) Save(ctx context.Context) (*ItemBrand, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemBrandCreate) SaveX(ctx context.Context) *ItemBrand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemBrandCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemBrandCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemBrandCreate) defaults() {
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := itembrand.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := itembrand.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itembrand.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itembrand.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := itembrand.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemBrandCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ItemBrand.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ItemBrand.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := itembrand.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ItemBrand.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "ItemBrand.code"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "ItemBrand.sort_order"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ItemBrand.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemBrand.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemBrand.updated_at"`)}
	}
	return nil
}

func (_c *ItemBrandCreate) sqlSave(ctx context.Context) (*ItemBrand, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemBrandCreate) createSpec() (*ItemBrand, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemBrand{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itembrand.Table, sqlgraph.NewFieldSpec(itembrand.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(itembrand.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(itembrand.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(itembrand.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(itembrand.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(itembrand.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(itembrand.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(itembrand.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itembrand.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itembrand.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   itembrand.ItemsTable,
			Columns: []string{itembrand.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemBrand.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemBrandUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemBrandCreate) OnConflict(opts ...sql.ConflictOption) *ItemBrandUpsertOne {
	_c.conflict = opts
	return &ItemBrandUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemBrandCreate) OnConflictColumns(columns ...string) *ItemBrandUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemBrandUpsertOne{
		create: _c,
	}
}

type (
	// ItemBrandUpsertOne is the builder for "upsert"-ing
	//  one ItemBrand node.
	ItemBrandUpsertOne struct {
		create *ItemBrandCreate
	}

	// ItemBrandUpsert is the "OnConflict" setter.
	ItemBrandUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *ItemBrandUpsert) SetTenantID(v uuid.UUID) *ItemBrandUpsert {
	u.Set(itembrand.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateTenantID() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldTenantID)
	return u
}

// SetName sets the "name" field.
func (u *ItemBrandUpsert) SetName(v string) *ItemBrandUpsert {
	u.Set(itembrand.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateName() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldName)
	return u
}

// SetCode sets the "code" field.
func (u *ItemBrandUpsert) SetCode(v string) *ItemBrandUpsert {
	u.Set(itembrand.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateCode() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldCode)
	return u
}

// SetDescription sets the "description" field.
func (u *ItemBrandUpsert) SetDescription(v string) *ItemBrandUpsert {
	u.Set(itembrand.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateDescription() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ItemBrandUpsert) ClearDescription() *ItemBrandUpsert {
	u.SetNull(itembrand.FieldDescription)
	return u
}

// SetLogoURL sets the "logo_url" field.
func (u *ItemBrandUpsert) SetLogoURL(v string) *ItemBrandUpsert {
	u.Set(itembrand.FieldLogoURL, v)
	return u
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateLogoURL() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldLogoURL)
	return u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ItemBrandUpsert) ClearLogoURL() *ItemBrandUpsert {
	u.SetNull(itembrand.FieldLogoURL)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *ItemBrandUpsert) SetSortOrder(v int) *ItemBrandUpsert {
	u.Set(itembrand.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateSortOrder() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ItemBrandUpsert) AddSortOrder(v int) *ItemBrandUpsert {
	u.Add(itembrand.FieldSortOrder, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *ItemBrandUpsert) SetIsActive(v bool) *ItemBrandUpsert {
	u.Set(itembrand.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateIsActive() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldIsActive)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemBrandUpsert) SetUpdatedAt(v time.Time) *ItemBrandUpsert {
	u.Set(itembrand.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemBrandUpsert) UpdateUpdatedAt() *ItemBrandUpsert {
	u.SetExcluded(itembrand.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itembrand.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemBrandUpsertOne) UpdateNewValues() *ItemBrandUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(itembrand.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(itembrand.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemBrandUpsertOne) Ignore() *ItemBrandUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemBrandUpsertOne) DoNothing() *ItemBrandUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemBrandCreate.OnConflict
// documentation for more info.
func (u *ItemBrandUpsertOne) Update(set func(*ItemBrandUpsert)) *ItemBrandUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemBrandUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *ItemBrandUpsertOne) SetTenantID(v uuid.UUID) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateTenantID() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *ItemBrandUpsertOne) SetName(v string) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateName() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *ItemBrandUpsertOne) SetCode(v string) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateCode() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateCode()
	})
}

// SetDescription sets the "description" field.
func (u *ItemBrandUpsertOne) SetDescription(v string) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateDescription() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ItemBrandUpsertOne) ClearDescription() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.ClearDescription()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *ItemBrandUpsertOne) SetLogoURL(v string) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateLogoURL() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ItemBrandUpsertOne) ClearLogoURL() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.ClearLogoURL()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ItemBrandUpsertOne) SetSortOrder(v int) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ItemBrandUpsertOne) AddSortOrder(v int) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateSortOrder() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ItemBrandUpsertOne) SetIsActive(v bool) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateIsActive() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemBrandUpsertOne) SetUpdatedAt(v time.Time) *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemBrandUpsertOne) UpdateUpdatedAt() *ItemBrandUpsertOne {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ItemBrandUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemBrandCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemBrandUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemBrandUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ItemBrandUpsertOne.ID is not supported by MySQL driver. Use ItemBrandUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemBrandUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemBrandCreateBulk is the builder for creating many ItemBrand entities in bulk.
type ItemBrandCreateBulk struct {
	config
	err      error
	builders []*ItemBrandCreate
	conflict []sql.ConflictOption
}

// Save creates the ItemBrand entities in the database.
func (_c *ItemBrandCreateBulk) Save(ctx context.Context) ([]*ItemBrand, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemBrand, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemBrandMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemBrandCreateBulk) SaveX(ctx context.Context) []*ItemBrand {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemBrandCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemBrandCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ItemBrand.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemBrandUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemBrandCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemBrandUpsertBulk {
	_c.conflict = opts
	return &ItemBrandUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemBrandCreateBulk) OnConflictColumns(columns ...string) *ItemBrandUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemBrandUpsertBulk{
		create: _c,
	}
}

// ItemBrandUpsertBulk is the builder for "upsert"-ing
// a bulk of ItemBrand nodes.
type ItemBrandUpsertBulk struct {
	create *ItemBrandCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(itembrand.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ItemBrandUpsertBulk) UpdateNewValues() *ItemBrandUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(itembrand.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(itembrand.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ItemBrand.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemBrandUpsertBulk) Ignore() *ItemBrandUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemBrandUpsertBulk) DoNothing() *ItemBrandUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemBrandCreateBulk.OnConflict
// documentation for more info.
func (u *ItemBrandUpsertBulk) Update(set func(*ItemBrandUpsert)) *ItemBrandUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemBrandUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *ItemBrandUpsertBulk) SetTenantID(v uuid.UUID) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateTenantID() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *ItemBrandUpsertBulk) SetName(v string) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateName() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateName()
	})
}

// SetCode sets the "code" field.
func (u *ItemBrandUpsertBulk) SetCode(v string) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateCode() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateCode()
	})
}

// SetDescription sets the "description" field.
func (u *ItemBrandUpsertBulk) SetDescription(v string) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateDescription() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ItemBrandUpsertBulk) ClearDescription() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.ClearDescription()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *ItemBrandUpsertBulk) SetLogoURL(v string) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateLogoURL() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *ItemBrandUpsertBulk) ClearLogoURL() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.ClearLogoURL()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *ItemBrandUpsertBulk) SetSortOrder(v int) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *ItemBrandUpsertBulk) AddSortOrder(v int) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateSortOrder() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsActive sets the "is_active" field.
func (u *ItemBrandUpsertBulk) SetIsActive(v bool) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateIsActive() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateIsActive()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ItemBrandUpsertBulk) SetUpdatedAt(v time.Time) *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ItemBrandUpsertBulk) UpdateUpdatedAt() *ItemBrandUpsertBulk {
	return u.Update(func(s *ItemBrandUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ItemBrandUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemBrandCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemBrandCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemBrandUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
