// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/itempricing"
	"github.com/google/uuid"
)

// ItemPricingCreate is the builder for creating a ItemPricing entity.
type ItemPricingCreate struct {
	config
	mutation *ItemPricingMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *ItemPricingCreate) SetTenantID(v uuid.UUID) *ItemPricingCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *ItemPricingCreate) SetItemID(v uuid.UUID) *ItemPricingCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetPricingTierID sets the "pricing_tier_id" field.
func (_c *ItemPricingCreate) SetPricingTierID(v uuid.UUID) *ItemPricingCreate {
	_c.mutation.SetPricingTierID(v)
	return _c
}

// SetOutletID sets the "outlet_id" field.
func (_c *ItemPricingCreate) SetOutletID(v uuid.UUID) *ItemPricingCreate {
	_c.mutation.SetOutletID(v)
	return _c
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableOutletID(v *uuid.UUID) *ItemPricingCreate {
	if v != nil {
		_c.SetOutletID(*v)
	}
	return _c
}

// SetTierBasis sets the "tier_basis" field.
func (_c *ItemPricingCreate) SetTierBasis(v itempricing.TierBasis) *ItemPricingCreate {
	_c.mutation.SetTierBasis(v)
	return _c
}

// SetNillableTierBasis sets the "tier_basis" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableTierBasis(v *itempricing.TierBasis) *ItemPricingCreate {
	if v != nil {
		_c.SetTierBasis(*v)
	}
	return _c
}

// SetPrice sets the "price" field.
func (_c *ItemPricingCreate) SetPrice(v float64) *ItemPricingCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillablePrice(v *float64) *ItemPricingCreate {
	if v != nil {
		_c.SetPrice(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *ItemPricingCreate) SetCurrency(v string) *ItemPricingCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableCurrency(v *string) *ItemPricingCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetEffectiveFrom sets the "effective_from" field.
func (_c *ItemPricingCreate) SetEffectiveFrom(v time.Time) *ItemPricingCreate {
	_c.mutation.SetEffectiveFrom(v)
	return _c
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableEffectiveFrom(v *time.Time) *ItemPricingCreate {
	if v != nil {
		_c.SetEffectiveFrom(*v)
	}
	return _c
}

// SetEffectiveTo sets the "effective_to" field.
func (_c *ItemPricingCreate) SetEffectiveTo(v time.Time) *ItemPricingCreate {
	_c.mutation.SetEffectiveTo(v)
	return _c
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableEffectiveTo(v *time.Time) *ItemPricingCreate {
	if v != nil {
		_c.SetEffectiveTo(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ItemPricingCreate) SetIsActive(v bool) *ItemPricingCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableIsActive(v *bool) *ItemPricingCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemPricingCreate) SetCreatedAt(v time.Time) *ItemPricingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableCreatedAt(v *time.Time) *ItemPricingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemPricingCreate) SetUpdatedAt(v time.Time) *ItemPricingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableUpdatedAt(v *time.Time) *ItemPricingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemPricingCreate) SetID(v uuid.UUID) *ItemPricingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItemPricingCreate) SetNillableID(v *uuid.UUID) *ItemPricingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ItemPricingMutation object of the builder.
func (_c *ItemPricingCreate) Mutation() *ItemPricingMutation {
	return _c.mutation
}

// Save creates the ItemPricing in the database.
func (_c *ItemPricingCreate) Save(ctx context.Context) (*ItemPricing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemPricingCreate) SaveX(ctx context.Context) *ItemPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemPricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemPricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemPricingCreate) defaults() {
	if _, ok := _c.mutation.TierBasis(); !ok {
		v := itempricing.DefaultTierBasis
		_c.mutation.SetTierBasis(v)
	}
	if _, ok := _c.mutation.Price(); !ok {
		v := itempricing.DefaultPrice
		_c.mutation.SetPrice(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := itempricing.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		v := itempricing.DefaultEffectiveFrom()
		_c.mutation.SetEffectiveFrom(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := itempricing.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := itempricing.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := itempricing.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := itempricing.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemPricingCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ItemPricing.tenant_id"`)}
	}
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "ItemPricing.item_id"`)}
	}
	if _, ok := _c.mutation.PricingTierID(); !ok {
		return &ValidationError{Name: "pricing_tier_id", err: errors.New(`ent: missing required field "ItemPricing.pricing_tier_id"`)}
	}
	if _, ok := _c.mutation.TierBasis(); !ok {
		return &ValidationError{Name: "tier_basis", err: errors.New(`ent: missing required field "ItemPricing.tier_basis"`)}
	}
	if v, ok := _c.mutation.TierBasis(); ok {
		if err := itempricing.TierBasisValidator(v); err != nil {
			return &ValidationError{Name: "tier_basis", err: fmt.Errorf(`ent: validator failed for field "ItemPricing.tier_basis": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "ItemPricing.price"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "ItemPricing.currency"`)}
	}
	if _, ok := _c.mutation.EffectiveFrom(); !ok {
		return &ValidationError{Name: "effective_from", err: errors.New(`ent: missing required field "ItemPricing.effective_from"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ItemPricing.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ItemPricing.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ItemPricing.updated_at"`)}
	}
	return nil
}

func (_c *ItemPricingCreate) sqlSave(ctx context.Context) (*ItemPricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemPricingCreate) createSpec() (*ItemPricing, *sqlgraph.CreateSpec) {
	var (
		_node = &ItemPricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(itempricing.Table, sqlgraph.NewFieldSpec(itempricing.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(itempricing.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(itempricing.FieldItemID, field.TypeUUID, value)
		_node.ItemID = value
	}
	if value, ok := _c.mutation.PricingTierID(); ok {
		_spec.SetField(itempricing.FieldPricingTierID, field.TypeUUID, value)
		_node.PricingTierID = value
	}
	if value, ok := _c.mutation.OutletID(); ok {
		_spec.SetField(itempricing.FieldOutletID, field.TypeUUID, value)
		_node.OutletID = &value
	}
	if value, ok := _c.mutation.TierBasis(); ok {
		_spec.SetField(itempricing.FieldTierBasis, field.TypeEnum, value)
		_node.TierBasis = value
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(itempricing.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(itempricing.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.EffectiveFrom(); ok {
		_spec.SetField(itempricing.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = value
	}
	if value, ok := _c.mutation.EffectiveTo(); ok {
		_spec.SetField(itempricing.FieldEffectiveTo, field.TypeTime, value)
		_node.EffectiveTo = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(itempricing.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(itempricing.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(itempricing.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ItemPricingCreateBulk is the builder for creating many ItemPricing entities in bulk.
type ItemPricingCreateBulk struct {
	config
	err      error
	builders []*ItemPricingCreate
}

// Save creates the ItemPricing entities in the database.
func (_c *ItemPricingCreateBulk) Save(ctx context.Context) ([]*ItemPricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ItemPricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemPricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemPricingCreateBulk) SaveX(ctx context.Context) []*ItemPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemPricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemPricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
