// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/bundle"
	"github.com/bengobox/inventory-service/internal/ent/bundlecomponent"
	"github.com/bengobox/inventory-service/internal/ent/customfieldvalue"
	"github.com/bengobox/inventory-service/internal/ent/inventorybalance"
	"github.com/bengobox/inventory-service/internal/ent/inventorylot"
	"github.com/bengobox/inventory-service/internal/ent/item"
	"github.com/bengobox/inventory-service/internal/ent/itemasset"
	"github.com/bengobox/inventory-service/internal/ent/itembrand"
	"github.com/bengobox/inventory-service/internal/ent/itemcategory"
	"github.com/bengobox/inventory-service/internal/ent/itemtranslation"
	"github.com/bengobox/inventory-service/internal/ent/itemvariant"
	"github.com/bengobox/inventory-service/internal/ent/modifiergroup"
	"github.com/bengobox/inventory-service/internal/ent/recipe"
	"github.com/bengobox/inventory-service/internal/ent/recipeingredient"
	"github.com/bengobox/inventory-service/internal/ent/tenant"
	"github.com/bengobox/inventory-service/internal/ent/unit"
	"github.com/bengobox/inventory-service/internal/ent/warranty"
	"github.com/google/uuid"
)

// ItemCreate is the builder for creating a Item entity.
type ItemCreate struct {
	config
	mutation *ItemMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *ItemCreate) SetTenantID(v uuid.UUID) *ItemCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetSku sets the "sku" field.
func (_c *ItemCreate) SetSku(v string) *ItemCreate {
	_c.mutation.SetSku(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ItemCreate) SetName(v string) *ItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ItemCreate) SetDescription(v string) *ItemCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ItemCreate) SetNillableDescription(v *string) *ItemCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategoryID sets the "category_id" field.
func (_c *ItemCreate) SetCategoryID(v uuid.UUID) *ItemCreate {
	_c.mutation.SetCategoryID(v)
	return _c
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCategoryID(v *uuid.UUID) *ItemCreate {
	if v != nil {
		_c.SetCategoryID(*v)
	}
	return _c
}

// SetBrandID sets the "brand_id" field.
func (_c *ItemCreate) SetBrandID(v uuid.UUID) *ItemCreate {
	_c.mutation.SetBrandID(v)
	return _c
}

// SetNillableBrandID sets the "brand_id" field if the given value is not nil.
func (_c *ItemCreate) SetNillableBrandID(v *uuid.UUID) *ItemCreate {
	if v != nil {
		_c.SetBrandID(*v)
	}
	return _c
}

// SetManufacturer sets the "manufacturer" field.
func (_c *ItemCreate) SetManufacturer(v string) *ItemCreate {
	_c.mutation.SetManufacturer(v)
	return _c
}

// SetNillableManufacturer sets the "manufacturer" field if the given value is not nil.
func (_c *ItemCreate) SetNillableManufacturer(v *string) *ItemCreate {
	if v != nil {
		_c.SetManufacturer(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ItemCreate) SetModel(v string) *ItemCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ItemCreate) SetNillableModel(v *string) *ItemCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetGtin sets the "gtin" field.
func (_c *ItemCreate) SetGtin(v string) *ItemCreate {
	_c.mutation.SetGtin(v)
	return _c
}

// SetNillableGtin sets the "gtin" field if the given value is not nil.
func (_c *ItemCreate) SetNillableGtin(v *string) *ItemCreate {
	if v != nil {
		_c.SetGtin(*v)
	}
	return _c
}

// SetMpn sets the "mpn" field.
func (_c *ItemCreate) SetMpn(v string) *ItemCreate {
	_c.mutation.SetMpn(v)
	return _c
}

// SetNillableMpn sets the "mpn" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMpn(v *string) *ItemCreate {
	if v != nil {
		_c.SetMpn(*v)
	}
	return _c
}

// SetCondition sets the "condition" field.
func (_c *ItemCreate) SetCondition(v item.Condition) *ItemCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetNillableCondition sets the "condition" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCondition(v *item.Condition) *ItemCreate {
	if v != nil {
		_c.SetCondition(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *ItemCreate) SetSlug(v string) *ItemCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_c *ItemCreate) SetNillableSlug(v *string) *ItemCreate {
	if v != nil {
		_c.SetSlug(*v)
	}
	return _c
}

// SetShortDescription sets the "short_description" field.
func (_c *ItemCreate) SetShortDescription(v string) *ItemCreate {
	_c.mutation.SetShortDescription(v)
	return _c
}

// SetNillableShortDescription sets the "short_description" field if the given value is not nil.
func (_c *ItemCreate) SetNillableShortDescription(v *string) *ItemCreate {
	if v != nil {
		_c.SetShortDescription(*v)
	}
	return _c
}

// SetMetaTitle sets the "meta_title" field.
func (_c *ItemCreate) SetMetaTitle(v string) *ItemCreate {
	_c.mutation.SetMetaTitle(v)
	return _c
}

// SetNillableMetaTitle sets the "meta_title" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMetaTitle(v *string) *ItemCreate {
	if v != nil {
		_c.SetMetaTitle(*v)
	}
	return _c
}

// SetMetaDescription sets the "meta_description" field.
func (_c *ItemCreate) SetMetaDescription(v string) *ItemCreate {
	_c.mutation.SetMetaDescription(v)
	return _c
}

// SetNillableMetaDescription sets the "meta_description" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMetaDescription(v *string) *ItemCreate {
	if v != nil {
		_c.SetMetaDescription(*v)
	}
	return _c
}

// SetCountryOfOrigin sets the "country_of_origin" field.
func (_c *ItemCreate) SetCountryOfOrigin(v string) *ItemCreate {
	_c.mutation.SetCountryOfOrigin(v)
	return _c
}

// SetNillableCountryOfOrigin sets the "country_of_origin" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCountryOfOrigin(v *string) *ItemCreate {
	if v != nil {
		_c.SetCountryOfOrigin(*v)
	}
	return _c
}

// SetHsCode sets the "hs_code" field.
func (_c *ItemCreate) SetHsCode(v string) *ItemCreate {
	_c.mutation.SetHsCode(v)
	return _c
}

// SetNillableHsCode sets the "hs_code" field if the given value is not nil.
func (_c *ItemCreate) SetNillableHsCode(v *string) *ItemCreate {
	if v != nil {
		_c.SetHsCode(*v)
	}
	return _c
}

// SetIsReturnable sets the "is_returnable" field.
func (_c *ItemCreate) SetIsReturnable(v bool) *ItemCreate {
	_c.mutation.SetIsReturnable(v)
	return _c
}

// SetNillableIsReturnable sets the "is_returnable" field if the given value is not nil.
func (_c *ItemCreate) SetNillableIsReturnable(v *bool) *ItemCreate {
	if v != nil {
		_c.SetIsReturnable(*v)
	}
	return _c
}

// SetReturnWindowDays sets the "return_window_days" field.
func (_c *ItemCreate) SetReturnWindowDays(v int) *ItemCreate {
	_c.mutation.SetReturnWindowDays(v)
	return _c
}

// SetNillableReturnWindowDays sets the "return_window_days" field if the given value is not nil.
func (_c *ItemCreate) SetNillableReturnWindowDays(v *int) *ItemCreate {
	if v != nil {
		_c.SetReturnWindowDays(*v)
	}
	return _c
}

// SetAllowBackorder sets the "allow_backorder" field.
func (_c *ItemCreate) SetAllowBackorder(v bool) *ItemCreate {
	_c.mutation.SetAllowBackorder(v)
	return _c
}

// SetNillableAllowBackorder sets the "allow_backorder" field if the given value is not nil.
func (_c *ItemCreate) SetNillableAllowBackorder(v *bool) *ItemCreate {
	if v != nil {
		_c.SetAllowBackorder(*v)
	}
	return _c
}

// SetIsDiscontinued sets the "is_discontinued" field.
func (_c *ItemCreate) SetIsDiscontinued(v bool) *ItemCreate {
	_c.mutation.SetIsDiscontinued(v)
	return _c
}

// SetNillableIsDiscontinued sets the "is_discontinued" field if the given value is not nil.
func (_c *ItemCreate) SetNillableIsDiscontinued(v *bool) *ItemCreate {
	if v != nil {
		_c.SetIsDiscontinued(*v)
	}
	return _c
}

// SetUnitID sets the "unit_id" field.
func (_c *ItemCreate) SetUnitID(v uuid.UUID) *ItemCreate {
	_c.mutation.SetUnitID(v)
	return _c
}

// SetNillableUnitID sets the "unit_id" field if the given value is not nil.
func (_c *ItemCreate) SetNillableUnitID(v *uuid.UUID) *ItemCreate {
	if v != nil {
		_c.SetUnitID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ItemCreate) SetType(v item.Type) *ItemCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ItemCreate) SetNillableType(v *item.Type) *ItemCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetUseCase sets the "use_case" field.
func (_c *ItemCreate) SetUseCase(v item.UseCase) *ItemCreate {
	_c.mutation.SetUseCase(v)
	return _c
}

// SetNillableUseCase sets the "use_case" field if the given value is not nil.
func (_c *ItemCreate) SetNillableUseCase(v *item.UseCase) *ItemCreate {
	if v != nil {
		_c.SetUseCase(*v)
	}
	return _c
}

// SetMealPlan sets the "meal_plan" field.
func (_c *ItemCreate) SetMealPlan(v item.MealPlan) *ItemCreate {
	_c.mutation.SetMealPlan(v)
	return _c
}

// SetNillableMealPlan sets the "meal_plan" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMealPlan(v *item.MealPlan) *ItemCreate {
	if v != nil {
		_c.SetMealPlan(*v)
	}
	return _c
}

// SetOccupancyBasis sets the "occupancy_basis" field.
func (_c *ItemCreate) SetOccupancyBasis(v item.OccupancyBasis) *ItemCreate {
	_c.mutation.SetOccupancyBasis(v)
	return _c
}

// SetNillableOccupancyBasis sets the "occupancy_basis" field if the given value is not nil.
func (_c *ItemCreate) SetNillableOccupancyBasis(v *item.OccupancyBasis) *ItemCreate {
	if v != nil {
		_c.SetOccupancyBasis(*v)
	}
	return _c
}

// SetMaxAdults sets the "max_adults" field.
func (_c *ItemCreate) SetMaxAdults(v int) *ItemCreate {
	_c.mutation.SetMaxAdults(v)
	return _c
}

// SetNillableMaxAdults sets the "max_adults" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMaxAdults(v *int) *ItemCreate {
	if v != nil {
		_c.SetMaxAdults(*v)
	}
	return _c
}

// SetMaxChildren sets the "max_children" field.
func (_c *ItemCreate) SetMaxChildren(v int) *ItemCreate {
	_c.mutation.SetMaxChildren(v)
	return _c
}

// SetNillableMaxChildren sets the "max_children" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMaxChildren(v *int) *ItemCreate {
	if v != nil {
		_c.SetMaxChildren(*v)
	}
	return _c
}

// SetExtraBedAllowed sets the "extra_bed_allowed" field.
func (_c *ItemCreate) SetExtraBedAllowed(v bool) *ItemCreate {
	_c.mutation.SetExtraBedAllowed(v)
	return _c
}

// SetNillableExtraBedAllowed sets the "extra_bed_allowed" field if the given value is not nil.
func (_c *ItemCreate) SetNillableExtraBedAllowed(v *bool) *ItemCreate {
	if v != nil {
		_c.SetExtraBedAllowed(*v)
	}
	return _c
}

// SetSingleSupplement sets the "single_supplement" field.
func (_c *ItemCreate) SetSingleSupplement(v float64) *ItemCreate {
	_c.mutation.SetSingleSupplement(v)
	return _c
}

// SetNillableSingleSupplement sets the "single_supplement" field if the given value is not nil.
func (_c *ItemCreate) SetNillableSingleSupplement(v *float64) *ItemCreate {
	if v != nil {
		_c.SetSingleSupplement(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ItemCreate) SetIsActive(v bool) *ItemCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ItemCreate) SetNillableIsActive(v *bool) *ItemCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *ItemCreate) SetImageURL(v string) *ItemCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *ItemCreate) SetNillableImageURL(v *string) *ItemCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetBarcode sets the "barcode" field.
func (_c *ItemCreate) SetBarcode(v string) *ItemCreate {
	_c.mutation.SetBarcode(v)
	return _c
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (_c *ItemCreate) SetNillableBarcode(v *string) *ItemCreate {
	if v != nil {
		_c.SetBarcode(*v)
	}
	return _c
}

// SetBarcodeType sets the "barcode_type" field.
func (_c *ItemCreate) SetBarcodeType(v string) *ItemCreate {
	_c.mutation.SetBarcodeType(v)
	return _c
}

// SetNillableBarcodeType sets the "barcode_type" field if the given value is not nil.
func (_c *ItemCreate) SetNillableBarcodeType(v *string) *ItemCreate {
	if v != nil {
		_c.SetBarcodeType(*v)
	}
	return _c
}

// SetRequiresAgeVerification sets the "requires_age_verification" field.
func (_c *ItemCreate) SetRequiresAgeVerification(v bool) *ItemCreate {
	_c.mutation.SetRequiresAgeVerification(v)
	return _c
}

// SetNillableRequiresAgeVerification sets the "requires_age_verification" field if the given value is not nil.
func (_c *ItemCreate) SetNillableRequiresAgeVerification(v *bool) *ItemCreate {
	if v != nil {
		_c.SetRequiresAgeVerification(*v)
	}
	return _c
}

// SetIsControlledSubstance sets the "is_controlled_substance" field.
func (_c *ItemCreate) SetIsControlledSubstance(v bool) *ItemCreate {
	_c.mutation.SetIsControlledSubstance(v)
	return _c
}

// SetNillableIsControlledSubstance sets the "is_controlled_substance" field if the given value is not nil.
func (_c *ItemCreate) SetNillableIsControlledSubstance(v *bool) *ItemCreate {
	if v != nil {
		_c.SetIsControlledSubstance(*v)
	}
	return _c
}

// SetIsPerishable sets the "is_perishable" field.
func (_c *ItemCreate) SetIsPerishable(v bool) *ItemCreate {
	_c.mutation.SetIsPerishable(v)
	return _c
}

// SetNillableIsPerishable sets the "is_perishable" field if the given value is not nil.
func (_c *ItemCreate) SetNillableIsPerishable(v *bool) *ItemCreate {
	if v != nil {
		_c.SetIsPerishable(*v)
	}
	return _c
}

// SetTrackSerialNumbers sets the "track_serial_numbers" field.
func (_c *ItemCreate) SetTrackSerialNumbers(v bool) *ItemCreate {
	_c.mutation.SetTrackSerialNumbers(v)
	return _c
}

// SetNillableTrackSerialNumbers sets the "track_serial_numbers" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTrackSerialNumbers(v *bool) *ItemCreate {
	if v != nil {
		_c.SetTrackSerialNumbers(*v)
	}
	return _c
}

// SetTrackLots sets the "track_lots" field.
func (_c *ItemCreate) SetTrackLots(v bool) *ItemCreate {
	_c.mutation.SetTrackLots(v)
	return _c
}

// SetNillableTrackLots sets the "track_lots" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTrackLots(v *bool) *ItemCreate {
	if v != nil {
		_c.SetTrackLots(*v)
	}
	return _c
}

// SetShelfLifeDays sets the "shelf_life_days" field.
func (_c *ItemCreate) SetShelfLifeDays(v int) *ItemCreate {
	_c.mutation.SetShelfLifeDays(v)
	return _c
}

// SetNillableShelfLifeDays sets the "shelf_life_days" field if the given value is not nil.
func (_c *ItemCreate) SetNillableShelfLifeDays(v *int) *ItemCreate {
	if v != nil {
		_c.SetShelfLifeDays(*v)
	}
	return _c
}

// SetWeightKg sets the "weight_kg" field.
func (_c *ItemCreate) SetWeightKg(v float64) *ItemCreate {
	_c.mutation.SetWeightKg(v)
	return _c
}

// SetNillableWeightKg sets the "weight_kg" field if the given value is not nil.
func (_c *ItemCreate) SetNillableWeightKg(v *float64) *ItemCreate {
	if v != nil {
		_c.SetWeightKg(*v)
	}
	return _c
}

// SetDimensionsCm sets the "dimensions_cm" field.
func (_c *ItemCreate) SetDimensionsCm(v map[string]float64) *ItemCreate {
	_c.mutation.SetDimensionsCm(v)
	return _c
}

// SetDurationMinutes sets the "duration_minutes" field.
func (_c *ItemCreate) SetDurationMinutes(v int) *ItemCreate {
	_c.mutation.SetDurationMinutes(v)
	return _c
}

// SetNillableDurationMinutes sets the "duration_minutes" field if the given value is not nil.
func (_c *ItemCreate) SetNillableDurationMinutes(v *int) *ItemCreate {
	if v != nil {
		_c.SetDurationMinutes(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *ItemCreate) SetTags(v []string) *ItemCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetTaxCodeID sets the "tax_code_id" field.
func (_c *ItemCreate) SetTaxCodeID(v string) *ItemCreate {
	_c.mutation.SetTaxCodeID(v)
	return _c
}

// SetNillableTaxCodeID sets the "tax_code_id" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTaxCodeID(v *string) *ItemCreate {
	if v != nil {
		_c.SetTaxCodeID(*v)
	}
	return _c
}

// SetTaxInclusive sets the "tax_inclusive" field.
func (_c *ItemCreate) SetTaxInclusive(v bool) *ItemCreate {
	_c.mutation.SetTaxInclusive(v)
	return _c
}

// SetNillableTaxInclusive sets the "tax_inclusive" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTaxInclusive(v *bool) *ItemCreate {
	if v != nil {
		_c.SetTaxInclusive(*v)
	}
	return _c
}

// SetCostPrice sets the "cost_price" field.
func (_c *ItemCreate) SetCostPrice(v float64) *ItemCreate {
	_c.mutation.SetCostPrice(v)
	return _c
}

// SetNillableCostPrice sets the "cost_price" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCostPrice(v *float64) *ItemCreate {
	if v != nil {
		_c.SetCostPrice(*v)
	}
	return _c
}

// SetPurchasePrice sets the "purchase_price" field.
func (_c *ItemCreate) SetPurchasePrice(v float64) *ItemCreate {
	_c.mutation.SetPurchasePrice(v)
	return _c
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (_c *ItemCreate) SetNillablePurchasePrice(v *float64) *ItemCreate {
	if v != nil {
		_c.SetPurchasePrice(*v)
	}
	return _c
}

// SetPurchasePackSize sets the "purchase_pack_size" field.
func (_c *ItemCreate) SetPurchasePackSize(v float64) *ItemCreate {
	_c.mutation.SetPurchasePackSize(v)
	return _c
}

// SetNillablePurchasePackSize sets the "purchase_pack_size" field if the given value is not nil.
func (_c *ItemCreate) SetNillablePurchasePackSize(v *float64) *ItemCreate {
	if v != nil {
		_c.SetPurchasePackSize(*v)
	}
	return _c
}

// SetPurchaseUnit sets the "purchase_unit" field.
func (_c *ItemCreate) SetPurchaseUnit(v string) *ItemCreate {
	_c.mutation.SetPurchaseUnit(v)
	return _c
}

// SetNillablePurchaseUnit sets the "purchase_unit" field if the given value is not nil.
func (_c *ItemCreate) SetNillablePurchaseUnit(v *string) *ItemCreate {
	if v != nil {
		_c.SetPurchaseUnit(*v)
	}
	return _c
}

// SetYieldPct sets the "yield_pct" field.
func (_c *ItemCreate) SetYieldPct(v float64) *ItemCreate {
	_c.mutation.SetYieldPct(v)
	return _c
}

// SetNillableYieldPct sets the "yield_pct" field if the given value is not nil.
func (_c *ItemCreate) SetNillableYieldPct(v *float64) *ItemCreate {
	if v != nil {
		_c.SetYieldPct(*v)
	}
	return _c
}

// SetMinSellingPrice sets the "min_selling_price" field.
func (_c *ItemCreate) SetMinSellingPrice(v float64) *ItemCreate {
	_c.mutation.SetMinSellingPrice(v)
	return _c
}

// SetNillableMinSellingPrice sets the "min_selling_price" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMinSellingPrice(v *float64) *ItemCreate {
	if v != nil {
		_c.SetMinSellingPrice(*v)
	}
	return _c
}

// SetMaxSellingPrice sets the "max_selling_price" field.
func (_c *ItemCreate) SetMaxSellingPrice(v float64) *ItemCreate {
	_c.mutation.SetMaxSellingPrice(v)
	return _c
}

// SetNillableMaxSellingPrice sets the "max_selling_price" field if the given value is not nil.
func (_c *ItemCreate) SetNillableMaxSellingPrice(v *float64) *ItemCreate {
	if v != nil {
		_c.SetMaxSellingPrice(*v)
	}
	return _c
}

// SetTargetMarginPercent sets the "target_margin_percent" field.
func (_c *ItemCreate) SetTargetMarginPercent(v float64) *ItemCreate {
	_c.mutation.SetTargetMarginPercent(v)
	return _c
}

// SetNillableTargetMarginPercent sets the "target_margin_percent" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTargetMarginPercent(v *float64) *ItemCreate {
	if v != nil {
		_c.SetTargetMarginPercent(*v)
	}
	return _c
}

// SetTotalCapacity sets the "total_capacity" field.
func (_c *ItemCreate) SetTotalCapacity(v int) *ItemCreate {
	_c.mutation.SetTotalCapacity(v)
	return _c
}

// SetNillableTotalCapacity sets the "total_capacity" field if the given value is not nil.
func (_c *ItemCreate) SetNillableTotalCapacity(v *int) *ItemCreate {
	if v != nil {
		_c.SetTotalCapacity(*v)
	}
	return _c
}

// SetBookedCapacity sets the "booked_capacity" field.
func (_c *ItemCreate) SetBookedCapacity(v int) *ItemCreate {
	_c.mutation.SetBookedCapacity(v)
	return _c
}

// SetNillableBookedCapacity sets the "booked_capacity" field if the given value is not nil.
func (_c *ItemCreate) SetNillableBookedCapacity(v *int) *ItemCreate {
	if v != nil {
		_c.SetBookedCapacity(*v)
	}
	return _c
}

// SetEventStartAt sets the "event_start_at" field.
func (_c *ItemCreate) SetEventStartAt(v time.Time) *ItemCreate {
	_c.mutation.SetEventStartAt(v)
	return _c
}

// SetNillableEventStartAt sets the "event_start_at" field if the given value is not nil.
func (_c *ItemCreate) SetNillableEventStartAt(v *time.Time) *ItemCreate {
	if v != nil {
		_c.SetEventStartAt(*v)
	}
	return _c
}

// SetEventEndAt sets the "event_end_at" field.
func (_c *ItemCreate) SetEventEndAt(v time.Time) *ItemCreate {
	_c.mutation.SetEventEndAt(v)
	return _c
}

// SetNillableEventEndAt sets the "event_end_at" field if the given value is not nil.
func (_c *ItemCreate) SetNillableEventEndAt(v *time.Time) *ItemCreate {
	if v != nil {
		_c.SetEventEndAt(*v)
	}
	return _c
}

// SetEventVenue sets the "event_venue" field.
func (_c *ItemCreate) SetEventVenue(v string) *ItemCreate {
	_c.mutation.SetEventVenue(v)
	return _c
}

// SetNillableEventVenue sets the "event_venue" field if the given value is not nil.
func (_c *ItemCreate) SetNillableEventVenue(v *string) *ItemCreate {
	if v != nil {
		_c.SetEventVenue(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ItemCreate) SetMetadata(v map[string]interface{}) *ItemCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ItemCreate) SetCreatedAt(v time.Time) *ItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ItemCreate) SetNillableCreatedAt(v *time.Time) *ItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ItemCreate) SetUpdatedAt(v time.Time) *ItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ItemCreate) SetNillableUpdatedAt(v *time.Time) *ItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ItemCreate) SetID(v uuid.UUID) *ItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ItemCreate) SetNillableID(v *uuid.UUID) *ItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *ItemCreate) SetTenant(v *Tenant) *ItemCreate {
	return _c.SetTenantID(v.ID)
}

// AddBalanceIDs adds the "balances" edge to the InventoryBalance entity by IDs.
func (_c *ItemCreate) AddBalanceIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddBalanceIDs(ids...)
	return _c
}

// AddBalances adds the "balances" edges to the InventoryBalance entity.
func (_c *ItemCreate) AddBalances(v ...*InventoryBalance) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBalanceIDs(ids...)
}

// AddRecipeIngredientIDs adds the "recipe_ingredients" edge to the RecipeIngredient entity by IDs.
func (_c *ItemCreate) AddRecipeIngredientIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddRecipeIngredientIDs(ids...)
	return _c
}

// AddRecipeIngredients adds the "recipe_ingredients" edges to the RecipeIngredient entity.
func (_c *ItemCreate) AddRecipeIngredients(v ...*RecipeIngredient) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRecipeIngredientIDs(ids...)
}

// SetUnitsID sets the "units" edge to the Unit entity by ID.
func (_c *ItemCreate) SetUnitsID(id uuid.UUID) *ItemCreate {
	_c.mutation.SetUnitsID(id)
	return _c
}

// SetNillableUnitsID sets the "units" edge to the Unit entity by ID if the given value is not nil.
func (_c *ItemCreate) SetNillableUnitsID(id *uuid.UUID) *ItemCreate {
	if id != nil {
		_c = _c.SetUnitsID(*id)
	}
	return _c
}

// SetUnits sets the "units" edge to the Unit entity.
func (_c *ItemCreate) SetUnits(v *Unit) *ItemCreate {
	return _c.SetUnitsID(v.ID)
}

// AddVariantIDs adds the "variants" edge to the ItemVariant entity by IDs.
func (_c *ItemCreate) AddVariantIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddVariantIDs(ids...)
	return _c
}

// AddVariants adds the "variants" edges to the ItemVariant entity.
func (_c *ItemCreate) AddVariants(v ...*ItemVariant) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVariantIDs(ids...)
}

// AddAssetIDs adds the "assets" edge to the ItemAsset entity by IDs.
func (_c *ItemCreate) AddAssetIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddAssetIDs(ids...)
	return _c
}

// AddAssets adds the "assets" edges to the ItemAsset entity.
func (_c *ItemCreate) AddAssets(v ...*ItemAsset) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssetIDs(ids...)
}

// AddTranslationIDs adds the "translations" edge to the ItemTranslation entity by IDs.
func (_c *ItemCreate) AddTranslationIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddTranslationIDs(ids...)
	return _c
}

// AddTranslations adds the "translations" edges to the ItemTranslation entity.
func (_c *ItemCreate) AddTranslations(v ...*ItemTranslation) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTranslationIDs(ids...)
}

// AddModifierGroupIDs adds the "modifier_groups" edge to the ModifierGroup entity by IDs.
func (_c *ItemCreate) AddModifierGroupIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddModifierGroupIDs(ids...)
	return _c
}

// AddModifierGroups adds the "modifier_groups" edges to the ModifierGroup entity.
func (_c *ItemCreate) AddModifierGroups(v ...*ModifierGroup) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModifierGroupIDs(ids...)
}

// AddLotIDs adds the "lots" edge to the InventoryLot entity by IDs.
func (_c *ItemCreate) AddLotIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddLotIDs(ids...)
	return _c
}

// AddLots adds the "lots" edges to the InventoryLot entity.
func (_c *ItemCreate) AddLots(v ...*InventoryLot) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLotIDs(ids...)
}

// AddCustomFieldValueIDs adds the "custom_field_values" edge to the CustomFieldValue entity by IDs.
func (_c *ItemCreate) AddCustomFieldValueIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddCustomFieldValueIDs(ids...)
	return _c
}

// AddCustomFieldValues adds the "custom_field_values" edges to the CustomFieldValue entity.
func (_c *ItemCreate) AddCustomFieldValues(v ...*CustomFieldValue) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomFieldValueIDs(ids...)
}

// SetBundleID sets the "bundle" edge to the Bundle entity by ID.
func (_c *ItemCreate) SetBundleID(id uuid.UUID) *ItemCreate {
	_c.mutation.SetBundleID(id)
	return _c
}

// SetNillableBundleID sets the "bundle" edge to the Bundle entity by ID if the given value is not nil.
func (_c *ItemCreate) SetNillableBundleID(id *uuid.UUID) *ItemCreate {
	if id != nil {
		_c = _c.SetBundleID(*id)
	}
	return _c
}

// SetBundle sets the "bundle" edge to the Bundle entity.
func (_c *ItemCreate) SetBundle(v *Bundle) *ItemCreate {
	return _c.SetBundleID(v.ID)
}

// AddBundleComponentIDs adds the "bundle_components" edge to the BundleComponent entity by IDs.
func (_c *ItemCreate) AddBundleComponentIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddBundleComponentIDs(ids...)
	return _c
}

// AddBundleComponents adds the "bundle_components" edges to the BundleComponent entity.
func (_c *ItemCreate) AddBundleComponents(v ...*BundleComponent) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddBundleComponentIDs(ids...)
}

// AddWarrantyIDs adds the "warranties" edge to the Warranty entity by IDs.
func (_c *ItemCreate) AddWarrantyIDs(ids ...uuid.UUID) *ItemCreate {
	_c.mutation.AddWarrantyIDs(ids...)
	return _c
}

// AddWarranties adds the "warranties" edges to the Warranty entity.
func (_c *ItemCreate) AddWarranties(v ...*Warranty) *ItemCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWarrantyIDs(ids...)
}

// SetProducedByRecipeID sets the "produced_by_recipe" edge to the Recipe entity by ID.
func (_c *ItemCreate) SetProducedByRecipeID(id uuid.UUID) *ItemCreate {
	_c.mutation.SetProducedByRecipeID(id)
	return _c
}

// SetNillableProducedByRecipeID sets the "produced_by_recipe" edge to the Recipe entity by ID if the given value is not nil.
func (_c *ItemCreate) SetNillableProducedByRecipeID(id *uuid.UUID) *ItemCreate {
	if id != nil {
		_c = _c.SetProducedByRecipeID(*id)
	}
	return _c
}

// SetProducedByRecipe sets the "produced_by_recipe" edge to the Recipe entity.
func (_c *ItemCreate) SetProducedByRecipe(v *Recipe) *ItemCreate {
	return _c.SetProducedByRecipeID(v.ID)
}

// SetItemCategoryID sets the "item_category" edge to the ItemCategory entity by ID.
func (_c *ItemCreate) SetItemCategoryID(id uuid.UUID) *ItemCreate {
	_c.mutation.SetItemCategoryID(id)
	return _c
}

// SetNillableItemCategoryID sets the "item_category" edge to the ItemCategory entity by ID if the given value is not nil.
func (_c *ItemCreate) SetNillableItemCategoryID(id *uuid.UUID) *ItemCreate {
	if id != nil {
		_c = _c.SetItemCategoryID(*id)
	}
	return _c
}

// SetItemCategory sets the "item_category" edge to the ItemCategory entity.
func (_c *ItemCreate) SetItemCategory(v *ItemCategory) *ItemCreate {
	return _c.SetItemCategoryID(v.ID)
}

// SetItemBrandID sets the "item_brand" edge to the ItemBrand entity by ID.
func (_c *ItemCreate) SetItemBrandID(id uuid.UUID) *ItemCreate {
	_c.mutation.SetItemBrandID(id)
	return _c
}

// SetNillableItemBrandID sets the "item_brand" edge to the ItemBrand entity by ID if the given value is not nil.
func (_c *ItemCreate) SetNillableItemBrandID(id *uuid.UUID) *ItemCreate {
	if id != nil {
		_c = _c.SetItemBrandID(*id)
	}
	return _c
}

// SetItemBrand sets the "item_brand" edge to the ItemBrand entity.
func (_c *ItemCreate) SetItemBrand(v *ItemBrand) *ItemCreate {
	return _c.SetItemBrandID(v.ID)
}

// Mutation returns the ItemMutation object of the builder.
func (_c *ItemCreate) Mutation() *ItemMutation {
	return _c.mutation
}

// Save creates the Item in the database.
func (_c *ItemCreate) Save(ctx context.Context) (*Item, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemCreate) SaveX(ctx context.Context) *Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemCreate) defaults() {
	if _, ok := _c.mutation.Condition(); !ok {
		v := item.DefaultCondition
		_c.mutation.SetCondition(v)
	}
	if _, ok := _c.mutation.IsReturnable(); !ok {
		v := item.DefaultIsReturnable
		_c.mutation.SetIsReturnable(v)
	}
	if _, ok := _c.mutation.AllowBackorder(); !ok {
		v := item.DefaultAllowBackorder
		_c.mutation.SetAllowBackorder(v)
	}
	if _, ok := _c.mutation.IsDiscontinued(); !ok {
		v := item.DefaultIsDiscontinued
		_c.mutation.SetIsDiscontinued(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := item.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.UseCase(); !ok {
		v := item.DefaultUseCase
		_c.mutation.SetUseCase(v)
	}
	if _, ok := _c.mutation.ExtraBedAllowed(); !ok {
		v := item.DefaultExtraBedAllowed
		_c.mutation.SetExtraBedAllowed(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := item.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.RequiresAgeVerification(); !ok {
		v := item.DefaultRequiresAgeVerification
		_c.mutation.SetRequiresAgeVerification(v)
	}
	if _, ok := _c.mutation.IsControlledSubstance(); !ok {
		v := item.DefaultIsControlledSubstance
		_c.mutation.SetIsControlledSubstance(v)
	}
	if _, ok := _c.mutation.IsPerishable(); !ok {
		v := item.DefaultIsPerishable
		_c.mutation.SetIsPerishable(v)
	}
	if _, ok := _c.mutation.TrackSerialNumbers(); !ok {
		v := item.DefaultTrackSerialNumbers
		_c.mutation.SetTrackSerialNumbers(v)
	}
	if _, ok := _c.mutation.TrackLots(); !ok {
		v := item.DefaultTrackLots
		_c.mutation.SetTrackLots(v)
	}
	if _, ok := _c.mutation.Tags(); !ok {
		v := item.DefaultTags
		_c.mutation.SetTags(v)
	}
	if _, ok := _c.mutation.TaxInclusive(); !ok {
		v := item.DefaultTaxInclusive
		_c.mutation.SetTaxInclusive(v)
	}
	if _, ok := _c.mutation.YieldPct(); !ok {
		v := item.DefaultYieldPct
		_c.mutation.SetYieldPct(v)
	}
	if _, ok := _c.mutation.BookedCapacity(); !ok {
		v := item.DefaultBookedCapacity
		_c.mutation.SetBookedCapacity(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := item.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := item.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := item.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := item.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Item.tenant_id"`)}
	}
	if _, ok := _c.mutation.Sku(); !ok {
		return &ValidationError{Name: "sku", err: errors.New(`ent: missing required field "Item.sku"`)}
	}
	if v, ok := _c.mutation.Sku(); ok {
		if err := item.SkuValidator(v); err != nil {
			return &ValidationError{Name: "sku", err: fmt.Errorf(`ent: validator failed for field "Item.sku": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Item.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "Item.condition"`)}
	}
	if v, ok := _c.mutation.Condition(); ok {
		if err := item.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "Item.condition": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsReturnable(); !ok {
		return &ValidationError{Name: "is_returnable", err: errors.New(`ent: missing required field "Item.is_returnable"`)}
	}
	if _, ok := _c.mutation.AllowBackorder(); !ok {
		return &ValidationError{Name: "allow_backorder", err: errors.New(`ent: missing required field "Item.allow_backorder"`)}
	}
	if _, ok := _c.mutation.IsDiscontinued(); !ok {
		return &ValidationError{Name: "is_discontinued", err: errors.New(`ent: missing required field "Item.is_discontinued"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Item.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := item.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Item.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UseCase(); !ok {
		return &ValidationError{Name: "use_case", err: errors.New(`ent: missing required field "Item.use_case"`)}
	}
	if v, ok := _c.mutation.UseCase(); ok {
		if err := item.UseCaseValidator(v); err != nil {
			return &ValidationError{Name: "use_case", err: fmt.Errorf(`ent: validator failed for field "Item.use_case": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MealPlan(); ok {
		if err := item.MealPlanValidator(v); err != nil {
			return &ValidationError{Name: "meal_plan", err: fmt.Errorf(`ent: validator failed for field "Item.meal_plan": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OccupancyBasis(); ok {
		if err := item.OccupancyBasisValidator(v); err != nil {
			return &ValidationError{Name: "occupancy_basis", err: fmt.Errorf(`ent: validator failed for field "Item.occupancy_basis": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExtraBedAllowed(); !ok {
		return &ValidationError{Name: "extra_bed_allowed", err: errors.New(`ent: missing required field "Item.extra_bed_allowed"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Item.is_active"`)}
	}
	if _, ok := _c.mutation.RequiresAgeVerification(); !ok {
		return &ValidationError{Name: "requires_age_verification", err: errors.New(`ent: missing required field "Item.requires_age_verification"`)}
	}
	if _, ok := _c.mutation.IsControlledSubstance(); !ok {
		return &ValidationError{Name: "is_controlled_substance", err: errors.New(`ent: missing required field "Item.is_controlled_substance"`)}
	}
	if _, ok := _c.mutation.IsPerishable(); !ok {
		return &ValidationError{Name: "is_perishable", err: errors.New(`ent: missing required field "Item.is_perishable"`)}
	}
	if _, ok := _c.mutation.TrackSerialNumbers(); !ok {
		return &ValidationError{Name: "track_serial_numbers", err: errors.New(`ent: missing required field "Item.track_serial_numbers"`)}
	}
	if _, ok := _c.mutation.TrackLots(); !ok {
		return &ValidationError{Name: "track_lots", err: errors.New(`ent: missing required field "Item.track_lots"`)}
	}
	if _, ok := _c.mutation.Tags(); !ok {
		return &ValidationError{Name: "tags", err: errors.New(`ent: missing required field "Item.tags"`)}
	}
	if _, ok := _c.mutation.TaxInclusive(); !ok {
		return &ValidationError{Name: "tax_inclusive", err: errors.New(`ent: missing required field "Item.tax_inclusive"`)}
	}
	if v, ok := _c.mutation.PurchaseUnit(); ok {
		if err := item.PurchaseUnitValidator(v); err != nil {
			return &ValidationError{Name: "purchase_unit", err: fmt.Errorf(`ent: validator failed for field "Item.purchase_unit": %w`, err)}
		}
	}
	if v, ok := _c.mutation.EventVenue(); ok {
		if err := item.EventVenueValidator(v); err != nil {
			return &ValidationError{Name: "event_venue", err: fmt.Errorf(`ent: validator failed for field "Item.event_venue": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "Item.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Item.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Item.updated_at"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Item.tenant"`)}
	}
	return nil
}

func (_c *ItemCreate) sqlSave(ctx context.Context) (*Item, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemCreate) createSpec() (*Item, *sqlgraph.CreateSpec) {
	var (
		_node = &Item{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(item.Table, sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Sku(); ok {
		_spec.SetField(item.FieldSku, field.TypeString, value)
		_node.Sku = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(item.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Manufacturer(); ok {
		_spec.SetField(item.FieldManufacturer, field.TypeString, value)
		_node.Manufacturer = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(item.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Gtin(); ok {
		_spec.SetField(item.FieldGtin, field.TypeString, value)
		_node.Gtin = value
	}
	if value, ok := _c.mutation.Mpn(); ok {
		_spec.SetField(item.FieldMpn, field.TypeString, value)
		_node.Mpn = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(item.FieldCondition, field.TypeEnum, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(item.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.ShortDescription(); ok {
		_spec.SetField(item.FieldShortDescription, field.TypeString, value)
		_node.ShortDescription = value
	}
	if value, ok := _c.mutation.MetaTitle(); ok {
		_spec.SetField(item.FieldMetaTitle, field.TypeString, value)
		_node.MetaTitle = value
	}
	if value, ok := _c.mutation.MetaDescription(); ok {
		_spec.SetField(item.FieldMetaDescription, field.TypeString, value)
		_node.MetaDescription = value
	}
	if value, ok := _c.mutation.CountryOfOrigin(); ok {
		_spec.SetField(item.FieldCountryOfOrigin, field.TypeString, value)
		_node.CountryOfOrigin = value
	}
	if value, ok := _c.mutation.HsCode(); ok {
		_spec.SetField(item.FieldHsCode, field.TypeString, value)
		_node.HsCode = value
	}
	if value, ok := _c.mutation.IsReturnable(); ok {
		_spec.SetField(item.FieldIsReturnable, field.TypeBool, value)
		_node.IsReturnable = value
	}
	if value, ok := _c.mutation.ReturnWindowDays(); ok {
		_spec.SetField(item.FieldReturnWindowDays, field.TypeInt, value)
		_node.ReturnWindowDays = &value
	}
	if value, ok := _c.mutation.AllowBackorder(); ok {
		_spec.SetField(item.FieldAllowBackorder, field.TypeBool, value)
		_node.AllowBackorder = value
	}
	if value, ok := _c.mutation.IsDiscontinued(); ok {
		_spec.SetField(item.FieldIsDiscontinued, field.TypeBool, value)
		_node.IsDiscontinued = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(item.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.UseCase(); ok {
		_spec.SetField(item.FieldUseCase, field.TypeEnum, value)
		_node.UseCase = value
	}
	if value, ok := _c.mutation.MealPlan(); ok {
		_spec.SetField(item.FieldMealPlan, field.TypeEnum, value)
		_node.MealPlan = &value
	}
	if value, ok := _c.mutation.OccupancyBasis(); ok {
		_spec.SetField(item.FieldOccupancyBasis, field.TypeEnum, value)
		_node.OccupancyBasis = &value
	}
	if value, ok := _c.mutation.MaxAdults(); ok {
		_spec.SetField(item.FieldMaxAdults, field.TypeInt, value)
		_node.MaxAdults = &value
	}
	if value, ok := _c.mutation.MaxChildren(); ok {
		_spec.SetField(item.FieldMaxChildren, field.TypeInt, value)
		_node.MaxChildren = &value
	}
	if value, ok := _c.mutation.ExtraBedAllowed(); ok {
		_spec.SetField(item.FieldExtraBedAllowed, field.TypeBool, value)
		_node.ExtraBedAllowed = value
	}
	if value, ok := _c.mutation.SingleSupplement(); ok {
		_spec.SetField(item.FieldSingleSupplement, field.TypeFloat64, value)
		_node.SingleSupplement = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(item.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(item.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.Barcode(); ok {
		_spec.SetField(item.FieldBarcode, field.TypeString, value)
		_node.Barcode = value
	}
	if value, ok := _c.mutation.BarcodeType(); ok {
		_spec.SetField(item.FieldBarcodeType, field.TypeString, value)
		_node.BarcodeType = value
	}
	if value, ok := _c.mutation.RequiresAgeVerification(); ok {
		_spec.SetField(item.FieldRequiresAgeVerification, field.TypeBool, value)
		_node.RequiresAgeVerification = value
	}
	if value, ok := _c.mutation.IsControlledSubstance(); ok {
		_spec.SetField(item.FieldIsControlledSubstance, field.TypeBool, value)
		_node.IsControlledSubstance = value
	}
	if value, ok := _c.mutation.IsPerishable(); ok {
		_spec.SetField(item.FieldIsPerishable, field.TypeBool, value)
		_node.IsPerishable = value
	}
	if value, ok := _c.mutation.TrackSerialNumbers(); ok {
		_spec.SetField(item.FieldTrackSerialNumbers, field.TypeBool, value)
		_node.TrackSerialNumbers = value
	}
	if value, ok := _c.mutation.TrackLots(); ok {
		_spec.SetField(item.FieldTrackLots, field.TypeBool, value)
		_node.TrackLots = value
	}
	if value, ok := _c.mutation.ShelfLifeDays(); ok {
		_spec.SetField(item.FieldShelfLifeDays, field.TypeInt, value)
		_node.ShelfLifeDays = &value
	}
	if value, ok := _c.mutation.WeightKg(); ok {
		_spec.SetField(item.FieldWeightKg, field.TypeFloat64, value)
		_node.WeightKg = &value
	}
	if value, ok := _c.mutation.DimensionsCm(); ok {
		_spec.SetField(item.FieldDimensionsCm, field.TypeJSON, value)
		_node.DimensionsCm = value
	}
	if value, ok := _c.mutation.DurationMinutes(); ok {
		_spec.SetField(item.FieldDurationMinutes, field.TypeInt, value)
		_node.DurationMinutes = &value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(item.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.TaxCodeID(); ok {
		_spec.SetField(item.FieldTaxCodeID, field.TypeString, value)
		_node.TaxCodeID = value
	}
	if value, ok := _c.mutation.TaxInclusive(); ok {
		_spec.SetField(item.FieldTaxInclusive, field.TypeBool, value)
		_node.TaxInclusive = value
	}
	if value, ok := _c.mutation.CostPrice(); ok {
		_spec.SetField(item.FieldCostPrice, field.TypeFloat64, value)
		_node.CostPrice = &value
	}
	if value, ok := _c.mutation.PurchasePrice(); ok {
		_spec.SetField(item.FieldPurchasePrice, field.TypeFloat64, value)
		_node.PurchasePrice = &value
	}
	if value, ok := _c.mutation.PurchasePackSize(); ok {
		_spec.SetField(item.FieldPurchasePackSize, field.TypeFloat64, value)
		_node.PurchasePackSize = &value
	}
	if value, ok := _c.mutation.PurchaseUnit(); ok {
		_spec.SetField(item.FieldPurchaseUnit, field.TypeString, value)
		_node.PurchaseUnit = value
	}
	if value, ok := _c.mutation.YieldPct(); ok {
		_spec.SetField(item.FieldYieldPct, field.TypeFloat64, value)
		_node.YieldPct = &value
	}
	if value, ok := _c.mutation.MinSellingPrice(); ok {
		_spec.SetField(item.FieldMinSellingPrice, field.TypeFloat64, value)
		_node.MinSellingPrice = &value
	}
	if value, ok := _c.mutation.MaxSellingPrice(); ok {
		_spec.SetField(item.FieldMaxSellingPrice, field.TypeFloat64, value)
		_node.MaxSellingPrice = &value
	}
	if value, ok := _c.mutation.TargetMarginPercent(); ok {
		_spec.SetField(item.FieldTargetMarginPercent, field.TypeFloat64, value)
		_node.TargetMarginPercent = &value
	}
	if value, ok := _c.mutation.TotalCapacity(); ok {
		_spec.SetField(item.FieldTotalCapacity, field.TypeInt, value)
		_node.TotalCapacity = &value
	}
	if value, ok := _c.mutation.BookedCapacity(); ok {
		_spec.SetField(item.FieldBookedCapacity, field.TypeInt, value)
		_node.BookedCapacity = &value
	}
	if value, ok := _c.mutation.EventStartAt(); ok {
		_spec.SetField(item.FieldEventStartAt, field.TypeTime, value)
		_node.EventStartAt = &value
	}
	if value, ok := _c.mutation.EventEndAt(); ok {
		_spec.SetField(item.FieldEventEndAt, field.TypeTime, value)
		_node.EventEndAt = &value
	}
	if value, ok := _c.mutation.EventVenue(); ok {
		_spec.SetField(item.FieldEventVenue, field.TypeString, value)
		_node.EventVenue = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(item.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(item.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(item.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.TenantTable,
			Columns: []string{item.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BalancesTable,
			Columns: []string{item.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventorybalance.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RecipeIngredientsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.RecipeIngredientsTable,
			Columns: []string{item.RecipeIngredientsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipeingredient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UnitsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   item.UnitsTable,
			Columns: []string{item.UnitsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(unit.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UnitID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.VariantsTable,
			Columns: []string{item.VariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemvariant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.AssetsTable,
			Columns: []string{item.AssetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemasset.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TranslationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.TranslationsTable,
			Columns: []string{item.TranslationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemtranslation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ModifierGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.ModifierGroupsTable,
			Columns: []string{item.ModifierGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modifiergroup.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LotsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.LotsTable,
			Columns: []string{item.LotsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventorylot.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomFieldValuesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.CustomFieldValuesTable,
			Columns: []string{item.CustomFieldValuesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customfieldvalue.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BundleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   item.BundleTable,
			Columns: []string{item.BundleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundle.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BundleComponentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.BundleComponentsTable,
			Columns: []string{item.BundleComponentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bundlecomponent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WarrantiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.WarrantiesTable,
			Columns: []string{item.WarrantiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(warranty.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProducedByRecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   item.ProducedByRecipeTable,
			Columns: []string{item.ProducedByRecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemCategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.ItemCategoryTable,
			Columns: []string{item.ItemCategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itemcategory.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemBrandIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   item.ItemBrandTable,
			Columns: []string{item.ItemBrandColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(itembrand.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BrandID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ItemCreateBulk is the builder for creating many Item entities in bulk.
type ItemCreateBulk struct {
	config
	err      error
	builders []*ItemCreate
}

// Save creates the Item entities in the database.
func (_c *ItemCreateBulk) Save(ctx context.Context) ([]*Item, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Item, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemCreateBulk) SaveX(ctx context.Context) []*Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
