// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/item"
	"github.com/bengobox/inventory-service/internal/ent/itemasset"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ItemAssetUpdate is the builder for updating ItemAsset entities.
type ItemAssetUpdate struct {
	config
	hooks    []Hook
	mutation *ItemAssetMutation
}

// Where appends a list predicates to the ItemAssetUpdate builder.
func (_u *ItemAssetUpdate) Where(ps ...predicate.ItemAsset) *ItemAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *ItemAssetUpdate) SetItemID(v uuid.UUID) *ItemAssetUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableItemID(v *uuid.UUID) *ItemAssetUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *ItemAssetUpdate) SetAssetType(v string) *ItemAssetUpdate {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableAssetType(v *string) *ItemAssetUpdate {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ItemAssetUpdate) SetURL(v string) *ItemAssetUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableURL(v *string) *ItemAssetUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ItemAssetUpdate) SetFileName(v string) *ItemAssetUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableFileName(v *string) *ItemAssetUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *ItemAssetUpdate) ClearFileName() *ItemAssetUpdate {
	_u.mutation.ClearFileName()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ItemAssetUpdate) SetFileSize(v string) *ItemAssetUpdate {
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableFileSize(v *string) *ItemAssetUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ItemAssetUpdate) ClearFileSize() *ItemAssetUpdate {
	_u.mutation.ClearFileSize()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ItemAssetUpdate) SetMimeType(v string) *ItemAssetUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableMimeType(v *string) *ItemAssetUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ItemAssetUpdate) ClearMimeType() *ItemAssetUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ItemAssetUpdate) SetMetadata(v map[string]interface{}) *ItemAssetUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ItemAssetUpdate) ClearMetadata() *ItemAssetUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ItemAssetUpdate) SetDisplayOrder(v int) *ItemAssetUpdate {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableDisplayOrder(v *int) *ItemAssetUpdate {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ItemAssetUpdate) AddDisplayOrder(v int) *ItemAssetUpdate {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *ItemAssetUpdate) SetIsPrimary(v bool) *ItemAssetUpdate {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *ItemAssetUpdate) SetNillableIsPrimary(v *bool) *ItemAssetUpdate {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemAssetUpdate) SetUpdatedAt(v time.Time) *ItemAssetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *ItemAssetUpdate) SetItem(v *Item) *ItemAssetUpdate {
	return _u.SetItemID(v.ID)
}

// Mutation returns the ItemAssetMutation object of the builder.
func (_u *ItemAssetUpdate) Mutation() *ItemAssetMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *ItemAssetUpdate) ClearItem() *ItemAssetUpdate {
	_u.mutation.ClearItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemAssetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemAssetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := itemasset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemAssetUpdate) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := itemasset.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "ItemAsset.url": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemAsset.item"`)
	}
	return nil
}

func (_u *ItemAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemasset.Table, itemasset.Columns, sqlgraph.NewFieldSpec(itemasset.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(itemasset.FieldAssetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(itemasset.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(itemasset.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(itemasset.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(itemasset.FieldFileSize, field.TypeString, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(itemasset.FieldFileSize, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(itemasset.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(itemasset.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(itemasset.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(itemasset.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(itemasset.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(itemasset.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(itemasset.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(itemasset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemasset.ItemTable,
			Columns: []string{itemasset.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemasset.ItemTable,
			Columns: []string{itemasset.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemAssetUpdateOne is the builder for updating a single ItemAsset entity.
type ItemAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemAssetMutation
}

// SetItemID sets the "item_id" field.
func (_u *ItemAssetUpdateOne) SetItemID(v uuid.UUID) *ItemAssetUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableItemID(v *uuid.UUID) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetAssetType sets the "asset_type" field.
func (_u *ItemAssetUpdateOne) SetAssetType(v string) *ItemAssetUpdateOne {
	_u.mutation.SetAssetType(v)
	return _u
}

// SetNillableAssetType sets the "asset_type" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableAssetType(v *string) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetAssetType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *ItemAssetUpdateOne) SetURL(v string) *ItemAssetUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableURL(v *string) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *ItemAssetUpdateOne) SetFileName(v string) *ItemAssetUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableFileName(v *string) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *ItemAssetUpdateOne) ClearFileName() *ItemAssetUpdateOne {
	_u.mutation.ClearFileName()
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *ItemAssetUpdateOne) SetFileSize(v string) *ItemAssetUpdateOne {
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableFileSize(v *string) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *ItemAssetUpdateOne) ClearFileSize() *ItemAssetUpdateOne {
	_u.mutation.ClearFileSize()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *ItemAssetUpdateOne) SetMimeType(v string) *ItemAssetUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableMimeType(v *string) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *ItemAssetUpdateOne) ClearMimeType() *ItemAssetUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ItemAssetUpdateOne) SetMetadata(v map[string]interface{}) *ItemAssetUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ItemAssetUpdateOne) ClearMetadata() *ItemAssetUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetDisplayOrder sets the "display_order" field.
func (_u *ItemAssetUpdateOne) SetDisplayOrder(v int) *ItemAssetUpdateOne {
	_u.mutation.ResetDisplayOrder()
	_u.mutation.SetDisplayOrder(v)
	return _u
}

// SetNillableDisplayOrder sets the "display_order" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableDisplayOrder(v *int) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetDisplayOrder(*v)
	}
	return _u
}

// AddDisplayOrder adds value to the "display_order" field.
func (_u *ItemAssetUpdateOne) AddDisplayOrder(v int) *ItemAssetUpdateOne {
	_u.mutation.AddDisplayOrder(v)
	return _u
}

// SetIsPrimary sets the "is_primary" field.
func (_u *ItemAssetUpdateOne) SetIsPrimary(v bool) *ItemAssetUpdateOne {
	_u.mutation.SetIsPrimary(v)
	return _u
}

// SetNillableIsPrimary sets the "is_primary" field if the given value is not nil.
func (_u *ItemAssetUpdateOne) SetNillableIsPrimary(v *bool) *ItemAssetUpdateOne {
	if v != nil {
		_u.SetIsPrimary(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ItemAssetUpdateOne) SetUpdatedAt(v time.Time) *ItemAssetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetItem sets the "item" edge to the Item entity.
func (_u *ItemAssetUpdateOne) SetItem(v *Item) *ItemAssetUpdateOne {
	return _u.SetItemID(v.ID)
}

// Mutation returns the ItemAssetMutation object of the builder.
func (_u *ItemAssetUpdateOne) Mutation() *ItemAssetMutation {
	return _u.mutation
}

// ClearItem clears the "item" edge to the Item entity.
func (_u *ItemAssetUpdateOne) ClearItem() *ItemAssetUpdateOne {
	_u.mutation.ClearItem()
	return _u
}

// Where appends a list predicates to the ItemAssetUpdate builder.
func (_u *ItemAssetUpdateOne) Where(ps ...predicate.ItemAsset) *ItemAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemAssetUpdateOne) Select(field string, fields ...string) *ItemAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ItemAsset entity.
func (_u *ItemAssetUpdateOne) Save(ctx context.Context) (*ItemAsset, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemAssetUpdateOne) SaveX(ctx context.Context) *ItemAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ItemAssetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := itemasset.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemAssetUpdateOne) check() error {
	if v, ok := _u.mutation.URL(); ok {
		if err := itemasset.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "ItemAsset.url": %w`, err)}
		}
	}
	if _u.mutation.ItemCleared() && len(_u.mutation.ItemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ItemAsset.item"`)
	}
	return nil
}

func (_u *ItemAssetUpdateOne) sqlSave(ctx context.Context) (_node *ItemAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(itemasset.Table, itemasset.Columns, sqlgraph.NewFieldSpec(itemasset.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ItemAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, itemasset.FieldID)
		for _, f := range fields {
			if !itemasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != itemasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AssetType(); ok {
		_spec.SetField(itemasset.FieldAssetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(itemasset.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(itemasset.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(itemasset.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(itemasset.FieldFileSize, field.TypeString, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(itemasset.FieldFileSize, field.TypeString)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(itemasset.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(itemasset.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(itemasset.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(itemasset.FieldMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.DisplayOrder(); ok {
		_spec.SetField(itemasset.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDisplayOrder(); ok {
		_spec.AddField(itemasset.FieldDisplayOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsPrimary(); ok {
		_spec.SetField(itemasset.FieldIsPrimary, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(itemasset.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemasset.ItemTable,
			Columns: []string{itemasset.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   itemasset.ItemTable,
			Columns: []string{itemasset.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ItemAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{itemasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
