// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/batchrawmaterial"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/bengobox/inventory-service/internal/ent/productionbatch"
	"github.com/bengobox/inventory-service/internal/ent/qualitycheck"
	"github.com/google/uuid"
)

// ProductionBatchUpdate is the builder for updating ProductionBatch entities.
type ProductionBatchUpdate struct {
	config
	hooks    []Hook
	mutation *ProductionBatchMutation
}

// Where appends a list predicates to the ProductionBatchUpdate builder.
func (_u *ProductionBatchUpdate) Where(ps ...predicate.ProductionBatch) *ProductionBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProductionBatchUpdate) SetTenantID(v uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableTenantID(v *uuid.UUID) *ProductionBatchUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *ProductionBatchUpdate) SetOutletID(v uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableOutletID(v *uuid.UUID) *ProductionBatchUpdate {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// ClearOutletID clears the value of the "outlet_id" field.
func (_u *ProductionBatchUpdate) ClearOutletID() *ProductionBatchUpdate {
	_u.mutation.ClearOutletID()
	return _u
}

// SetBatchNumber sets the "batch_number" field.
func (_u *ProductionBatchUpdate) SetBatchNumber(v string) *ProductionBatchUpdate {
	_u.mutation.SetBatchNumber(v)
	return _u
}

// SetNillableBatchNumber sets the "batch_number" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableBatchNumber(v *string) *ProductionBatchUpdate {
	if v != nil {
		_u.SetBatchNumber(*v)
	}
	return _u
}

// SetRecipeID sets the "recipe_id" field.
func (_u *ProductionBatchUpdate) SetRecipeID(v uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.SetRecipeID(v)
	return _u
}

// SetNillableRecipeID sets the "recipe_id" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableRecipeID(v *uuid.UUID) *ProductionBatchUpdate {
	if v != nil {
		_u.SetRecipeID(*v)
	}
	return _u
}

// SetScheduledDate sets the "scheduled_date" field.
func (_u *ProductionBatchUpdate) SetScheduledDate(v time.Time) *ProductionBatchUpdate {
	_u.mutation.SetScheduledDate(v)
	return _u
}

// SetNillableScheduledDate sets the "scheduled_date" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableScheduledDate(v *time.Time) *ProductionBatchUpdate {
	if v != nil {
		_u.SetScheduledDate(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProductionBatchUpdate) SetStartDate(v time.Time) *ProductionBatchUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableStartDate(v *time.Time) *ProductionBatchUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ProductionBatchUpdate) ClearStartDate() *ProductionBatchUpdate {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProductionBatchUpdate) SetEndDate(v time.Time) *ProductionBatchUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableEndDate(v *time.Time) *ProductionBatchUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ProductionBatchUpdate) ClearEndDate() *ProductionBatchUpdate {
	_u.mutation.ClearEndDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductionBatchUpdate) SetStatus(v productionbatch.Status) *ProductionBatchUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableStatus(v *productionbatch.Status) *ProductionBatchUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *ProductionBatchUpdate) SetPlannedQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillablePlannedQuantity(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *ProductionBatchUpdate) AddPlannedQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// SetActualQuantity sets the "actual_quantity" field.
func (_u *ProductionBatchUpdate) SetActualQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetActualQuantity()
	_u.mutation.SetActualQuantity(v)
	return _u
}

// SetNillableActualQuantity sets the "actual_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableActualQuantity(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetActualQuantity(*v)
	}
	return _u
}

// AddActualQuantity adds value to the "actual_quantity" field.
func (_u *ProductionBatchUpdate) AddActualQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.AddActualQuantity(v)
	return _u
}

// ClearActualQuantity clears the value of the "actual_quantity" field.
func (_u *ProductionBatchUpdate) ClearActualQuantity() *ProductionBatchUpdate {
	_u.mutation.ClearActualQuantity()
	return _u
}

// SetLaborCost sets the "labor_cost" field.
func (_u *ProductionBatchUpdate) SetLaborCost(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetLaborCost()
	_u.mutation.SetLaborCost(v)
	return _u
}

// SetNillableLaborCost sets the "labor_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableLaborCost(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetLaborCost(*v)
	}
	return _u
}

// AddLaborCost adds value to the "labor_cost" field.
func (_u *ProductionBatchUpdate) AddLaborCost(v float64) *ProductionBatchUpdate {
	_u.mutation.AddLaborCost(v)
	return _u
}

// SetOverheadCost sets the "overhead_cost" field.
func (_u *ProductionBatchUpdate) SetOverheadCost(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetOverheadCost()
	_u.mutation.SetOverheadCost(v)
	return _u
}

// SetNillableOverheadCost sets the "overhead_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableOverheadCost(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetOverheadCost(*v)
	}
	return _u
}

// AddOverheadCost adds value to the "overhead_cost" field.
func (_u *ProductionBatchUpdate) AddOverheadCost(v float64) *ProductionBatchUpdate {
	_u.mutation.AddOverheadCost(v)
	return _u
}

// SetScrapQuantity sets the "scrap_quantity" field.
func (_u *ProductionBatchUpdate) SetScrapQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetScrapQuantity()
	_u.mutation.SetScrapQuantity(v)
	return _u
}

// SetNillableScrapQuantity sets the "scrap_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableScrapQuantity(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetScrapQuantity(*v)
	}
	return _u
}

// AddScrapQuantity adds value to the "scrap_quantity" field.
func (_u *ProductionBatchUpdate) AddScrapQuantity(v float64) *ProductionBatchUpdate {
	_u.mutation.AddScrapQuantity(v)
	return _u
}

// SetUnitCost sets the "unit_cost" field.
func (_u *ProductionBatchUpdate) SetUnitCost(v float64) *ProductionBatchUpdate {
	_u.mutation.ResetUnitCost()
	_u.mutation.SetUnitCost(v)
	return _u
}

// SetNillableUnitCost sets the "unit_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableUnitCost(v *float64) *ProductionBatchUpdate {
	if v != nil {
		_u.SetUnitCost(*v)
	}
	return _u
}

// AddUnitCost adds value to the "unit_cost" field.
func (_u *ProductionBatchUpdate) AddUnitCost(v float64) *ProductionBatchUpdate {
	_u.mutation.AddUnitCost(v)
	return _u
}

// ClearUnitCost clears the value of the "unit_cost" field.
func (_u *ProductionBatchUpdate) ClearUnitCost() *ProductionBatchUpdate {
	_u.mutation.ClearUnitCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProductionBatchUpdate) SetNotes(v string) *ProductionBatchUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableNotes(v *string) *ProductionBatchUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProductionBatchUpdate) ClearNotes() *ProductionBatchUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductionBatchUpdate) SetCreatedBy(v uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableCreatedBy(v *uuid.UUID) *ProductionBatchUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductionBatchUpdate) ClearCreatedBy() *ProductionBatchUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetSupervisorID sets the "supervisor_id" field.
func (_u *ProductionBatchUpdate) SetSupervisorID(v uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.SetSupervisorID(v)
	return _u
}

// SetNillableSupervisorID sets the "supervisor_id" field if the given value is not nil.
func (_u *ProductionBatchUpdate) SetNillableSupervisorID(v *uuid.UUID) *ProductionBatchUpdate {
	if v != nil {
		_u.SetSupervisorID(*v)
	}
	return _u
}

// ClearSupervisorID clears the value of the "supervisor_id" field.
func (_u *ProductionBatchUpdate) ClearSupervisorID() *ProductionBatchUpdate {
	_u.mutation.ClearSupervisorID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductionBatchUpdate) SetUpdatedAt(v time.Time) *ProductionBatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRawMaterialIDs adds the "raw_materials" edge to the BatchRawMaterial entity by IDs.
func (_u *ProductionBatchUpdate) AddRawMaterialIDs(ids ...uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.AddRawMaterialIDs(ids...)
	return _u
}

// AddRawMaterials adds the "raw_materials" edges to the BatchRawMaterial entity.
func (_u *ProductionBatchUpdate) AddRawMaterials(v ...*BatchRawMaterial) *ProductionBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawMaterialIDs(ids...)
}

// AddQualityCheckIDs adds the "quality_checks" edge to the QualityCheck entity by IDs.
func (_u *ProductionBatchUpdate) AddQualityCheckIDs(ids ...uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.AddQualityCheckIDs(ids...)
	return _u
}

// AddQualityChecks adds the "quality_checks" edges to the QualityCheck entity.
func (_u *ProductionBatchUpdate) AddQualityChecks(v ...*QualityCheck) *ProductionBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQualityCheckIDs(ids...)
}

// Mutation returns the ProductionBatchMutation object of the builder.
func (_u *ProductionBatchUpdate) Mutation() *ProductionBatchMutation {
	return _u.mutation
}

// ClearRawMaterials clears all "raw_materials" edges to the BatchRawMaterial entity.
func (_u *ProductionBatchUpdate) ClearRawMaterials() *ProductionBatchUpdate {
	_u.mutation.ClearRawMaterials()
	return _u
}

// RemoveRawMaterialIDs removes the "raw_materials" edge to BatchRawMaterial entities by IDs.
func (_u *ProductionBatchUpdate) RemoveRawMaterialIDs(ids ...uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.RemoveRawMaterialIDs(ids...)
	return _u
}

// RemoveRawMaterials removes "raw_materials" edges to BatchRawMaterial entities.
func (_u *ProductionBatchUpdate) RemoveRawMaterials(v ...*BatchRawMaterial) *ProductionBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawMaterialIDs(ids...)
}

// ClearQualityChecks clears all "quality_checks" edges to the QualityCheck entity.
func (_u *ProductionBatchUpdate) ClearQualityChecks() *ProductionBatchUpdate {
	_u.mutation.ClearQualityChecks()
	return _u
}

// RemoveQualityCheckIDs removes the "quality_checks" edge to QualityCheck entities by IDs.
func (_u *ProductionBatchUpdate) RemoveQualityCheckIDs(ids ...uuid.UUID) *ProductionBatchUpdate {
	_u.mutation.RemoveQualityCheckIDs(ids...)
	return _u
}

// RemoveQualityChecks removes "quality_checks" edges to QualityCheck entities.
func (_u *ProductionBatchUpdate) RemoveQualityChecks(v ...*QualityCheck) *ProductionBatchUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQualityCheckIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductionBatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductionBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductionBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductionBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductionBatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productionbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductionBatchUpdate) check() error {
	if v, ok := _u.mutation.BatchNumber(); ok {
		if err := productionbatch.BatchNumberValidator(v); err != nil {
			return &ValidationError{Name: "batch_number", err: fmt.Errorf(`ent: validator failed for field "ProductionBatch.batch_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := productionbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductionBatch.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductionBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productionbatch.Table, productionbatch.Columns, sqlgraph.NewFieldSpec(productionbatch.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(productionbatch.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(productionbatch.FieldOutletID, field.TypeUUID, value)
	}
	if _u.mutation.OutletIDCleared() {
		_spec.ClearField(productionbatch.FieldOutletID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BatchNumber(); ok {
		_spec.SetField(productionbatch.FieldBatchNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipeID(); ok {
		_spec.SetField(productionbatch.FieldRecipeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ScheduledDate(); ok {
		_spec.SetField(productionbatch.FieldScheduledDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(productionbatch.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(productionbatch.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(productionbatch.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(productionbatch.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productionbatch.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(productionbatch.FieldPlannedQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(productionbatch.FieldPlannedQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualQuantity(); ok {
		_spec.SetField(productionbatch.FieldActualQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualQuantity(); ok {
		_spec.AddField(productionbatch.FieldActualQuantity, field.TypeFloat64, value)
	}
	if _u.mutation.ActualQuantityCleared() {
		_spec.ClearField(productionbatch.FieldActualQuantity, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LaborCost(); ok {
		_spec.SetField(productionbatch.FieldLaborCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLaborCost(); ok {
		_spec.AddField(productionbatch.FieldLaborCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OverheadCost(); ok {
		_spec.SetField(productionbatch.FieldOverheadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOverheadCost(); ok {
		_spec.AddField(productionbatch.FieldOverheadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ScrapQuantity(); ok {
		_spec.SetField(productionbatch.FieldScrapQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScrapQuantity(); ok {
		_spec.AddField(productionbatch.FieldScrapQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitCost(); ok {
		_spec.SetField(productionbatch.FieldUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitCost(); ok {
		_spec.AddField(productionbatch.FieldUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UnitCostCleared() {
		_spec.ClearField(productionbatch.FieldUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(productionbatch.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(productionbatch.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(productionbatch.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(productionbatch.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.SupervisorID(); ok {
		_spec.SetField(productionbatch.FieldSupervisorID, field.TypeUUID, value)
	}
	if _u.mutation.SupervisorIDCleared() {
		_spec.ClearField(productionbatch.FieldSupervisorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productionbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RawMaterialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawMaterialsIDs(); len(nodes) > 0 && !_u.mutation.RawMaterialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawMaterialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QualityChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQualityChecksIDs(); len(nodes) > 0 && !_u.mutation.QualityChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QualityChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productionbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductionBatchUpdateOne is the builder for updating a single ProductionBatch entity.
type ProductionBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductionBatchMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *ProductionBatchUpdateOne) SetTenantID(v uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableTenantID(v *uuid.UUID) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *ProductionBatchUpdateOne) SetOutletID(v uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableOutletID(v *uuid.UUID) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// ClearOutletID clears the value of the "outlet_id" field.
func (_u *ProductionBatchUpdateOne) ClearOutletID() *ProductionBatchUpdateOne {
	_u.mutation.ClearOutletID()
	return _u
}

// SetBatchNumber sets the "batch_number" field.
func (_u *ProductionBatchUpdateOne) SetBatchNumber(v string) *ProductionBatchUpdateOne {
	_u.mutation.SetBatchNumber(v)
	return _u
}

// SetNillableBatchNumber sets the "batch_number" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableBatchNumber(v *string) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetBatchNumber(*v)
	}
	return _u
}

// SetRecipeID sets the "recipe_id" field.
func (_u *ProductionBatchUpdateOne) SetRecipeID(v uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.SetRecipeID(v)
	return _u
}

// SetNillableRecipeID sets the "recipe_id" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableRecipeID(v *uuid.UUID) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetRecipeID(*v)
	}
	return _u
}

// SetScheduledDate sets the "scheduled_date" field.
func (_u *ProductionBatchUpdateOne) SetScheduledDate(v time.Time) *ProductionBatchUpdateOne {
	_u.mutation.SetScheduledDate(v)
	return _u
}

// SetNillableScheduledDate sets the "scheduled_date" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableScheduledDate(v *time.Time) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetScheduledDate(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *ProductionBatchUpdateOne) SetStartDate(v time.Time) *ProductionBatchUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableStartDate(v *time.Time) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// ClearStartDate clears the value of the "start_date" field.
func (_u *ProductionBatchUpdateOne) ClearStartDate() *ProductionBatchUpdateOne {
	_u.mutation.ClearStartDate()
	return _u
}

// SetEndDate sets the "end_date" field.
func (_u *ProductionBatchUpdateOne) SetEndDate(v time.Time) *ProductionBatchUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableEndDate(v *time.Time) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// ClearEndDate clears the value of the "end_date" field.
func (_u *ProductionBatchUpdateOne) ClearEndDate() *ProductionBatchUpdateOne {
	_u.mutation.ClearEndDate()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProductionBatchUpdateOne) SetStatus(v productionbatch.Status) *ProductionBatchUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableStatus(v *productionbatch.Status) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPlannedQuantity sets the "planned_quantity" field.
func (_u *ProductionBatchUpdateOne) SetPlannedQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetPlannedQuantity()
	_u.mutation.SetPlannedQuantity(v)
	return _u
}

// SetNillablePlannedQuantity sets the "planned_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillablePlannedQuantity(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetPlannedQuantity(*v)
	}
	return _u
}

// AddPlannedQuantity adds value to the "planned_quantity" field.
func (_u *ProductionBatchUpdateOne) AddPlannedQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddPlannedQuantity(v)
	return _u
}

// SetActualQuantity sets the "actual_quantity" field.
func (_u *ProductionBatchUpdateOne) SetActualQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetActualQuantity()
	_u.mutation.SetActualQuantity(v)
	return _u
}

// SetNillableActualQuantity sets the "actual_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableActualQuantity(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetActualQuantity(*v)
	}
	return _u
}

// AddActualQuantity adds value to the "actual_quantity" field.
func (_u *ProductionBatchUpdateOne) AddActualQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddActualQuantity(v)
	return _u
}

// ClearActualQuantity clears the value of the "actual_quantity" field.
func (_u *ProductionBatchUpdateOne) ClearActualQuantity() *ProductionBatchUpdateOne {
	_u.mutation.ClearActualQuantity()
	return _u
}

// SetLaborCost sets the "labor_cost" field.
func (_u *ProductionBatchUpdateOne) SetLaborCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetLaborCost()
	_u.mutation.SetLaborCost(v)
	return _u
}

// SetNillableLaborCost sets the "labor_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableLaborCost(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetLaborCost(*v)
	}
	return _u
}

// AddLaborCost adds value to the "labor_cost" field.
func (_u *ProductionBatchUpdateOne) AddLaborCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddLaborCost(v)
	return _u
}

// SetOverheadCost sets the "overhead_cost" field.
func (_u *ProductionBatchUpdateOne) SetOverheadCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetOverheadCost()
	_u.mutation.SetOverheadCost(v)
	return _u
}

// SetNillableOverheadCost sets the "overhead_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableOverheadCost(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetOverheadCost(*v)
	}
	return _u
}

// AddOverheadCost adds value to the "overhead_cost" field.
func (_u *ProductionBatchUpdateOne) AddOverheadCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddOverheadCost(v)
	return _u
}

// SetScrapQuantity sets the "scrap_quantity" field.
func (_u *ProductionBatchUpdateOne) SetScrapQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetScrapQuantity()
	_u.mutation.SetScrapQuantity(v)
	return _u
}

// SetNillableScrapQuantity sets the "scrap_quantity" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableScrapQuantity(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetScrapQuantity(*v)
	}
	return _u
}

// AddScrapQuantity adds value to the "scrap_quantity" field.
func (_u *ProductionBatchUpdateOne) AddScrapQuantity(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddScrapQuantity(v)
	return _u
}

// SetUnitCost sets the "unit_cost" field.
func (_u *ProductionBatchUpdateOne) SetUnitCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.ResetUnitCost()
	_u.mutation.SetUnitCost(v)
	return _u
}

// SetNillableUnitCost sets the "unit_cost" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableUnitCost(v *float64) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetUnitCost(*v)
	}
	return _u
}

// AddUnitCost adds value to the "unit_cost" field.
func (_u *ProductionBatchUpdateOne) AddUnitCost(v float64) *ProductionBatchUpdateOne {
	_u.mutation.AddUnitCost(v)
	return _u
}

// ClearUnitCost clears the value of the "unit_cost" field.
func (_u *ProductionBatchUpdateOne) ClearUnitCost() *ProductionBatchUpdateOne {
	_u.mutation.ClearUnitCost()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *ProductionBatchUpdateOne) SetNotes(v string) *ProductionBatchUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableNotes(v *string) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *ProductionBatchUpdateOne) ClearNotes() *ProductionBatchUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProductionBatchUpdateOne) SetCreatedBy(v uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProductionBatchUpdateOne) ClearCreatedBy() *ProductionBatchUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetSupervisorID sets the "supervisor_id" field.
func (_u *ProductionBatchUpdateOne) SetSupervisorID(v uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.SetSupervisorID(v)
	return _u
}

// SetNillableSupervisorID sets the "supervisor_id" field if the given value is not nil.
func (_u *ProductionBatchUpdateOne) SetNillableSupervisorID(v *uuid.UUID) *ProductionBatchUpdateOne {
	if v != nil {
		_u.SetSupervisorID(*v)
	}
	return _u
}

// ClearSupervisorID clears the value of the "supervisor_id" field.
func (_u *ProductionBatchUpdateOne) ClearSupervisorID() *ProductionBatchUpdateOne {
	_u.mutation.ClearSupervisorID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProductionBatchUpdateOne) SetUpdatedAt(v time.Time) *ProductionBatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRawMaterialIDs adds the "raw_materials" edge to the BatchRawMaterial entity by IDs.
func (_u *ProductionBatchUpdateOne) AddRawMaterialIDs(ids ...uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.AddRawMaterialIDs(ids...)
	return _u
}

// AddRawMaterials adds the "raw_materials" edges to the BatchRawMaterial entity.
func (_u *ProductionBatchUpdateOne) AddRawMaterials(v ...*BatchRawMaterial) *ProductionBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRawMaterialIDs(ids...)
}

// AddQualityCheckIDs adds the "quality_checks" edge to the QualityCheck entity by IDs.
func (_u *ProductionBatchUpdateOne) AddQualityCheckIDs(ids ...uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.AddQualityCheckIDs(ids...)
	return _u
}

// AddQualityChecks adds the "quality_checks" edges to the QualityCheck entity.
func (_u *ProductionBatchUpdateOne) AddQualityChecks(v ...*QualityCheck) *ProductionBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQualityCheckIDs(ids...)
}

// Mutation returns the ProductionBatchMutation object of the builder.
func (_u *ProductionBatchUpdateOne) Mutation() *ProductionBatchMutation {
	return _u.mutation
}

// ClearRawMaterials clears all "raw_materials" edges to the BatchRawMaterial entity.
func (_u *ProductionBatchUpdateOne) ClearRawMaterials() *ProductionBatchUpdateOne {
	_u.mutation.ClearRawMaterials()
	return _u
}

// RemoveRawMaterialIDs removes the "raw_materials" edge to BatchRawMaterial entities by IDs.
func (_u *ProductionBatchUpdateOne) RemoveRawMaterialIDs(ids ...uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.RemoveRawMaterialIDs(ids...)
	return _u
}

// RemoveRawMaterials removes "raw_materials" edges to BatchRawMaterial entities.
func (_u *ProductionBatchUpdateOne) RemoveRawMaterials(v ...*BatchRawMaterial) *ProductionBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRawMaterialIDs(ids...)
}

// ClearQualityChecks clears all "quality_checks" edges to the QualityCheck entity.
func (_u *ProductionBatchUpdateOne) ClearQualityChecks() *ProductionBatchUpdateOne {
	_u.mutation.ClearQualityChecks()
	return _u
}

// RemoveQualityCheckIDs removes the "quality_checks" edge to QualityCheck entities by IDs.
func (_u *ProductionBatchUpdateOne) RemoveQualityCheckIDs(ids ...uuid.UUID) *ProductionBatchUpdateOne {
	_u.mutation.RemoveQualityCheckIDs(ids...)
	return _u
}

// RemoveQualityChecks removes "quality_checks" edges to QualityCheck entities.
func (_u *ProductionBatchUpdateOne) RemoveQualityChecks(v ...*QualityCheck) *ProductionBatchUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQualityCheckIDs(ids...)
}

// Where appends a list predicates to the ProductionBatchUpdate builder.
func (_u *ProductionBatchUpdateOne) Where(ps ...predicate.ProductionBatch) *ProductionBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductionBatchUpdateOne) Select(field string, fields ...string) *ProductionBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductionBatch entity.
func (_u *ProductionBatchUpdateOne) Save(ctx context.Context) (*ProductionBatch, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductionBatchUpdateOne) SaveX(ctx context.Context) *ProductionBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductionBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductionBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProductionBatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := productionbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductionBatchUpdateOne) check() error {
	if v, ok := _u.mutation.BatchNumber(); ok {
		if err := productionbatch.BatchNumberValidator(v); err != nil {
			return &ValidationError{Name: "batch_number", err: fmt.Errorf(`ent: validator failed for field "ProductionBatch.batch_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := productionbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ProductionBatch.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ProductionBatchUpdateOne) sqlSave(ctx context.Context) (_node *ProductionBatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productionbatch.Table, productionbatch.Columns, sqlgraph.NewFieldSpec(productionbatch.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductionBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productionbatch.FieldID)
		for _, f := range fields {
			if !productionbatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productionbatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(productionbatch.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(productionbatch.FieldOutletID, field.TypeUUID, value)
	}
	if _u.mutation.OutletIDCleared() {
		_spec.ClearField(productionbatch.FieldOutletID, field.TypeUUID)
	}
	if value, ok := _u.mutation.BatchNumber(); ok {
		_spec.SetField(productionbatch.FieldBatchNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.RecipeID(); ok {
		_spec.SetField(productionbatch.FieldRecipeID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ScheduledDate(); ok {
		_spec.SetField(productionbatch.FieldScheduledDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(productionbatch.FieldStartDate, field.TypeTime, value)
	}
	if _u.mutation.StartDateCleared() {
		_spec.ClearField(productionbatch.FieldStartDate, field.TypeTime)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(productionbatch.FieldEndDate, field.TypeTime, value)
	}
	if _u.mutation.EndDateCleared() {
		_spec.ClearField(productionbatch.FieldEndDate, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(productionbatch.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PlannedQuantity(); ok {
		_spec.SetField(productionbatch.FieldPlannedQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPlannedQuantity(); ok {
		_spec.AddField(productionbatch.FieldPlannedQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualQuantity(); ok {
		_spec.SetField(productionbatch.FieldActualQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualQuantity(); ok {
		_spec.AddField(productionbatch.FieldActualQuantity, field.TypeFloat64, value)
	}
	if _u.mutation.ActualQuantityCleared() {
		_spec.ClearField(productionbatch.FieldActualQuantity, field.TypeFloat64)
	}
	if value, ok := _u.mutation.LaborCost(); ok {
		_spec.SetField(productionbatch.FieldLaborCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLaborCost(); ok {
		_spec.AddField(productionbatch.FieldLaborCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OverheadCost(); ok {
		_spec.SetField(productionbatch.FieldOverheadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOverheadCost(); ok {
		_spec.AddField(productionbatch.FieldOverheadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ScrapQuantity(); ok {
		_spec.SetField(productionbatch.FieldScrapQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScrapQuantity(); ok {
		_spec.AddField(productionbatch.FieldScrapQuantity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UnitCost(); ok {
		_spec.SetField(productionbatch.FieldUnitCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUnitCost(); ok {
		_spec.AddField(productionbatch.FieldUnitCost, field.TypeFloat64, value)
	}
	if _u.mutation.UnitCostCleared() {
		_spec.ClearField(productionbatch.FieldUnitCost, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(productionbatch.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(productionbatch.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(productionbatch.FieldCreatedBy, field.TypeUUID, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(productionbatch.FieldCreatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.SupervisorID(); ok {
		_spec.SetField(productionbatch.FieldSupervisorID, field.TypeUUID, value)
	}
	if _u.mutation.SupervisorIDCleared() {
		_spec.ClearField(productionbatch.FieldSupervisorID, field.TypeUUID)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(productionbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RawMaterialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRawMaterialsIDs(); len(nodes) > 0 && !_u.mutation.RawMaterialsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RawMaterialsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.RawMaterialsTable,
			Columns: []string{productionbatch.RawMaterialsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(batchrawmaterial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QualityChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQualityChecksIDs(); len(nodes) > 0 && !_u.mutation.QualityChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QualityChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   productionbatch.QualityChecksTable,
			Columns: []string{productionbatch.QualityChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(qualitycheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductionBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productionbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
