// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/ratelimitconfig"
	"github.com/google/uuid"
)

// RateLimitConfigCreate is the builder for creating a RateLimitConfig entity.
type RateLimitConfigCreate struct {
	config
	mutation *RateLimitConfigMutation
	hooks    []Hook
}

// SetServiceName sets the "service_name" field.
func (_c *RateLimitConfigCreate) SetServiceName(v string) *RateLimitConfigCreate {
	_c.mutation.SetServiceName(v)
	return _c
}

// SetKeyType sets the "key_type" field.
func (_c *RateLimitConfigCreate) SetKeyType(v string) *RateLimitConfigCreate {
	_c.mutation.SetKeyType(v)
	return _c
}

// SetEndpointPattern sets the "endpoint_pattern" field.
func (_c *RateLimitConfigCreate) SetEndpointPattern(v string) *RateLimitConfigCreate {
	_c.mutation.SetEndpointPattern(v)
	return _c
}

// SetNillableEndpointPattern sets the "endpoint_pattern" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableEndpointPattern(v *string) *RateLimitConfigCreate {
	if v != nil {
		_c.SetEndpointPattern(*v)
	}
	return _c
}

// SetRequestsPerWindow sets the "requests_per_window" field.
func (_c *RateLimitConfigCreate) SetRequestsPerWindow(v int) *RateLimitConfigCreate {
	_c.mutation.SetRequestsPerWindow(v)
	return _c
}

// SetNillableRequestsPerWindow sets the "requests_per_window" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableRequestsPerWindow(v *int) *RateLimitConfigCreate {
	if v != nil {
		_c.SetRequestsPerWindow(*v)
	}
	return _c
}

// SetWindowSeconds sets the "window_seconds" field.
func (_c *RateLimitConfigCreate) SetWindowSeconds(v int) *RateLimitConfigCreate {
	_c.mutation.SetWindowSeconds(v)
	return _c
}

// SetNillableWindowSeconds sets the "window_seconds" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableWindowSeconds(v *int) *RateLimitConfigCreate {
	if v != nil {
		_c.SetWindowSeconds(*v)
	}
	return _c
}

// SetBurstMultiplier sets the "burst_multiplier" field.
func (_c *RateLimitConfigCreate) SetBurstMultiplier(v float64) *RateLimitConfigCreate {
	_c.mutation.SetBurstMultiplier(v)
	return _c
}

// SetNillableBurstMultiplier sets the "burst_multiplier" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableBurstMultiplier(v *float64) *RateLimitConfigCreate {
	if v != nil {
		_c.SetBurstMultiplier(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *RateLimitConfigCreate) SetIsActive(v bool) *RateLimitConfigCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableIsActive(v *bool) *RateLimitConfigCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RateLimitConfigCreate) SetDescription(v string) *RateLimitConfigCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableDescription(v *string) *RateLimitConfigCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RateLimitConfigCreate) SetCreatedAt(v time.Time) *RateLimitConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableCreatedAt(v *time.Time) *RateLimitConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RateLimitConfigCreate) SetUpdatedAt(v time.Time) *RateLimitConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableUpdatedAt(v *time.Time) *RateLimitConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RateLimitConfigCreate) SetID(v uuid.UUID) *RateLimitConfigCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RateLimitConfigCreate) SetNillableID(v *uuid.UUID) *RateLimitConfigCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the RateLimitConfigMutation object of the builder.
func (_c *RateLimitConfigCreate) Mutation() *RateLimitConfigMutation {
	return _c.mutation
}

// Save creates the RateLimitConfig in the database.
func (_c *RateLimitConfigCreate) Save(ctx context.Context) (*RateLimitConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RateLimitConfigCreate) SaveX(ctx context.Context) *RateLimitConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RateLimitConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RateLimitConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RateLimitConfigCreate) defaults() {
	if _, ok := _c.mutation.EndpointPattern(); !ok {
		v := ratelimitconfig.DefaultEndpointPattern
		_c.mutation.SetEndpointPattern(v)
	}
	if _, ok := _c.mutation.RequestsPerWindow(); !ok {
		v := ratelimitconfig.DefaultRequestsPerWindow
		_c.mutation.SetRequestsPerWindow(v)
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		v := ratelimitconfig.DefaultWindowSeconds
		_c.mutation.SetWindowSeconds(v)
	}
	if _, ok := _c.mutation.BurstMultiplier(); !ok {
		v := ratelimitconfig.DefaultBurstMultiplier
		_c.mutation.SetBurstMultiplier(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := ratelimitconfig.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ratelimitconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ratelimitconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ratelimitconfig.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RateLimitConfigCreate) check() error {
	if _, ok := _c.mutation.ServiceName(); !ok {
		return &ValidationError{Name: "service_name", err: errors.New(`ent: missing required field "RateLimitConfig.service_name"`)}
	}
	if v, ok := _c.mutation.ServiceName(); ok {
		if err := ratelimitconfig.ServiceNameValidator(v); err != nil {
			return &ValidationError{Name: "service_name", err: fmt.Errorf(`ent: validator failed for field "RateLimitConfig.service_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyType(); !ok {
		return &ValidationError{Name: "key_type", err: errors.New(`ent: missing required field "RateLimitConfig.key_type"`)}
	}
	if v, ok := _c.mutation.KeyType(); ok {
		if err := ratelimitconfig.KeyTypeValidator(v); err != nil {
			return &ValidationError{Name: "key_type", err: fmt.Errorf(`ent: validator failed for field "RateLimitConfig.key_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EndpointPattern(); !ok {
		return &ValidationError{Name: "endpoint_pattern", err: errors.New(`ent: missing required field "RateLimitConfig.endpoint_pattern"`)}
	}
	if _, ok := _c.mutation.RequestsPerWindow(); !ok {
		return &ValidationError{Name: "requests_per_window", err: errors.New(`ent: missing required field "RateLimitConfig.requests_per_window"`)}
	}
	if v, ok := _c.mutation.RequestsPerWindow(); ok {
		if err := ratelimitconfig.RequestsPerWindowValidator(v); err != nil {
			return &ValidationError{Name: "requests_per_window", err: fmt.Errorf(`ent: validator failed for field "RateLimitConfig.requests_per_window": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WindowSeconds(); !ok {
		return &ValidationError{Name: "window_seconds", err: errors.New(`ent: missing required field "RateLimitConfig.window_seconds"`)}
	}
	if v, ok := _c.mutation.WindowSeconds(); ok {
		if err := ratelimitconfig.WindowSecondsValidator(v); err != nil {
			return &ValidationError{Name: "window_seconds", err: fmt.Errorf(`ent: validator failed for field "RateLimitConfig.window_seconds": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BurstMultiplier(); !ok {
		return &ValidationError{Name: "burst_multiplier", err: errors.New(`ent: missing required field "RateLimitConfig.burst_multiplier"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "RateLimitConfig.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RateLimitConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RateLimitConfig.updated_at"`)}
	}
	return nil
}

func (_c *RateLimitConfigCreate) sqlSave(ctx context.Context) (*RateLimitConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RateLimitConfigCreate) createSpec() (*RateLimitConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &RateLimitConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ratelimitconfig.Table, sqlgraph.NewFieldSpec(ratelimitconfig.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ServiceName(); ok {
		_spec.SetField(ratelimitconfig.FieldServiceName, field.TypeString, value)
		_node.ServiceName = value
	}
	if value, ok := _c.mutation.KeyType(); ok {
		_spec.SetField(ratelimitconfig.FieldKeyType, field.TypeString, value)
		_node.KeyType = value
	}
	if value, ok := _c.mutation.EndpointPattern(); ok {
		_spec.SetField(ratelimitconfig.FieldEndpointPattern, field.TypeString, value)
		_node.EndpointPattern = value
	}
	if value, ok := _c.mutation.RequestsPerWindow(); ok {
		_spec.SetField(ratelimitconfig.FieldRequestsPerWindow, field.TypeInt, value)
		_node.RequestsPerWindow = value
	}
	if value, ok := _c.mutation.WindowSeconds(); ok {
		_spec.SetField(ratelimitconfig.FieldWindowSeconds, field.TypeInt, value)
		_node.WindowSeconds = value
	}
	if value, ok := _c.mutation.BurstMultiplier(); ok {
		_spec.SetField(ratelimitconfig.FieldBurstMultiplier, field.TypeFloat64, value)
		_node.BurstMultiplier = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(ratelimitconfig.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(ratelimitconfig.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ratelimitconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimitconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RateLimitConfigCreateBulk is the builder for creating many RateLimitConfig entities in bulk.
type RateLimitConfigCreateBulk struct {
	config
	err      error
	builders []*RateLimitConfigCreate
}

// Save creates the RateLimitConfig entities in the database.
func (_c *RateLimitConfigCreateBulk) Save(ctx context.Context) ([]*RateLimitConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RateLimitConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RateLimitConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RateLimitConfigCreateBulk) SaveX(ctx context.Context) []*RateLimitConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RateLimitConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RateLimitConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
