// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/inventory-service/internal/ent/requisition"
	"github.com/bengobox/inventory-service/internal/ent/requisitionline"
	"github.com/google/uuid"
)

// RequisitionLine is the model entity for the RequisitionLine schema.
type RequisitionLine struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Owning tenant
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// FK to Requisition
	RequisitionID uuid.UUID `json:"requisition_id,omitempty"`
	// ItemType holds the value of the "item_type" field.
	ItemType requisitionline.ItemType `json:"item_type,omitempty"`
	// FK to Item (inventory type)
	ItemID *uuid.UUID `json:"item_id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// ApprovedQuantity holds the value of the "approved_quantity" field.
	ApprovedQuantity *int `json:"approved_quantity,omitempty"`
	// Urgent holds the value of the "urgent" field.
	Urgent bool `json:"urgent,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Specifications holds the value of the "specifications" field.
	Specifications string `json:"specifications,omitempty"`
	// EstimatedPrice holds the value of the "estimated_price" field.
	EstimatedPrice *float64 `json:"estimated_price,omitempty"`
	// Preferred supplier (external/service)
	SupplierID *uuid.UUID `json:"supplier_id,omitempty"`
	// ServiceDescription holds the value of the "service_description" field.
	ServiceDescription string `json:"service_description,omitempty"`
	// ExpectedDeliverables holds the value of the "expected_deliverables" field.
	ExpectedDeliverables string `json:"expected_deliverables,omitempty"`
	// Duration holds the value of the "duration" field.
	Duration string `json:"duration,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate *time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate *time.Time `json:"end_date,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequisitionLineQuery when eager-loading is set.
	Edges        RequisitionLineEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequisitionLineEdges holds the relations/edges for other nodes in the graph.
type RequisitionLineEdges struct {
	// Requisition holds the value of the requisition edge.
	Requisition *Requisition `json:"requisition,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequisitionOrErr returns the Requisition value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequisitionLineEdges) RequisitionOrErr() (*Requisition, error) {
	if e.Requisition != nil {
		return e.Requisition, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: requisition.Label}
	}
	return nil, &NotLoadedError{edge: "requisition"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequisitionLine) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requisitionline.FieldItemID, requisitionline.FieldSupplierID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case requisitionline.FieldUrgent:
			values[i] = new(sql.NullBool)
		case requisitionline.FieldEstimatedPrice:
			values[i] = new(sql.NullFloat64)
		case requisitionline.FieldQuantity, requisitionline.FieldApprovedQuantity:
			values[i] = new(sql.NullInt64)
		case requisitionline.FieldItemType, requisitionline.FieldDescription, requisitionline.FieldSpecifications, requisitionline.FieldServiceDescription, requisitionline.FieldExpectedDeliverables, requisitionline.FieldDuration:
			values[i] = new(sql.NullString)
		case requisitionline.FieldStartDate, requisitionline.FieldEndDate, requisitionline.FieldCreatedAt, requisitionline.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case requisitionline.FieldID, requisitionline.FieldTenantID, requisitionline.FieldRequisitionID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequisitionLine fields.
func (_m *RequisitionLine) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requisitionline.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case requisitionline.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case requisitionline.FieldRequisitionID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field requisition_id", values[i])
			} else if value != nil {
				_m.RequisitionID = *value
			}
		case requisitionline.FieldItemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_type", values[i])
			} else if value.Valid {
				_m.ItemType = requisitionline.ItemType(value.String)
			}
		case requisitionline.FieldItemID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = new(uuid.UUID)
				*_m.ItemID = *value.S.(*uuid.UUID)
			}
		case requisitionline.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case requisitionline.FieldApprovedQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field approved_quantity", values[i])
			} else if value.Valid {
				_m.ApprovedQuantity = new(int)
				*_m.ApprovedQuantity = int(value.Int64)
			}
		case requisitionline.FieldUrgent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field urgent", values[i])
			} else if value.Valid {
				_m.Urgent = value.Bool
			}
		case requisitionline.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case requisitionline.FieldSpecifications:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field specifications", values[i])
			} else if value.Valid {
				_m.Specifications = value.String
			}
		case requisitionline.FieldEstimatedPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_price", values[i])
			} else if value.Valid {
				_m.EstimatedPrice = new(float64)
				*_m.EstimatedPrice = value.Float64
			}
		case requisitionline.FieldSupplierID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field supplier_id", values[i])
			} else if value.Valid {
				_m.SupplierID = new(uuid.UUID)
				*_m.SupplierID = *value.S.(*uuid.UUID)
			}
		case requisitionline.FieldServiceDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_description", values[i])
			} else if value.Valid {
				_m.ServiceDescription = value.String
			}
		case requisitionline.FieldExpectedDeliverables:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expected_deliverables", values[i])
			} else if value.Valid {
				_m.ExpectedDeliverables = value.String
			}
		case requisitionline.FieldDuration:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				_m.Duration = value.String
			}
		case requisitionline.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				_m.StartDate = new(time.Time)
				*_m.StartDate = value.Time
			}
		case requisitionline.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				_m.EndDate = new(time.Time)
				*_m.EndDate = value.Time
			}
		case requisitionline.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requisitionline.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequisitionLine.
// This includes values selected through modifiers, order, etc.
func (_m *RequisitionLine) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequisition queries the "requisition" edge of the RequisitionLine entity.
func (_m *RequisitionLine) QueryRequisition() *RequisitionQuery {
	return NewRequisitionLineClient(_m.config).QueryRequisition(_m)
}

// Update returns a builder for updating this RequisitionLine.
// Note that you need to call RequisitionLine.Unwrap() before calling this method if this RequisitionLine
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequisitionLine) Update() *RequisitionLineUpdateOne {
	return NewRequisitionLineClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequisitionLine entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequisitionLine) Unwrap() *RequisitionLine {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequisitionLine is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequisitionLine) String() string {
	var builder strings.Builder
	builder.WriteString("RequisitionLine(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("requisition_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequisitionID))
	builder.WriteString(", ")
	builder.WriteString("item_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ItemType))
	builder.WriteString(", ")
	if v := _m.ItemID; v != nil {
		builder.WriteString("item_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	if v := _m.ApprovedQuantity; v != nil {
		builder.WriteString("approved_quantity=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("urgent=")
	builder.WriteString(fmt.Sprintf("%v", _m.Urgent))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("specifications=")
	builder.WriteString(_m.Specifications)
	builder.WriteString(", ")
	if v := _m.EstimatedPrice; v != nil {
		builder.WriteString("estimated_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SupplierID; v != nil {
		builder.WriteString("supplier_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("service_description=")
	builder.WriteString(_m.ServiceDescription)
	builder.WriteString(", ")
	builder.WriteString("expected_deliverables=")
	builder.WriteString(_m.ExpectedDeliverables)
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(_m.Duration)
	builder.WriteString(", ")
	if v := _m.StartDate; v != nil {
		builder.WriteString("start_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndDate; v != nil {
		builder.WriteString("end_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequisitionLines is a parsable slice of RequisitionLine.
type RequisitionLines []*RequisitionLine
