// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/bengobox/inventory-service/internal/ent/stocktransfer"
	"github.com/bengobox/inventory-service/internal/ent/stocktransferline"
	"github.com/google/uuid"
)

// StockTransferLineUpdate is the builder for updating StockTransferLine entities.
type StockTransferLineUpdate struct {
	config
	hooks    []Hook
	mutation *StockTransferLineMutation
}

// Where appends a list predicates to the StockTransferLineUpdate builder.
func (_u *StockTransferLineUpdate) Where(ps ...predicate.StockTransferLine) *StockTransferLineUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTransferID sets the "transfer_id" field.
func (_u *StockTransferLineUpdate) SetTransferID(v uuid.UUID) *StockTransferLineUpdate {
	_u.mutation.SetTransferID(v)
	return _u
}

// SetNillableTransferID sets the "transfer_id" field if the given value is not nil.
func (_u *StockTransferLineUpdate) SetNillableTransferID(v *uuid.UUID) *StockTransferLineUpdate {
	if v != nil {
		_u.SetTransferID(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *StockTransferLineUpdate) SetItemID(v uuid.UUID) *StockTransferLineUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *StockTransferLineUpdate) SetNillableItemID(v *uuid.UUID) *StockTransferLineUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetVariantID sets the "variant_id" field.
func (_u *StockTransferLineUpdate) SetVariantID(v uuid.UUID) *StockTransferLineUpdate {
	_u.mutation.SetVariantID(v)
	return _u
}

// SetNillableVariantID sets the "variant_id" field if the given value is not nil.
func (_u *StockTransferLineUpdate) SetNillableVariantID(v *uuid.UUID) *StockTransferLineUpdate {
	if v != nil {
		_u.SetVariantID(*v)
	}
	return _u
}

// ClearVariantID clears the value of the "variant_id" field.
func (_u *StockTransferLineUpdate) ClearVariantID() *StockTransferLineUpdate {
	_u.mutation.ClearVariantID()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *StockTransferLineUpdate) SetLotID(v uuid.UUID) *StockTransferLineUpdate {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *StockTransferLineUpdate) SetNillableLotID(v *uuid.UUID) *StockTransferLineUpdate {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *StockTransferLineUpdate) ClearLotID() *StockTransferLineUpdate {
	_u.mutation.ClearLotID()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *StockTransferLineUpdate) SetQuantity(v int) *StockTransferLineUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *StockTransferLineUpdate) SetNillableQuantity(v *int) *StockTransferLineUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *StockTransferLineUpdate) AddQuantity(v int) *StockTransferLineUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetTransfer sets the "transfer" edge to the StockTransfer entity.
func (_u *StockTransferLineUpdate) SetTransfer(v *StockTransfer) *StockTransferLineUpdate {
	return _u.SetTransferID(v.ID)
}

// Mutation returns the StockTransferLineMutation object of the builder.
func (_u *StockTransferLineUpdate) Mutation() *StockTransferLineMutation {
	return _u.mutation
}

// ClearTransfer clears the "transfer" edge to the StockTransfer entity.
func (_u *StockTransferLineUpdate) ClearTransfer() *StockTransferLineUpdate {
	_u.mutation.ClearTransfer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StockTransferLineUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockTransferLineUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StockTransferLineUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockTransferLineUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockTransferLineUpdate) check() error {
	if _u.mutation.TransferCleared() && len(_u.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StockTransferLine.transfer"`)
	}
	return nil
}

func (_u *StockTransferLineUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stocktransferline.Table, stocktransferline.Columns, sqlgraph.NewFieldSpec(stocktransferline.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(stocktransferline.FieldItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.VariantID(); ok {
		_spec.SetField(stocktransferline.FieldVariantID, field.TypeUUID, value)
	}
	if _u.mutation.VariantIDCleared() {
		_spec.ClearField(stocktransferline.FieldVariantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(stocktransferline.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(stocktransferline.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(stocktransferline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(stocktransferline.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.TransferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stocktransferline.TransferTable,
			Columns: []string{stocktransferline.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stocktransfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stocktransferline.TransferTable,
			Columns: []string{stocktransferline.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stocktransfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stocktransferline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StockTransferLineUpdateOne is the builder for updating a single StockTransferLine entity.
type StockTransferLineUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StockTransferLineMutation
}

// SetTransferID sets the "transfer_id" field.
func (_u *StockTransferLineUpdateOne) SetTransferID(v uuid.UUID) *StockTransferLineUpdateOne {
	_u.mutation.SetTransferID(v)
	return _u
}

// SetNillableTransferID sets the "transfer_id" field if the given value is not nil.
func (_u *StockTransferLineUpdateOne) SetNillableTransferID(v *uuid.UUID) *StockTransferLineUpdateOne {
	if v != nil {
		_u.SetTransferID(*v)
	}
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *StockTransferLineUpdateOne) SetItemID(v uuid.UUID) *StockTransferLineUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *StockTransferLineUpdateOne) SetNillableItemID(v *uuid.UUID) *StockTransferLineUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetVariantID sets the "variant_id" field.
func (_u *StockTransferLineUpdateOne) SetVariantID(v uuid.UUID) *StockTransferLineUpdateOne {
	_u.mutation.SetVariantID(v)
	return _u
}

// SetNillableVariantID sets the "variant_id" field if the given value is not nil.
func (_u *StockTransferLineUpdateOne) SetNillableVariantID(v *uuid.UUID) *StockTransferLineUpdateOne {
	if v != nil {
		_u.SetVariantID(*v)
	}
	return _u
}

// ClearVariantID clears the value of the "variant_id" field.
func (_u *StockTransferLineUpdateOne) ClearVariantID() *StockTransferLineUpdateOne {
	_u.mutation.ClearVariantID()
	return _u
}

// SetLotID sets the "lot_id" field.
func (_u *StockTransferLineUpdateOne) SetLotID(v uuid.UUID) *StockTransferLineUpdateOne {
	_u.mutation.SetLotID(v)
	return _u
}

// SetNillableLotID sets the "lot_id" field if the given value is not nil.
func (_u *StockTransferLineUpdateOne) SetNillableLotID(v *uuid.UUID) *StockTransferLineUpdateOne {
	if v != nil {
		_u.SetLotID(*v)
	}
	return _u
}

// ClearLotID clears the value of the "lot_id" field.
func (_u *StockTransferLineUpdateOne) ClearLotID() *StockTransferLineUpdateOne {
	_u.mutation.ClearLotID()
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *StockTransferLineUpdateOne) SetQuantity(v int) *StockTransferLineUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *StockTransferLineUpdateOne) SetNillableQuantity(v *int) *StockTransferLineUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *StockTransferLineUpdateOne) AddQuantity(v int) *StockTransferLineUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetTransfer sets the "transfer" edge to the StockTransfer entity.
func (_u *StockTransferLineUpdateOne) SetTransfer(v *StockTransfer) *StockTransferLineUpdateOne {
	return _u.SetTransferID(v.ID)
}

// Mutation returns the StockTransferLineMutation object of the builder.
func (_u *StockTransferLineUpdateOne) Mutation() *StockTransferLineMutation {
	return _u.mutation
}

// ClearTransfer clears the "transfer" edge to the StockTransfer entity.
func (_u *StockTransferLineUpdateOne) ClearTransfer() *StockTransferLineUpdateOne {
	_u.mutation.ClearTransfer()
	return _u
}

// Where appends a list predicates to the StockTransferLineUpdate builder.
func (_u *StockTransferLineUpdateOne) Where(ps ...predicate.StockTransferLine) *StockTransferLineUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StockTransferLineUpdateOne) Select(field string, fields ...string) *StockTransferLineUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StockTransferLine entity.
func (_u *StockTransferLineUpdateOne) Save(ctx context.Context) (*StockTransferLine, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StockTransferLineUpdateOne) SaveX(ctx context.Context) *StockTransferLine {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StockTransferLineUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StockTransferLineUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StockTransferLineUpdateOne) check() error {
	if _u.mutation.TransferCleared() && len(_u.mutation.TransferIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StockTransferLine.transfer"`)
	}
	return nil
}

func (_u *StockTransferLineUpdateOne) sqlSave(ctx context.Context) (_node *StockTransferLine, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stocktransferline.Table, stocktransferline.Columns, sqlgraph.NewFieldSpec(stocktransferline.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StockTransferLine.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stocktransferline.FieldID)
		for _, f := range fields {
			if !stocktransferline.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stocktransferline.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(stocktransferline.FieldItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.VariantID(); ok {
		_spec.SetField(stocktransferline.FieldVariantID, field.TypeUUID, value)
	}
	if _u.mutation.VariantIDCleared() {
		_spec.ClearField(stocktransferline.FieldVariantID, field.TypeUUID)
	}
	if value, ok := _u.mutation.LotID(); ok {
		_spec.SetField(stocktransferline.FieldLotID, field.TypeUUID, value)
	}
	if _u.mutation.LotIDCleared() {
		_spec.ClearField(stocktransferline.FieldLotID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(stocktransferline.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(stocktransferline.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.TransferCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stocktransferline.TransferTable,
			Columns: []string{stocktransferline.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stocktransfer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransferIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stocktransferline.TransferTable,
			Columns: []string{stocktransferline.TransferColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(stocktransfer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StockTransferLine{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stocktransferline.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
