// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/bengobox/inventory-service/internal/ent/tenantinventoryconfig"
)

// TenantInventoryConfigDelete is the builder for deleting a TenantInventoryConfig entity.
type TenantInventoryConfigDelete struct {
	config
	hooks    []Hook
	mutation *TenantInventoryConfigMutation
}

// Where appends a list predicates to the TenantInventoryConfigDelete builder.
func (_d *TenantInventoryConfigDelete) Where(ps ...predicate.TenantInventoryConfig) *TenantInventoryConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TenantInventoryConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantInventoryConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TenantInventoryConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tenantinventoryconfig.Table, sqlgraph.NewFieldSpec(tenantinventoryconfig.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TenantInventoryConfigDeleteOne is the builder for deleting a single TenantInventoryConfig entity.
type TenantInventoryConfigDeleteOne struct {
	_d *TenantInventoryConfigDelete
}

// Where appends a list predicates to the TenantInventoryConfigDelete builder.
func (_d *TenantInventoryConfigDeleteOne) Where(ps ...predicate.TenantInventoryConfig) *TenantInventoryConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TenantInventoryConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tenantinventoryconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TenantInventoryConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
