// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/inventory-service/internal/ent/predicate"
	"github.com/bengobox/inventory-service/internal/ent/useroutlet"
	"github.com/google/uuid"
)

// UserOutletUpdate is the builder for updating UserOutlet entities.
type UserOutletUpdate struct {
	config
	hooks    []Hook
	mutation *UserOutletMutation
}

// Where appends a list predicates to the UserOutletUpdate builder.
func (_u *UserOutletUpdate) Where(ps ...predicate.UserOutlet) *UserOutletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *UserOutletUpdate) SetTenantID(v uuid.UUID) *UserOutletUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UserOutletUpdate) SetNillableTenantID(v *uuid.UUID) *UserOutletUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserOutletUpdate) SetUserID(v uuid.UUID) *UserOutletUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOutletUpdate) SetNillableUserID(v *uuid.UUID) *UserOutletUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *UserOutletUpdate) SetOutletID(v uuid.UUID) *UserOutletUpdate {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *UserOutletUpdate) SetNillableOutletID(v *uuid.UUID) *UserOutletUpdate {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetIsHomeOutlet sets the "is_home_outlet" field.
func (_u *UserOutletUpdate) SetIsHomeOutlet(v bool) *UserOutletUpdate {
	_u.mutation.SetIsHomeOutlet(v)
	return _u
}

// SetNillableIsHomeOutlet sets the "is_home_outlet" field if the given value is not nil.
func (_u *UserOutletUpdate) SetNillableIsHomeOutlet(v *bool) *UserOutletUpdate {
	if v != nil {
		_u.SetIsHomeOutlet(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserOutletUpdate) SetAssignedBy(v uuid.UUID) *UserOutletUpdate {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserOutletUpdate) SetNillableAssignedBy(v *uuid.UUID) *UserOutletUpdate {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserOutletUpdate) ClearAssignedBy() *UserOutletUpdate {
	_u.mutation.ClearAssignedBy()
	return _u
}

// Mutation returns the UserOutletMutation object of the builder.
func (_u *UserOutletUpdate) Mutation() *UserOutletMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserOutletUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOutletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserOutletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOutletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserOutletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(useroutlet.Table, useroutlet.Columns, sqlgraph.NewFieldSpec(useroutlet.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(useroutlet.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useroutlet.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(useroutlet.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsHomeOutlet(); ok {
		_spec.SetField(useroutlet.FieldIsHomeOutlet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(useroutlet.FieldAssignedBy, field.TypeUUID, value)
	}
	if _u.mutation.AssignedByCleared() {
		_spec.ClearField(useroutlet.FieldAssignedBy, field.TypeUUID)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroutlet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserOutletUpdateOne is the builder for updating a single UserOutlet entity.
type UserOutletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOutletMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *UserOutletUpdateOne) SetTenantID(v uuid.UUID) *UserOutletUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UserOutletUpdateOne) SetNillableTenantID(v *uuid.UUID) *UserOutletUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserOutletUpdateOne) SetUserID(v uuid.UUID) *UserOutletUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOutletUpdateOne) SetNillableUserID(v *uuid.UUID) *UserOutletUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *UserOutletUpdateOne) SetOutletID(v uuid.UUID) *UserOutletUpdateOne {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *UserOutletUpdateOne) SetNillableOutletID(v *uuid.UUID) *UserOutletUpdateOne {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetIsHomeOutlet sets the "is_home_outlet" field.
func (_u *UserOutletUpdateOne) SetIsHomeOutlet(v bool) *UserOutletUpdateOne {
	_u.mutation.SetIsHomeOutlet(v)
	return _u
}

// SetNillableIsHomeOutlet sets the "is_home_outlet" field if the given value is not nil.
func (_u *UserOutletUpdateOne) SetNillableIsHomeOutlet(v *bool) *UserOutletUpdateOne {
	if v != nil {
		_u.SetIsHomeOutlet(*v)
	}
	return _u
}

// SetAssignedBy sets the "assigned_by" field.
func (_u *UserOutletUpdateOne) SetAssignedBy(v uuid.UUID) *UserOutletUpdateOne {
	_u.mutation.SetAssignedBy(v)
	return _u
}

// SetNillableAssignedBy sets the "assigned_by" field if the given value is not nil.
func (_u *UserOutletUpdateOne) SetNillableAssignedBy(v *uuid.UUID) *UserOutletUpdateOne {
	if v != nil {
		_u.SetAssignedBy(*v)
	}
	return _u
}

// ClearAssignedBy clears the value of the "assigned_by" field.
func (_u *UserOutletUpdateOne) ClearAssignedBy() *UserOutletUpdateOne {
	_u.mutation.ClearAssignedBy()
	return _u
}

// Mutation returns the UserOutletMutation object of the builder.
func (_u *UserOutletUpdateOne) Mutation() *UserOutletMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserOutletUpdate builder.
func (_u *UserOutletUpdateOne) Where(ps ...predicate.UserOutlet) *UserOutletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserOutletUpdateOne) Select(field string, fields ...string) *UserOutletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserOutlet entity.
func (_u *UserOutletUpdateOne) Save(ctx context.Context) (*UserOutlet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOutletUpdateOne) SaveX(ctx context.Context) *UserOutlet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserOutletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOutletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *UserOutletUpdateOne) sqlSave(ctx context.Context) (_node *UserOutlet, err error) {
	_spec := sqlgraph.NewUpdateSpec(useroutlet.Table, useroutlet.Columns, sqlgraph.NewFieldSpec(useroutlet.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserOutlet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroutlet.FieldID)
		for _, f := range fields {
			if !useroutlet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useroutlet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(useroutlet.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(useroutlet.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(useroutlet.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsHomeOutlet(); ok {
		_spec.SetField(useroutlet.FieldIsHomeOutlet, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AssignedBy(); ok {
		_spec.SetField(useroutlet.FieldAssignedBy, field.TypeUUID, value)
	}
	if _u.mutation.AssignedByCleared() {
		_spec.ClearField(useroutlet.FieldAssignedBy, field.TypeUUID)
	}
	_node = &UserOutlet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroutlet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
