// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Consumption is the predicate function for consumption builders.
type Consumption func(*sql.Selector)

// InventoryBalance is the predicate function for inventorybalance builders.
type InventoryBalance func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// Warehouse is the predicate function for warehouse builders.
type Warehouse func(*sql.Selector)
