// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldEventItemID holds the string denoting the event_item_id field in the database.
	FieldEventItemID = "event_item_id"
	// FieldOrderID holds the string denoting the order_id field in the database.
	FieldOrderID = "order_id"
	// FieldTierID holds the string denoting the tier_id field in the database.
	FieldTierID = "tier_id"
	// FieldTierName holds the string denoting the tier_name field in the database.
	FieldTierName = "tier_name"
	// FieldBuyerID holds the string denoting the buyer_id field in the database.
	FieldBuyerID = "buyer_id"
	// FieldBuyerName holds the string denoting the buyer_name field in the database.
	FieldBuyerName = "buyer_name"
	// FieldBuyerEmail holds the string denoting the buyer_email field in the database.
	FieldBuyerEmail = "buyer_email"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldUnitPrice holds the string denoting the unit_price field in the database.
	FieldUnitPrice = "unit_price"
	// FieldTotalPrice holds the string denoting the total_price field in the database.
	FieldTotalPrice = "total_price"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldValidFrom holds the string denoting the valid_from field in the database.
	FieldValidFrom = "valid_from"
	// FieldValidUntil holds the string denoting the valid_until field in the database.
	FieldValidUntil = "valid_until"
	// FieldRedeemedAt holds the string denoting the redeemed_at field in the database.
	FieldRedeemedAt = "redeemed_at"
	// FieldRedeemedBy holds the string denoting the redeemed_by field in the database.
	FieldRedeemedBy = "redeemed_by"
	// FieldCheckInLocation holds the string denoting the check_in_location field in the database.
	FieldCheckInLocation = "check_in_location"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldEventItemID,
	FieldOrderID,
	FieldTierID,
	FieldTierName,
	FieldBuyerID,
	FieldBuyerName,
	FieldBuyerEmail,
	FieldQuantity,
	FieldUnitPrice,
	FieldTotalPrice,
	FieldCurrency,
	FieldCode,
	FieldStatus,
	FieldValidFrom,
	FieldValidUntil,
	FieldRedeemedAt,
	FieldRedeemedBy,
	FieldCheckInLocation,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultQuantity holds the default value on creation for the "quantity" field.
	DefaultQuantity int
	// DefaultUnitPrice holds the default value on creation for the "unit_price" field.
	DefaultUnitPrice float64
	// DefaultTotalPrice holds the default value on creation for the "total_price" field.
	DefaultTotalPrice float64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusIssued is the default value of the Status enum.
const DefaultStatus = StatusIssued

// Status values.
const (
	StatusIssued    Status = "issued"
	StatusRedeemed  Status = "redeemed"
	StatusCancelled Status = "cancelled"
	StatusRefunded  Status = "refunded"
	StatusVoid      Status = "void"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusIssued, StatusRedeemed, StatusCancelled, StatusRefunded, StatusVoid:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByEventItemID orders the results by the event_item_id field.
func ByEventItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventItemID, opts...).ToFunc()
}

// ByOrderID orders the results by the order_id field.
func ByOrderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrderID, opts...).ToFunc()
}

// ByTierID orders the results by the tier_id field.
func ByTierID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierID, opts...).ToFunc()
}

// ByTierName orders the results by the tier_name field.
func ByTierName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierName, opts...).ToFunc()
}

// ByBuyerID orders the results by the buyer_id field.
func ByBuyerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerID, opts...).ToFunc()
}

// ByBuyerName orders the results by the buyer_name field.
func ByBuyerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerName, opts...).ToFunc()
}

// ByBuyerEmail orders the results by the buyer_email field.
func ByBuyerEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyerEmail, opts...).ToFunc()
}

// ByQuantity orders the results by the quantity field.
func ByQuantity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantity, opts...).ToFunc()
}

// ByUnitPrice orders the results by the unit_price field.
func ByUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitPrice, opts...).ToFunc()
}

// ByTotalPrice orders the results by the total_price field.
func ByTotalPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalPrice, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByValidFrom orders the results by the valid_from field.
func ByValidFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidFrom, opts...).ToFunc()
}

// ByValidUntil orders the results by the valid_until field.
func ByValidUntil(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidUntil, opts...).ToFunc()
}

// ByRedeemedAt orders the results by the redeemed_at field.
func ByRedeemedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedAt, opts...).ToFunc()
}

// ByRedeemedBy orders the results by the redeemed_by field.
func ByRedeemedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedBy, opts...).ToFunc()
}

// ByCheckInLocation orders the results by the check_in_location field.
func ByCheckInLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckInLocation, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
