// Code generated by ent, DO NOT EDIT.

package item

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the item type in the database.
	Label = "item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldUnitID holds the string denoting the unit_id field in the database.
	FieldUnitID = "unit_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldBarcode holds the string denoting the barcode field in the database.
	FieldBarcode = "barcode"
	// FieldBarcodeType holds the string denoting the barcode_type field in the database.
	FieldBarcodeType = "barcode_type"
	// FieldRequiresAgeVerification holds the string denoting the requires_age_verification field in the database.
	FieldRequiresAgeVerification = "requires_age_verification"
	// FieldIsControlledSubstance holds the string denoting the is_controlled_substance field in the database.
	FieldIsControlledSubstance = "is_controlled_substance"
	// FieldIsPerishable holds the string denoting the is_perishable field in the database.
	FieldIsPerishable = "is_perishable"
	// FieldTrackSerialNumbers holds the string denoting the track_serial_numbers field in the database.
	FieldTrackSerialNumbers = "track_serial_numbers"
	// FieldTrackLots holds the string denoting the track_lots field in the database.
	FieldTrackLots = "track_lots"
	// FieldWeightKg holds the string denoting the weight_kg field in the database.
	FieldWeightKg = "weight_kg"
	// FieldDimensionsCm holds the string denoting the dimensions_cm field in the database.
	FieldDimensionsCm = "dimensions_cm"
	// FieldDurationMinutes holds the string denoting the duration_minutes field in the database.
	FieldDurationMinutes = "duration_minutes"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTenant holds the string denoting the tenant edge name in mutations.
	EdgeTenant = "tenant"
	// EdgeBalances holds the string denoting the balances edge name in mutations.
	EdgeBalances = "balances"
	// EdgeRecipeIngredients holds the string denoting the recipe_ingredients edge name in mutations.
	EdgeRecipeIngredients = "recipe_ingredients"
	// EdgeUnits holds the string denoting the units edge name in mutations.
	EdgeUnits = "units"
	// EdgeVariants holds the string denoting the variants edge name in mutations.
	EdgeVariants = "variants"
	// EdgeAssets holds the string denoting the assets edge name in mutations.
	EdgeAssets = "assets"
	// EdgeTranslations holds the string denoting the translations edge name in mutations.
	EdgeTranslations = "translations"
	// EdgeModifierGroups holds the string denoting the modifier_groups edge name in mutations.
	EdgeModifierGroups = "modifier_groups"
	// EdgeLots holds the string denoting the lots edge name in mutations.
	EdgeLots = "lots"
	// EdgeCustomFieldValues holds the string denoting the custom_field_values edge name in mutations.
	EdgeCustomFieldValues = "custom_field_values"
	// EdgeBundle holds the string denoting the bundle edge name in mutations.
	EdgeBundle = "bundle"
	// EdgeBundleComponents holds the string denoting the bundle_components edge name in mutations.
	EdgeBundleComponents = "bundle_components"
	// EdgeWarranties holds the string denoting the warranties edge name in mutations.
	EdgeWarranties = "warranties"
	// EdgeItemCategory holds the string denoting the item_category edge name in mutations.
	EdgeItemCategory = "item_category"
	// Table holds the table name of the item in the database.
	Table = "items"
	// TenantTable is the table that holds the tenant relation/edge.
	TenantTable = "items"
	// TenantInverseTable is the table name for the Tenant entity.
	// It exists in this package in order to avoid circular dependency with the "tenant" package.
	TenantInverseTable = "tenants"
	// TenantColumn is the table column denoting the tenant relation/edge.
	TenantColumn = "tenant_id"
	// BalancesTable is the table that holds the balances relation/edge.
	BalancesTable = "inventory_balances"
	// BalancesInverseTable is the table name for the InventoryBalance entity.
	// It exists in this package in order to avoid circular dependency with the "inventorybalance" package.
	BalancesInverseTable = "inventory_balances"
	// BalancesColumn is the table column denoting the balances relation/edge.
	BalancesColumn = "item_id"
	// RecipeIngredientsTable is the table that holds the recipe_ingredients relation/edge.
	RecipeIngredientsTable = "recipe_ingredients"
	// RecipeIngredientsInverseTable is the table name for the RecipeIngredient entity.
	// It exists in this package in order to avoid circular dependency with the "recipeingredient" package.
	RecipeIngredientsInverseTable = "recipe_ingredients"
	// RecipeIngredientsColumn is the table column denoting the recipe_ingredients relation/edge.
	RecipeIngredientsColumn = "item_id"
	// UnitsTable is the table that holds the units relation/edge.
	UnitsTable = "items"
	// UnitsInverseTable is the table name for the Unit entity.
	// It exists in this package in order to avoid circular dependency with the "unit" package.
	UnitsInverseTable = "units"
	// UnitsColumn is the table column denoting the units relation/edge.
	UnitsColumn = "unit_id"
	// VariantsTable is the table that holds the variants relation/edge.
	VariantsTable = "item_variants"
	// VariantsInverseTable is the table name for the ItemVariant entity.
	// It exists in this package in order to avoid circular dependency with the "itemvariant" package.
	VariantsInverseTable = "item_variants"
	// VariantsColumn is the table column denoting the variants relation/edge.
	VariantsColumn = "item_id"
	// AssetsTable is the table that holds the assets relation/edge.
	AssetsTable = "item_assets"
	// AssetsInverseTable is the table name for the ItemAsset entity.
	// It exists in this package in order to avoid circular dependency with the "itemasset" package.
	AssetsInverseTable = "item_assets"
	// AssetsColumn is the table column denoting the assets relation/edge.
	AssetsColumn = "item_id"
	// TranslationsTable is the table that holds the translations relation/edge.
	TranslationsTable = "item_translations"
	// TranslationsInverseTable is the table name for the ItemTranslation entity.
	// It exists in this package in order to avoid circular dependency with the "itemtranslation" package.
	TranslationsInverseTable = "item_translations"
	// TranslationsColumn is the table column denoting the translations relation/edge.
	TranslationsColumn = "item_id"
	// ModifierGroupsTable is the table that holds the modifier_groups relation/edge.
	ModifierGroupsTable = "modifier_groups"
	// ModifierGroupsInverseTable is the table name for the ModifierGroup entity.
	// It exists in this package in order to avoid circular dependency with the "modifiergroup" package.
	ModifierGroupsInverseTable = "modifier_groups"
	// ModifierGroupsColumn is the table column denoting the modifier_groups relation/edge.
	ModifierGroupsColumn = "item_id"
	// LotsTable is the table that holds the lots relation/edge.
	LotsTable = "inventory_lots"
	// LotsInverseTable is the table name for the InventoryLot entity.
	// It exists in this package in order to avoid circular dependency with the "inventorylot" package.
	LotsInverseTable = "inventory_lots"
	// LotsColumn is the table column denoting the lots relation/edge.
	LotsColumn = "item_id"
	// CustomFieldValuesTable is the table that holds the custom_field_values relation/edge.
	CustomFieldValuesTable = "custom_field_values"
	// CustomFieldValuesInverseTable is the table name for the CustomFieldValue entity.
	// It exists in this package in order to avoid circular dependency with the "customfieldvalue" package.
	CustomFieldValuesInverseTable = "custom_field_values"
	// CustomFieldValuesColumn is the table column denoting the custom_field_values relation/edge.
	CustomFieldValuesColumn = "item_id"
	// BundleTable is the table that holds the bundle relation/edge.
	BundleTable = "bundles"
	// BundleInverseTable is the table name for the Bundle entity.
	// It exists in this package in order to avoid circular dependency with the "bundle" package.
	BundleInverseTable = "bundles"
	// BundleColumn is the table column denoting the bundle relation/edge.
	BundleColumn = "item_id"
	// BundleComponentsTable is the table that holds the bundle_components relation/edge.
	BundleComponentsTable = "bundle_components"
	// BundleComponentsInverseTable is the table name for the BundleComponent entity.
	// It exists in this package in order to avoid circular dependency with the "bundlecomponent" package.
	BundleComponentsInverseTable = "bundle_components"
	// BundleComponentsColumn is the table column denoting the bundle_components relation/edge.
	BundleComponentsColumn = "component_item_id"
	// WarrantiesTable is the table that holds the warranties relation/edge.
	WarrantiesTable = "warranties"
	// WarrantiesInverseTable is the table name for the Warranty entity.
	// It exists in this package in order to avoid circular dependency with the "warranty" package.
	WarrantiesInverseTable = "warranties"
	// WarrantiesColumn is the table column denoting the warranties relation/edge.
	WarrantiesColumn = "item_id"
	// ItemCategoryTable is the table that holds the item_category relation/edge.
	ItemCategoryTable = "items"
	// ItemCategoryInverseTable is the table name for the ItemCategory entity.
	// It exists in this package in order to avoid circular dependency with the "itemcategory" package.
	ItemCategoryInverseTable = "item_categories"
	// ItemCategoryColumn is the table column denoting the item_category relation/edge.
	ItemCategoryColumn = "category_id"
)

// Columns holds all SQL columns for item fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldSku,
	FieldName,
	FieldDescription,
	FieldCategoryID,
	FieldUnitID,
	FieldType,
	FieldIsActive,
	FieldImageURL,
	FieldBarcode,
	FieldBarcodeType,
	FieldRequiresAgeVerification,
	FieldIsControlledSubstance,
	FieldIsPerishable,
	FieldTrackSerialNumbers,
	FieldTrackLots,
	FieldWeightKg,
	FieldDimensionsCm,
	FieldDurationMinutes,
	FieldTags,
	FieldMetadata,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SkuValidator is a validator for the "sku" field. It is called by the builders before save.
	SkuValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultRequiresAgeVerification holds the default value on creation for the "requires_age_verification" field.
	DefaultRequiresAgeVerification bool
	// DefaultIsControlledSubstance holds the default value on creation for the "is_controlled_substance" field.
	DefaultIsControlledSubstance bool
	// DefaultIsPerishable holds the default value on creation for the "is_perishable" field.
	DefaultIsPerishable bool
	// DefaultTrackSerialNumbers holds the default value on creation for the "track_serial_numbers" field.
	DefaultTrackSerialNumbers bool
	// DefaultTrackLots holds the default value on creation for the "track_lots" field.
	DefaultTrackLots bool
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata map[string]interface{}
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Type defines the type for the "type" enum field.
type Type string

// TypeGOODS is the default value of the Type enum.
const DefaultType = TypeGOODS

// Type values.
const (
	TypeGOODS      Type = "GOODS"
	TypeSERVICE    Type = "SERVICE"
	TypeRECIPE     Type = "RECIPE"
	TypeINGREDIENT Type = "INGREDIENT"
	TypeVOUCHER    Type = "VOUCHER"
	TypeEQUIPMENT  Type = "EQUIPMENT"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeGOODS, TypeSERVICE, TypeRECIPE, TypeINGREDIENT, TypeVOUCHER, TypeEQUIPMENT:
		return nil
	default:
		return fmt.Errorf("item: invalid enum value for type field: %q", _type)
	}
}

// OrderOption defines the ordering options for the Item queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// BySku orders the results by the sku field.
func BySku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSku, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByUnitID orders the results by the unit_id field.
func ByUnitID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnitID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByBarcode orders the results by the barcode field.
func ByBarcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarcode, opts...).ToFunc()
}

// ByBarcodeType orders the results by the barcode_type field.
func ByBarcodeType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarcodeType, opts...).ToFunc()
}

// ByRequiresAgeVerification orders the results by the requires_age_verification field.
func ByRequiresAgeVerification(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequiresAgeVerification, opts...).ToFunc()
}

// ByIsControlledSubstance orders the results by the is_controlled_substance field.
func ByIsControlledSubstance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsControlledSubstance, opts...).ToFunc()
}

// ByIsPerishable orders the results by the is_perishable field.
func ByIsPerishable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPerishable, opts...).ToFunc()
}

// ByTrackSerialNumbers orders the results by the track_serial_numbers field.
func ByTrackSerialNumbers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackSerialNumbers, opts...).ToFunc()
}

// ByTrackLots orders the results by the track_lots field.
func ByTrackLots(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrackLots, opts...).ToFunc()
}

// ByWeightKg orders the results by the weight_kg field.
func ByWeightKg(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeightKg, opts...).ToFunc()
}

// ByDurationMinutes orders the results by the duration_minutes field.
func ByDurationMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationMinutes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantField orders the results by tenant field.
func ByTenantField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTenantStep(), sql.OrderByField(field, opts...))
	}
}

// ByBalancesCount orders the results by balances count.
func ByBalancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBalancesStep(), opts...)
	}
}

// ByBalances orders the results by balances terms.
func ByBalances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBalancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecipeIngredientsCount orders the results by recipe_ingredients count.
func ByRecipeIngredientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecipeIngredientsStep(), opts...)
	}
}

// ByRecipeIngredients orders the results by recipe_ingredients terms.
func ByRecipeIngredients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecipeIngredientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUnitsField orders the results by units field.
func ByUnitsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUnitsStep(), sql.OrderByField(field, opts...))
	}
}

// ByVariantsCount orders the results by variants count.
func ByVariantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVariantsStep(), opts...)
	}
}

// ByVariants orders the results by variants terms.
func ByVariants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVariantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAssetsCount orders the results by assets count.
func ByAssetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAssetsStep(), opts...)
	}
}

// ByAssets orders the results by assets terms.
func ByAssets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAssetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTranslationsCount orders the results by translations count.
func ByTranslationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTranslationsStep(), opts...)
	}
}

// ByTranslations orders the results by translations terms.
func ByTranslations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTranslationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByModifierGroupsCount orders the results by modifier_groups count.
func ByModifierGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newModifierGroupsStep(), opts...)
	}
}

// ByModifierGroups orders the results by modifier_groups terms.
func ByModifierGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModifierGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLotsCount orders the results by lots count.
func ByLotsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLotsStep(), opts...)
	}
}

// ByLots orders the results by lots terms.
func ByLots(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLotsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCustomFieldValuesCount orders the results by custom_field_values count.
func ByCustomFieldValuesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomFieldValuesStep(), opts...)
	}
}

// ByCustomFieldValues orders the results by custom_field_values terms.
func ByCustomFieldValues(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomFieldValuesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBundleField orders the results by bundle field.
func ByBundleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBundleStep(), sql.OrderByField(field, opts...))
	}
}

// ByBundleComponentsCount orders the results by bundle_components count.
func ByBundleComponentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBundleComponentsStep(), opts...)
	}
}

// ByBundleComponents orders the results by bundle_components terms.
func ByBundleComponents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBundleComponentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWarrantiesCount orders the results by warranties count.
func ByWarrantiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWarrantiesStep(), opts...)
	}
}

// ByWarranties orders the results by warranties terms.
func ByWarranties(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWarrantiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByItemCategoryField orders the results by item_category field.
func ByItemCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newItemCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newTenantStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TenantInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TenantTable, TenantColumn),
	)
}
func newBalancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BalancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BalancesTable, BalancesColumn),
	)
}
func newRecipeIngredientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecipeIngredientsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecipeIngredientsTable, RecipeIngredientsColumn),
	)
}
func newUnitsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UnitsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UnitsTable, UnitsColumn),
	)
}
func newVariantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VariantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VariantsTable, VariantsColumn),
	)
}
func newAssetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AssetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AssetsTable, AssetsColumn),
	)
}
func newTranslationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TranslationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TranslationsTable, TranslationsColumn),
	)
}
func newModifierGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModifierGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ModifierGroupsTable, ModifierGroupsColumn),
	)
}
func newLotsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LotsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LotsTable, LotsColumn),
	)
}
func newCustomFieldValuesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomFieldValuesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CustomFieldValuesTable, CustomFieldValuesColumn),
	)
}
func newBundleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BundleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, BundleTable, BundleColumn),
	)
}
func newBundleComponentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BundleComponentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BundleComponentsTable, BundleComponentsColumn),
	)
}
func newWarrantiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WarrantiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WarrantiesTable, WarrantiesColumn),
	)
}
func newItemCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ItemCategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ItemCategoryTable, ItemCategoryColumn),
	)
}
